In [1]:
cd ..

/Users/camila.cusicanqui/Documents/klar/mini-tasks

In [2]:
from data_ingest import get_db_conn
import pandas as pd
import numpy as np
import gspread
import matplotlib.pyplot as plt
from typing import List, Tuple, Dict
import seaborn as sns
from datetime import date, timedelta, datetime
pd.set_option('display.max_columns', None)
from openai import OpenAI
# from import agents Agent, Runner          
import yaml
import os
import json

In [3]:
import asyncio
from agents import Agent, Runner
from agents import Agent, Runner, function_tool
import datetime as dt
import polars as pl
import docx2txt
from pydantic import BaseModel, Field
from typing import List, Optional

In [4]:
# transform docx to text
process_context_txt = open("agents-automization/OPS-FRA-009 - Análisis de comercios fraudulentos.txt", "r+")
process_context_txt = process_context_txt.read()

In [5]:
# read yaml config file 


with open("/Users/camila.cusicanqui/Documents/klar/mini-tasks/.config/openai-credentials.yaml", "r") as file:
    config = yaml.safe_load(file)

api_key = config["key"]

In [6]:
os.environ["OPENAI_API_KEY"] = api_key

In [7]:
def common_commerces_from_cb(klrids: List[str], merchant_name = str) -> Tuple[pd.DataFrame, pd.DataFrame]:
    # query here that finds the transactions of the klrids and which commmerces they interacted with
    # klrids_revise = after_df["klrid"].unique()
    # merchant1_cards

    number_of_klrids = len(klrids)
    revise_trx_users_str = ",".join([f"'{user}'" for user in klrids])
    revise_trx_user_query = f"""
        with txn_base as (
            select
                t.user_id,
                t.timestamp_mx_created_at as trx_mx_time,
                t.source_external_id as klrid,
                t.type,
                t."state",
                t.merchant_name,
                t.description,
                t.transaction_id,
                t.amount,
                case
                    when upper(t.transaction_id) like 'PARABILIUM:%'
                        and nullif(split_part(t.transaction_id, ':', 2), '') ~ '^[0-9]+$'
                    then split_part(t.transaction_id, ':', 2)

                    when t.transaction_id ~ '^[0-9]+$'
                    then t.transaction_id

                    else null
                end as operation_id_str
            from analytics_bi.transactions t
            where
                t.source_external_id in ({revise_trx_users_str})
                and t.type = 'PURCHASE'
                and t.timestamp_mx_created_at >= '2026-02-10'::date
        ),

        txn_enriched as (
            select
                tb.*,
                o.omi_id_operacion,
                o.c022,
                o.c063,
                pt.t_c0,
                op.sucursal as merchant_affiliation,
                op.terminal as num_terminal,
                regexp_substr(o.c063, 'CE[0-9]5[^!]*') as ce_token
            from txn_base tb
            left join is_pii_parabilium.operation_iso_messages_temp o
                on o.omi_id_operacion = tb.operation_id_str
            left join
            is_pii_parabilium.operaciones op on op.id_operacion = tb.operation_id_str
            left join is_pii_parabilium.parabilium_transactions pt
                on pt.id = case
                    when tb.operation_id_str ~ '^[0-9]+$' then tb.operation_id_str::bigint
                    else null
                end
        ),

        txn_3ds as (
            select
                te.*,

                case
                    when substring(te.c022, 1, 2) = '00' then 'Unknown'
                    when substring(te.c022, 1, 2) = '01' then 'CNP Manual'
                    when substring(te.c022, 1, 2) = '05' then 'Integrated Circuit Read'
                    when substring(te.c022, 1, 2) = '07' then 'Contactless'
                    when substring(te.c022, 1, 2) = '10' then 'CNP Card On File'
                    when substring(te.c022, 1, 2) = '80' then 'Fallback'
                    when substring(te.c022, 1, 2) = '90' then 'Magnetic stripe read'
                    else null
                end as pos_entry_mode,

                case
                    when te.t_c0 is null then 'unknown'
                    when substring(te.t_c0, 32, 1) = '1' then 'has cvv'
                    else 'no cvv'
                end::varchar as cvv_ind,

                case
                    when te.ce_token is not null
                        and position('01' in te.ce_token) > 0
                    then substring(te.ce_token from position('01' in te.ce_token) + 2 for 2)
                    else null
                end as leading_indicator
            from txn_enriched te
        )

        select
            tc.*,
            case
                when tc.ce_token is null then 'NO_3DS'
                when tc.leading_indicator in ('kA','kB','kC','kE','kF','kJ','kR','kS','kG','kO','kP')
                    then '3DS_AUTHENTICATED'
                when tc.leading_indicator in ('kN','kW','kU','kX')
                    then '3DS_NOT_AUTHENTICATED'
                else 'UNKNOWN'
            end as three_ds_status,

            case
                when tc.ce_token is null then 'NO_3DS'
                when tc.leading_indicator in ('kA','kC','kE','kO')
                    then 'FRICTIONLESS'
                when tc.leading_indicator in ('kB','kS','kG','kP')
                    then 'CHALLENGE'
                when tc.leading_indicator in ('kN','kW','kU','kX')
                    then 'EXEMPT_OR_INFO'
                else 'UNKNOWN'
            end as three_ds_flow,

            c.product_type,
            c.card_type,
            c.status
        from txn_3ds tc
        left join is_provider_parabilium.cards c
            on c.id = tc.klrid

    """
    revise_users_df = pd.read_sql(revise_trx_user_query, get_db_conn())
    revise_users_df["country"] = revise_users_df["merchant_name"].str[-2:]
    revise_users_df.sort_values(by=['klrid','trx_mx_time'], inplace=True)
    top_commerces = revise_users_df.groupby(["merchant_name"])["klrid"].nunique().sort_values(ascending=False).reset_index(name="unique_klrids")
    top_commerces = top_commerces[(top_commerces["merchant_name"] != merchant_name) & (top_commerces["unique_klrids"] > np.floor(number_of_klrids*0.75))]
    revise_users_df = revise_users_df[(revise_users_df["merchant_name"] == merchant_name) | revise_users_df["merchant_name"].isin(top_commerces["merchant_name"].unique())]
    return top_commerces, revise_users_df

In [8]:
# def chargeback_merchant_summary(merchants_to_block: List[str]) -> Dict[str, Dict]:


#     def _series_to_dict(series: pd.Series) -> Dict:
#         return {str(idx): int(value) for idx, value in series.fillna("null").items()}

#     def _dataframe_to_records(df: pd.DataFrame) -> List[Dict]:
#         if df.empty:
#             return []

#         serializable_df = df.copy()
#         for column in serializable_df.columns:
#             if pd.api.types.is_datetime64_any_dtype(serializable_df[column]):
#                 serializable_df[column] = serializable_df[column].astype(str)

#         return serializable_df.to_dict(orient="records")

#     report = {}
#     timeframes = {
#         "1_week": (dt.datetime.now() - dt.timedelta(days=7)).strftime('%Y-%m-%d %H:%M:%S'),
#         "1_month": (dt.datetime.now() - dt.timedelta(days=30)).strftime('%Y-%m-%d %H:%M:%S'),
#         "ytd": dt.datetime(dt.datetime.now().year, 1, 1).strftime('%Y-%m-%d %H:%M:%S'),
#     }

#     for merchant in merchants_to_block:
#         merchant_name = merchant.replace('*', '')
#         merchant_cb_df = cb_df[cb_df["merchant"] == merchant_name].copy()

#         if merchant_cb_df.empty:
#             report[merchant_name] = {
#                 "merchant_name": merchant_name,
#                 "first_appearance": None,
#                 "last_appearance": None,
#                 "shared_commerces_summary": [],
#                 "shared_commerces_transactions": [],
#                 "timeframes": {},
#             }
#             continue

#         klrids_merchant = merchant_cb_df["klrid"].unique().tolist()
#         top_commerces, revise_users_df = common_commerces_from_cb(
#             klrids=klrids_merchant,
#             merchant_name=merchant_name,
#         )

#         merchant_summary = {
#             "merchant_name": merchant_name,
#             "first_appearance": str(merchant_cb_df["trx_timestamp_mx"].min()),
#             "last_appearance": str(merchant_cb_df["trx_timestamp_mx"].max()),
#             "shared_commerces_summary": _dataframe_to_records(top_commerces),
#             "shared_commerces_transactions": _dataframe_to_records(revise_users_df),
#             "timeframes": {},
#         }

#         for timeframe_name, start_time in timeframes.items():
#             timeframe_df = merchant_cb_df[merchant_cb_df["trx_timestamp_mx"] >= start_time]
#             merchant_summary["timeframes"][timeframe_name] = {
#                 "start_time": start_time,
#                 "num_chargebacks_reported": int(timeframe_df["transaction_id"].nunique()),
#                 "num_unique_users": int(timeframe_df["user_id"].nunique()),
#                 "num_klrids_per_card_type": _series_to_dict(timeframe_df.groupby("card_type")["klrid"].nunique()),
#                 "num_klrids_per_product_type": _series_to_dict(timeframe_df.groupby("product_type")["klrid"].nunique()),
#                 "num_transactions_per_cvv_indicator": _series_to_dict(timeframe_df.groupby("cvv_ind")["transaction_id"].nunique()),
#                 "num_transactions_per_3ds_status": _series_to_dict(timeframe_df.groupby("three_ds_status")["transaction_id"].nunique()),
#             }

#         report[merchant_name] = merchant_summary

#     return report

In [9]:
class FraudFinding(BaseModel):
    merchant_name: str
    risk_level: str = Field(description="low, medium, high")
    summary: str
    suspicious_signals: List[str]
    recommendation: str
    confidence: float

## Agent

In [10]:
# add requirements of blocking
# safety net alerts and ADC alerts of copying information

In [11]:
# add definition of response codes
# conectarme al google sheets BL Merchants
# hay otro comercio involucrado del comercio ?
    # los otros comercios en común están bloqueados o no ?
# deadline
    # what we need
    # what we're going to work on 
# expected deadline for the project

# Full implementation AI + text summaries + testing

*Logic*

1. receive the merchant

2. run the necessary prompts and sections

3. construct the final prompt

4. build the for statement to receive the merchant name in the list

### example merchants

# Full pipeline

In [ ]:
def build_merchant_activity_query(merchant_name: str, blocked_at_mx: str) -> str:
    """
    Builds the query used to get activity for a blocked merchant up to the current
    blocked timestamp in Mexico City timezone.
    """
    merchant_sql = merchant_name.replace("'", "''")
    # convert blocked date str to datetime
    blocked_at_mx = dt.datetime.strptime(blocked_at_mx, "%Y-%m-%d %H:%M:%S")
    blocked_at_sql = blocked_at_mx.strftime('%Y-%m-%d %H:%M:%S')

    return f"""
        WITH ytd_base AS (
        SELECT DISTINCT
            COALESCE(NULLIF(SPLIT_PART(transaction_id, 'PARABILIUM:', 2), ''), transaction_id) AS transaction_id_clean,
            user_id,
            state
        FROM analytics_bi.transactions__ytd
        WHERE type = 'PURCHASE'
        )
        SELECT
        CAST(ot.id_operacion AS VARCHAR(100)) AS transaction_id,
        convert_timezone('UTC','America/Mexico_City', ot.fecharegistro) AS tx_date_mx,
        CAST(convert_timezone('UTC','America/Mexico_City', ot.fecharegistro) AS DATE) AS tx_date_mx_date,
        ot.operador AS merchant_name,
        CAST(TRIM(ot.cod_respuesta) AS INTEGER) AS cod_respuesta,
        y.user_id,
        y.state,
        c.card_type,
        c.product_type,
        CASE
            WHEN pt.t_c0 IS NULL THEN 'unknown'
            WHEN SUBSTRING(pt.t_c0, 32, 1) = '1' THEN 'has cvv'
            ELSE 'no cvv'
        END AS cvv,
        CASE
            WHEN POSITION('! C0' IN oimt.c063) > 0
            THEN SUBSTRING(oimt.c063, POSITION('! C0' IN oimt.c063) + 28, 1)
            ELSE NULL
        END AS eci
        FROM is_pii_parabilium.operations_temp ot
        LEFT JOIN is_pii_parabilium.operaciones o
        ON o.id_operacion = ot.id_operacion
        LEFT JOIN is_provider_parabilium.cards c
        ON c.id = o.klrid
        LEFT JOIN is_pii_parabilium.operation_iso_messages_temp oimt
        ON oimt.omi_id_operacion = ot.id_operacion
        LEFT JOIN is_pii_parabilium.parabilium_transactions pt
        ON pt.id = ot.id_operacion
        LEFT JOIN ytd_base y
        ON y.transaction_id_clean = CAST(ot.id_operacion AS VARCHAR(100))
        WHERE ot.operador = '{merchant_sql}'
        AND convert_timezone('UTC','America/Mexico_City', ot.fecharegistro) <= TIMESTAMP '{blocked_at_sql}'
        AND EXTRACT(YEAR FROM convert_timezone('UTC','America/Mexico_City', ot.fecharegistro)) = EXTRACT(YEAR FROM TIMESTAMP '{blocked_at_sql}');
            """

In [13]:
def build_merchant_activity_summary(raw_df: pl.DataFrame, blocked_at_mx: str) -> pl.DataFrame:
    """
    Builds the merchant activity summary in Polars for T1D, T1W and YTD windows.
    """
    rows = []
    target_response_codes = [0, 14, 87, 51]
    blocked_at_dt = dt.datetime.strptime(blocked_at_mx, "%Y-%m-%d %H:%M:%S")
    block_date_mx = blocked_at_dt.date()
    week_start_mx = block_date_mx - dt.timedelta(days=6)
    year_start_mx = dt.date(block_date_mx.year, 1, 1)

    def safe_value(value):
        if value is None:
            return None
        if isinstance(value, dt.datetime):
            return value.strftime('%Y-%m-%d %H:%M')
        return value

    def should_keep_metric(t1d, t1w, ytd) -> bool:
        values = [t1d, t1w, ytd]
        return any(value not in [None, 0, '0'] for value in values)

    def append_metric(metric_name: str, t1d, t1w, ytd):
        if should_keep_metric(t1d, t1w, ytd):
            rows.append({
                'metric': metric_name,
                't1d': safe_value(t1d),
                't1w': safe_value(t1w),
                'ytd': safe_value(ytd)
            })

    if raw_df.is_empty():
        return pl.DataFrame({
            'metric': [],
            't1d': [],
            't1w': [],
            'ytd': []
        })

    df = raw_df.with_columns([
        pl.col('tx_date_mx').cast(pl.Datetime, strict=False).alias('tx_date_mx_parsed'),
        pl.col('tx_date_mx_date').cast(pl.Date, strict=False).alias('tx_date_mx_date_parsed'),
        pl.col('cod_respuesta').cast(pl.Int64, strict=False).alias('cod_respuesta_int'),
        pl.col('user_id').cast(pl.Utf8, strict=False).alias('user_id_cast'),
        pl.col('state').cast(pl.Utf8, strict=False).alias('state_cast'),
        pl.col('card_type').cast(pl.Utf8, strict=False).alias('card_type_cast'),
        pl.col('product_type').cast(pl.Utf8, strict=False).alias('product_type_cast'),
        pl.col('cvv').cast(pl.Utf8, strict=False).alias('cvv_cast'),
        pl.col('eci').cast(pl.Utf8, strict=False).alias('eci_cast')
    ]).with_columns([
        (pl.col('tx_date_mx_date_parsed') == pl.lit(block_date_mx)).alias('flg_t1d'),
        (
            (pl.col('tx_date_mx_date_parsed') >= pl.lit(week_start_mx)) &
            (pl.col('tx_date_mx_date_parsed') <= pl.lit(block_date_mx))
        ).alias('flg_t1w'),
        (
            (pl.col('tx_date_mx_date_parsed') >= pl.lit(year_start_mx)) &
            (pl.col('tx_date_mx_date_parsed') <= pl.lit(block_date_mx))
        ).alias('flg_ytd'),
        (
            (pl.col('cvv_cast') == 'no cvv') &
            (~pl.col('eci_cast').fill_null('').is_in(['5', '6']))
        ).alias('flg_no_3ds_no_cvv'),
        (
            (pl.col('cvv_cast') == 'has cvv') |
            (pl.col('eci_cast').fill_null('').is_in(['5', '6']))
        ).alias('flg_has_cvv_or_3ds')
    ])

    def count_for(mask_expr, period_expr):
        return df.filter(mask_expr & period_expr).height

    def first_for(period_expr):
        return df.filter(period_expr).select(pl.col('tx_date_mx_parsed').min()).item()

    def last_for(period_expr):
        return df.filter(period_expr).select(pl.col('tx_date_mx_parsed').max()).item()

    def distinct_users_for(period_expr):
        value = (
            df.filter(period_expr & pl.col('user_id_cast').is_not_null())
                .select(pl.col('user_id_cast').n_unique())
                .item()
        )
        return 0 if value is None else int(value)

    append_metric(
        'first_tx_date',
        first_for(pl.col('flg_t1d')),
        first_for(pl.col('flg_t1w')),
        first_for(pl.col('flg_ytd'))
    )
    append_metric(
        'last_tx_date',
        last_for(pl.col('flg_t1d')),
        last_for(pl.col('flg_t1w')),
        last_for(pl.col('flg_ytd'))
    )

    for code in target_response_codes:
        code_mask = pl.col('cod_respuesta_int') == code
        append_metric(
            f'cnt_cr_{code}',
            count_for(code_mask, pl.col('flg_t1d')),
            count_for(code_mask, pl.col('flg_t1w')),
            count_for(code_mask, pl.col('flg_ytd'))
        )
        append_metric(
            f'cnt_cr_{code}_no_3ds_no_cvv',
            count_for(code_mask & pl.col('flg_no_3ds_no_cvv'), pl.col('flg_t1d')),
            count_for(code_mask & pl.col('flg_no_3ds_no_cvv'), pl.col('flg_t1w')),
            count_for(code_mask & pl.col('flg_no_3ds_no_cvv'), pl.col('flg_ytd'))
        )
        append_metric(
            f'cnt_cr_{code}_has_cvv_or_has_3ds',
            count_for(code_mask & pl.col('flg_has_cvv_or_3ds'), pl.col('flg_t1d')),
            count_for(code_mask & pl.col('flg_has_cvv_or_3ds'), pl.col('flg_t1w')),
            count_for(code_mask & pl.col('flg_has_cvv_or_3ds'), pl.col('flg_ytd'))
        )

    append_metric(
        'cnt_unique_users',
        distinct_users_for(pl.col('flg_t1d')),
        distinct_users_for(pl.col('flg_t1w')),
        distinct_users_for(pl.col('flg_ytd'))
    )
    append_metric(
        'cnt_state_failed_canceled',
        count_for(pl.col('state_cast').is_in(['FAILED', 'CANCELED']), pl.col('flg_t1d')),
        count_for(pl.col('state_cast').is_in(['FAILED', 'CANCELED']), pl.col('flg_t1w')),
        count_for(pl.col('state_cast').is_in(['FAILED', 'CANCELED']), pl.col('flg_ytd'))
    )
    append_metric(
        'cnt_authorized_settled',
        count_for(pl.col('state_cast').is_in(['AUTHORIZED', 'SETTLED']), pl.col('flg_t1d')),
        count_for(pl.col('state_cast').is_in(['AUTHORIZED', 'SETTLED']), pl.col('flg_t1w')),
        count_for(pl.col('state_cast').is_in(['AUTHORIZED', 'SETTLED']), pl.col('flg_ytd'))
    )

    card_types = (
        df.filter(
            pl.col('card_type_cast').is_not_null() &
            (pl.col('card_type_cast').map_elements(lambda x: x.strip() if x is not None else '', return_dtype=pl.Utf8) != '')
        )
        .select('card_type_cast')
        .unique()
        .sort('card_type_cast')
        .to_series()
        .to_list()
    )

    for card_type in card_types:
        card_mask = (
            (pl.col('card_type_cast') == card_type) &
            pl.col('flg_no_3ds_no_cvv')
        )
        append_metric(
            f'cnt_card_type_{card_type}_no_3ds_no_cvv',
            count_for(card_mask, pl.col('flg_t1d')),
            count_for(card_mask, pl.col('flg_t1w')),
            count_for(card_mask, pl.col('flg_ytd'))
        )

    product_types = (
        df.filter(
            pl.col('product_type_cast').is_not_null() &
            (pl.col('product_type_cast').map_elements(lambda x: x.strip() if x is not None else '', return_dtype=pl.Utf8) != '')
        )
        .select('product_type_cast')
        .unique()
        .sort('product_type_cast')
        .to_series()
        .to_list()
    )

    for product_type in product_types:
        product_mask = (
            (pl.col('product_type_cast') == product_type) &
            pl.col('flg_no_3ds_no_cvv')
        )
        append_metric(
            f'cnt_product_type_{product_type}_no_3ds_no_cvv',
            count_for(product_mask, pl.col('flg_t1d')),
            count_for(product_mask, pl.col('flg_t1w')),
            count_for(product_mask, pl.col('flg_ytd'))
        )

    return pl.DataFrame(rows) if rows else pl.DataFrame({
        'metric': [],
        't1d': [],
        't1w': [],
        'ytd': []
    })

In [14]:
def merchant_trx_summary(merchant:str, blocked_date:str) -> pl.DataFrame:
    merchant_activity_query = build_merchant_activity_query(merchant, blocked_date)
    merchant_activity_raw = pl.read_database(
        query=merchant_activity_query,
        connection=get_db_conn()
    )
    return build_merchant_activity_summary(merchant_activity_raw, blocked_date)

In [15]:
# def find_chargeback(merchant_to_block: str) -> pd.DataFrame:
#     # run query here
#     cb_query = f"""
#         WITH tc_base AS (
#             SELECT
#                 tc.*,
#                 COALESCE(
#                     NULLIF(split_part(tc.transaction_id, 'PARABILIUM:', 2), ''),
#                     tc.transaction_id
#                 ) AS omi_id_operacion_raw
#             FROM ops_fraud.total_chargeback tc
#             --where
#             --    tc.merchant ilike '%' || '{merchant_to_block}' || '%'
#         ),

#         oimt_base AS (
#             SELECT
#                 oimt.omi_id_operacion,
#                 oimt.c063,
#                 oimt.c032 as adquirente
#             FROM is_pii_parabilium.operation_iso_messages_temp oimt
#             INNER JOIN tc_base tc
#                 ON oimt.omi_id_operacion = tc.omi_id_operacion_raw
#         ),

#         pin_verif AS (
#             SELECT
#                 o.omi_id_operacion,
#                 /* ---------- CVM RESULTS (Byte 1) ---------- */
#                 '! ' || REGEXP_SUBSTR(o.c063, 'B300080[^!]*') AS B300080_value,
#                 SUBSTRING(B300080_value FROM 49 FOR 6) AS "8-CVMRSLTS",
#                 SUBSTRING("8-CVMRSLTS" FROM 1 FOR 2) AS byte_1_hex,
#                 CASE
#                     WHEN byte_1_hex ~ '^[0-9A-Fa-f]{2}$'
#                     THEN FROM_VARBYTE(from_hex(byte_1_hex), 'binary')
#                     ELSE NULL
#                 END AS byte_1_bits,
#                 CASE
#                     WHEN byte_1_bits IS NULL THEN NULL
#                     WHEN SUBSTRING(byte_1_bits FROM 3 FOR 6) = '000000'
#                         THEN 'Procesamiento de CVM fallido'
#                     WHEN SUBSTRING(byte_1_bits FROM 3 FOR 6) = '000001'
#                         THEN 'Verificacion de PIN en texto plano realizada por el chip de la tarjeta'
#                     WHEN SUBSTRING(byte_1_bits FROM 3 FOR 6) = '000010'
#                         THEN 'PIN cifrado verificado en linea'
#                     WHEN SUBSTRING(byte_1_bits FROM 3 FOR 6) = '000011'
#                         THEN 'Verificacion de PIN en texto plano realizada por el chip de la tarjeta y firma (papel)'
#                     WHEN SUBSTRING(byte_1_bits FROM 3 FOR 6) = '000100'
#                         THEN 'Verificacion de PIN cifrado realizada por el chip de la tarjeta'
#                     WHEN SUBSTRING(byte_1_bits FROM 3 FOR 6) = '000101'
#                         THEN 'Verificacion de PIN cifrado realizada por el chip de la tarjeta y firma (papel)'
#                     WHEN SUBSTRING(byte_1_bits FROM 3 FOR 6) = '011110'
#                         THEN 'Firma (papel)'
#                     WHEN SUBSTRING(byte_1_bits FROM 3 FOR 6) = '011111'
#                         THEN 'No se requiere CVM'
#                     ELSE SUBSTRING(byte_1_bits FROM 3 FOR 6)
#                 END AS metodo_verificacion
#             FROM oimt_base o
#             WHERE o.c063 LIKE '%! B3%'
#         ),

#         three_ds AS (
#             SELECT
#                 o.omi_id_operacion,
#                 o.c063,

#                 /* ---------- CE TOKEN EXTRACTION ---------- */
#                 REGEXP_SUBSTR(o.c063, 'CE[0-9]{5}[^!]*') AS ce_token,

#                 /* ---------- LEADING INDICATOR (kA, kG, kN, etc.) ---------- */
#                 CASE
#                     WHEN REGEXP_SUBSTR(o.c063, 'CE[0-9]{5}[^!]*') IS NOT NULL
#                         AND position('01' IN REGEXP_SUBSTR(o.c063, 'CE[0-9]{5}[^!]*')) > 0
#                     THEN substring(
#                         REGEXP_SUBSTR(o.c063, 'CE[0-9]{5}[^!]*')
#                         FROM position('01' IN REGEXP_SUBSTR(o.c063, 'CE[0-9]{5}[^!]*')) + 2
#                         FOR 2
#                     )
#                     ELSE NULL
#                 END AS leading_indicator,

#                 /* ---------- 3DS STATUS ---------- */
#                 CASE
#                     WHEN REGEXP_SUBSTR(o.c063, 'CE[0-9]{5}[^!]*') IS NULL
#                         THEN 'NO_3DS'
#                     WHEN substring(
#                             REGEXP_SUBSTR(o.c063, 'CE[0-9]{5}[^!]*')
#                             FROM position('01' IN REGEXP_SUBSTR(o.c063, 'CE[0-9]{5}[^!]*')) + 2
#                             FOR 2
#                         ) IN ('kA','kB','kC','kE','kF','kJ','kR','kS','kG','kO','kP')
#                         THEN '3DS_AUTHENTICATED'
#                     WHEN substring(
#                             REGEXP_SUBSTR(o.c063, 'CE[0-9]{5}[^!]*')
#                             FROM position('01' IN REGEXP_SUBSTR(o.c063, 'CE[0-9]{5}[^!]*')) + 2
#                             FOR 2
#                         ) IN ('kN','kW','kU','kX')
#                         THEN '3DS_NOT_AUTHENTICATED'
#                     ELSE 'UNKNOWN'
#                 END AS three_ds_status,

#                 /* ---------- 3DS FLOW ---------- */
#                 CASE
#                     WHEN REGEXP_SUBSTR(o.c063, 'CE[0-9]{5}[^!]*') IS NULL
#                         THEN 'NO_3DS'
#                     WHEN substring(
#                             REGEXP_SUBSTR(o.c063, 'CE[0-9]{5}[^!]*')
#                             FROM position('01' IN REGEXP_SUBSTR(o.c063, 'CE[0-9]{5}[^!]*')) + 2
#                             FOR 2
#                         ) IN ('kA','kC','kE','kO')
#                         THEN 'FRICTIONLESS'
#                     WHEN substring(
#                             REGEXP_SUBSTR(o.c063, 'CE[0-9]{5}[^!]*')
#                             FROM position('01' IN REGEXP_SUBSTR(o.c063, 'CE[0-9]{5}[^!]*')) + 2
#                             FOR 2
#                         ) IN ('kB','kS','kG','kP')
#                         THEN 'CHALLENGE'
#                     WHEN substring(
#                             REGEXP_SUBSTR(o.c063, 'CE[0-9]{5}[^!]*')
#                             FROM position('01' IN REGEXP_SUBSTR(o.c063, 'CE[0-9]{5}[^!]*')) + 2
#                             FOR 2
#                         ) IN ('kN','kW','kU','kX')
#                         THEN 'EXEMPT_OR_INFO'
#                     ELSE 'UNKNOWN'
#                 END AS three_ds_flow
#             FROM oimt_base o
#         )

#         SELECT
#             tc.*,
#             pv.metodo_verificacion AS metodo_identificacion,
#             td.leading_indicator,
#             td.three_ds_status,
#             td.three_ds_flow,
#             td.c063,
#             o.sucursal as afiliacion,
#             o.terminal as numero_terminal,
#             ob.adquirente
#         FROM tc_base tc
#         LEFT JOIN pin_verif pv
#             ON pv.omi_id_operacion = tc.omi_id_operacion_raw
#         LEFT JOIN three_ds td
#             ON td.omi_id_operacion = tc.omi_id_operacion_raw
#         left join
#             is_pii_parabilium.parabilium_transactions pt on pt.id = tc.omi_id_operacion_raw
#         left join
#             is_pii_parabilium.operaciones o on o.id_operacion = tc.omi_id_operacion_raw
#         LEFT JOIN oimt_base ob
#             ON ob.omi_id_operacion = tc.omi_id_operacion_raw
#         """

#     cb_df = pd.read_sql(cb_query, get_db_conn())
#     cb_df = cb_df[cb_df["merchant"] == merchant_to_block]
#     if cb_df.empty:
#         return cb_df
#     else:
#         cb_df["trx_time"] = cb_df['trx_timestamp_mx']
#         cb_df['trx_timestamp_mx'] = pd.to_datetime(cb_df['trx_timestamp_mx'])
#         cb_df['week_number'] = cb_df['trx_timestamp_mx'].dt.isocalendar().week
#         cb_df['trx_date'] = cb_df["trx_timestamp_mx"].dt.date
#         cb_df['trx_month'] = cb_df['trx_timestamp_mx'].dt.month
#         cb_df['trx_day'] = cb_df["trx_timestamp_mx"].dt.day
#         cb_df['trx_month_year'] = cb_df['trx_timestamp_mx'].dt.to_period('M')
#         cb_df['trx_week_year'] = cb_df['trx_timestamp_mx'].dt.strftime('%Y-%W')
#         # cb timestamp
#         cb_df['cb_date'] = cb_df["cb_timestamp"].dt.date
#         cb_df['cb_month'] = cb_df['cb_timestamp'].dt.month
#         cb_df['cb_day'] = cb_df["cb_timestamp"].dt.day
#         cb_df['cb_month_year'] = cb_df['cb_timestamp'].dt.to_period('M')
#         cb_df['cb_week_year'] = cb_df['cb_timestamp'].dt.strftime('%Y-%W')
#         cb_df.drop_duplicates(subset=["transaction_id"], inplace=True, keep='first')
#         cb_df = cb_df[(cb_df["transaction_id"].notna()) &(cb_df["amount"].notna())]
#         # mapear cb_reasons to the correct ones
#         cb_df = cb_df[cb_df["cb_reason"] != 'Devolución de dinero']
#         cb_df["cb_reason_original"] = cb_df["cb_reason"]
#         cb_df["cb_reason"] = cb_df["cb_reason"].map({
#             'Transacción por internet o compra telefónica': "Rembolso no recibido",
#             'Error durante el proceso': "Cargo no reconocido",
#             'Otro' : "Otro",
#             'Producto no recibido': "Rembolso no recibido",
#             'Transacción duplicada': 'Transacción duplicada',
#             'Transacción declinada': 'Transacción declinada',
#             'Transacción excede el importe autorizado': 'Rembolso no procesado',
#             'Aclaración de Transacción de Cajero Automático': 'Aclaración de Transacción de Cajero Automático',
#             'ATM no entrega dinero': 'Aclaración de Transacción de Cajero Automático',
#             'Reporte de cargo no reconocido':  "Cargo no reconocido",
#             'TRANSACTION_EXCEEDS_AUTHORIZED_AMOUNT':  'Rembolso no procesado',
#             'Reembolso no procesado': 'Rembolso no procesado',
#             'REFUND_NOT_PROCESSED': 'Rembolso no procesado',
#             'TRANSACTION_DECLINED': 'Transacción declinada',
#             'OTHER': 'Otro',
#             'UNRECOGNIZED_TRANSACTION': 'Cargo no reconocido',
#             'INTERNET_PHONE_TRANSACTION': 'Rembolso no recibido',
#             'UNRECOGNIZED_CHARGE': "Cargo no reconocido",
#             'DUPLICATE_TRANSACTION': 'Transacción duplicada',
#             'ATM_TRANSACTION_CLARIFICATION': 'Aclaración de Transacción de Cajero Automático',
#         })
#         # obtain last two characters of merchant
#         cb_df["country"] = cb_df.merchant.str[-2:]
#         return cb_df

In [16]:
# def chargeback_merchant_summary(merchant_name: str) -> Dict[str, Dict]:
#     def _series_to_dict(series: pd.Series) -> Dict:
#         return {str(idx): int(value) for idx, value in series.fillna("null").items()}

#     def _dataframe_to_records(df: pd.DataFrame) -> List[Dict]:
#         if df.empty:
#             return []

#         serializable_df = df.copy()
#         for column in serializable_df.columns:
#             if pd.api.types.is_datetime64_any_dtype(serializable_df[column]):
#                 serializable_df[column] = serializable_df[column].astype(str)

#         return serializable_df.to_dict(orient="records")

#     report = {}
#     timeframes = {
#         "1_week": (dt.datetime.now() - dt.timedelta(days=7)).strftime('%Y-%m-%d %H:%M:%S'),
#         "1_month": (dt.datetime.now() - dt.timedelta(days=30)).strftime('%Y-%m-%d %H:%M:%S'),
#         "ytd": dt.datetime(dt.datetime.now().year, 1, 1).strftime('%Y-%m-%d %H:%M:%S'),
#     }
#     merchant_name = merchant_name.replace('*', '')
#     merchant_cb_df = find_chargeback(merchant_name)

#     if merchant_cb_df.empty:
#         report[merchant_name] = {
#             "merchant_name": merchant_name,
#             "first_appearance": None,
#             "last_appearance": None,
#             "shared_commerces_summary": [],
#             "shared_commerces_transactions": [],
#             "timeframes": {},
#         }
#         return report
#     else:
#         klrids_merchant = merchant_cb_df["klrid"].unique().tolist()
#         # top_commerces, revise_users_df = common_commerces_from_cb(
#         #     klrids=klrids_merchant,
#         #     merchant_name=merchant_name,
#         # )

#         merchant_summary = {
#             "merchant_name": merchant_name,
#             "first_appearance": str(merchant_cb_df["trx_timestamp_mx"].min()),
#             "last_appearance": str(merchant_cb_df["trx_timestamp_mx"].max()),
#             # "shared_commerces_summary": _dataframe_to_records(top_commerces),
#             # "shared_commerces_transactions": _dataframe_to_records(revise_users_df),
#             "timeframes": {},
#         }

#         for timeframe_name, start_time in timeframes.items():
#             timeframe_df = merchant_cb_df[merchant_cb_df["trx_timestamp_mx"] >= start_time]
#             merchant_summary["timeframes"][timeframe_name] = {
#                 "start_time": start_time,
#                 "num_chargebacks_reported": int(timeframe_df["transaction_id"].nunique()),
#                 "num_unique_users": int(timeframe_df["user_id"].nunique()),
#                 "num_klrids_per_card_type": _series_to_dict(timeframe_df.groupby("card_type")["klrid"].nunique()),
#                 "num_klrids_per_product_type": _series_to_dict(timeframe_df.groupby("product_type")["klrid"].nunique()),
#                 "num_transactions_per_cvv_indicator": _series_to_dict(timeframe_df.groupby("cvv_ind")["transaction_id"].nunique()),
#                 "num_transactions_per_3ds_status": _series_to_dict(timeframe_df.groupby("three_ds_status")["transaction_id"].nunique()),
#             }

#         report[merchant_name] = merchant_summary

#     return report

In [17]:
def _series_to_dict(series: pd.Series) -> Dict[str, int]:
    return {str(idx): int(value) for idx, value in series.fillna("null").items()}


def _normalize_blocking_timestamp(
    blocking_date: str | dt.date | dt.datetime | pd.Timestamp,
) -> pd.Timestamp:
    blocking_ts = pd.Timestamp(blocking_date)

    if isinstance(blocking_date, dt.date) and not isinstance(blocking_date, dt.datetime):
        return blocking_ts.normalize() + pd.Timedelta(days=1) - pd.Timedelta(microseconds=1)

    blocking_text = str(blocking_date).strip()
    if len(blocking_text) <= 10:
        return blocking_ts.normalize() + pd.Timedelta(days=1) - pd.Timedelta(microseconds=1)

    return blocking_ts


def _normalize_blocking_day(
    blocking_date: str | dt.date | dt.datetime | pd.Timestamp,
) -> dt.date:
    return pd.Timestamp(blocking_date).date()


def _build_timeframes(
    blocking_date: str | dt.date | dt.datetime | pd.Timestamp,
) -> Dict[str, Dict[str, pd.Timestamp]]:
    blocking_ts = _normalize_blocking_timestamp(blocking_date)

    return {
        "1_week": {
            "start_time": blocking_ts - pd.Timedelta(days=7),
            "end_time": blocking_ts,
        },
        "1_month": {
            "start_time": blocking_ts - pd.Timedelta(days=30),
            "end_time": blocking_ts,
        },
        "ytd": {
            "start_time": pd.Timestamp(dt.datetime(blocking_ts.year, 1, 1)),
            "end_time": blocking_ts,
        },
    }


def find_chargeback(
    merchant_to_block: str,
    blocking_date: str | dt.date | dt.datetime | pd.Timestamp,
) -> pd.DataFrame:
    merchant_name = merchant_to_block.replace("*", "")
    blocking_day_sql = _normalize_blocking_day(blocking_date).isoformat()

    cb_query = f"""
        WITH tc_base AS (
            SELECT
                tc.*,
                COALESCE(
                    NULLIF(split_part(tc.transaction_id, 'PARABILIUM:', 2), ''),
                    tc.transaction_id
                ) AS omi_id_operacion_raw
            FROM ops_fraud.total_chargeback tc
            WHERE
                tc.merchant = '{merchant_name}'
                AND tc.trx_timestamp_mx < DATEADD(day, 1, DATE '{blocking_day_sql}')
        ),

        oimt_base AS (
            SELECT
                oimt.omi_id_operacion,
                oimt.c063,
                oimt.c032 AS adquirente
            FROM is_pii_parabilium.operation_iso_messages_temp oimt
            INNER JOIN tc_base tc
                ON oimt.omi_id_operacion = tc.omi_id_operacion_raw
        ),

        pin_verif AS (
            SELECT
                o.omi_id_operacion,
                '! ' || REGEXP_SUBSTR(o.c063, 'B300080[^!]*') AS B300080_value,
                SUBSTRING(B300080_value FROM 49 FOR 6) AS "8-CVMRSLTS",
                SUBSTRING("8-CVMRSLTS" FROM 1 FOR 2) AS byte_1_hex,
                CASE
                    WHEN byte_1_hex ~ '^[0-9A-Fa-f]{2}$'
                    THEN FROM_VARBYTE(from_hex(byte_1_hex), 'binary')
                    ELSE NULL
                END AS byte_1_bits,
                CASE
                    WHEN byte_1_bits IS NULL THEN NULL
                    WHEN SUBSTRING(byte_1_bits FROM 3 FOR 6) = '000000'
                        THEN 'Procesamiento de CVM fallido'
                    WHEN SUBSTRING(byte_1_bits FROM 3 FOR 6) = '000001'
                        THEN 'Verificacion de PIN en texto plano realizada por el chip de la tarjeta'
                    WHEN SUBSTRING(byte_1_bits FROM 3 FOR 6) = '000010'
                        THEN 'PIN cifrado verificado en linea'
                    WHEN SUBSTRING(byte_1_bits FROM 3 FOR 6) = '000011'
                        THEN 'Verificacion de PIN en texto plano realizada por el chip de la tarjeta y firma (papel)'
                    WHEN SUBSTRING(byte_1_bits FROM 3 FOR 6) = '000100'
                        THEN 'Verificacion de PIN cifrado realizada por el chip de la tarjeta'
                    WHEN SUBSTRING(byte_1_bits FROM 3 FOR 6) = '000101'
                        THEN 'Verificacion de PIN cifrado realizada por el chip de la tarjeta y firma (papel)'
                    WHEN SUBSTRING(byte_1_bits FROM 3 FOR 6) = '011110'
                        THEN 'Firma (papel)'
                    WHEN SUBSTRING(byte_1_bits FROM 3 FOR 6) = '011111'
                        THEN 'No se requiere CVM'
                    ELSE SUBSTRING(byte_1_bits FROM 3 FOR 6)
                END AS metodo_verificacion
            FROM oimt_base o
            WHERE o.c063 LIKE '%! B3%'
        ),

        three_ds AS (
            SELECT
                o.omi_id_operacion,
                o.c063,
                REGEXP_SUBSTR(o.c063, 'CE[0-9]{5}[^!]*') AS ce_token,
                CASE
                    WHEN REGEXP_SUBSTR(o.c063, 'CE[0-9]{5}[^!]*') IS NOT NULL
                        AND POSITION('01' IN REGEXP_SUBSTR(o.c063, 'CE[0-9]{5}[^!]*')) > 0
                    THEN SUBSTRING(
                        REGEXP_SUBSTR(o.c063, 'CE[0-9]{5}[^!]*')
                        FROM POSITION('01' IN REGEXP_SUBSTR(o.c063, 'CE[0-9]{5}[^!]*')) + 2
                        FOR 2
                    )
                    ELSE NULL
                END AS leading_indicator,
                CASE
                    WHEN REGEXP_SUBSTR(o.c063, 'CE[0-9]{5}[^!]*') IS NULL
                        THEN 'NO_3DS'
                    WHEN SUBSTRING(
                            REGEXP_SUBSTR(o.c063, 'CE[0-9]{5}[^!]*')
                            FROM POSITION('01' IN REGEXP_SUBSTR(o.c063, 'CE[0-9]{5}[^!]*')) + 2
                            FOR 2
                        ) IN ('kA','kB','kC','kE','kF','kJ','kR','kS','kG','kO','kP')
                        THEN '3DS_AUTHENTICATED'
                    WHEN SUBSTRING(
                            REGEXP_SUBSTR(o.c063, 'CE[0-9]{5}[^!]*')
                            FROM POSITION('01' IN REGEXP_SUBSTR(o.c063, 'CE[0-9]{5}[^!]*')) + 2
                            FOR 2
                        ) IN ('kN','kW','kU','kX')
                        THEN '3DS_NOT_AUTHENTICATED'
                    ELSE 'UNKNOWN'
                END AS three_ds_status,
                CASE
                    WHEN REGEXP_SUBSTR(o.c063, 'CE[0-9]{5}[^!]*') IS NULL
                        THEN 'NO_3DS'
                    WHEN SUBSTRING(
                            REGEXP_SUBSTR(o.c063, 'CE[0-9]{5}[^!]*')
                            FROM POSITION('01' IN REGEXP_SUBSTR(o.c063, 'CE[0-9]{5}[^!]*')) + 2
                            FOR 2
                        ) IN ('kA','kC','kE','kO')
                        THEN 'FRICTIONLESS'
                    WHEN SUBSTRING(
                            REGEXP_SUBSTR(o.c063, 'CE[0-9]{5}[^!]*')
                            FROM POSITION('01' IN REGEXP_SUBSTR(o.c063, 'CE[0-9]{5}[^!]*')) + 2
                            FOR 2
                        ) IN ('kB','kS','kG','kP')
                        THEN 'CHALLENGE'
                    WHEN SUBSTRING(
                            REGEXP_SUBSTR(o.c063, 'CE[0-9]{5}[^!]*')
                            FROM POSITION('01' IN REGEXP_SUBSTR(o.c063, 'CE[0-9]{5}[^!]*')) + 2
                            FOR 2
                        ) IN ('kN','kW','kU','kX')
                        THEN 'EXEMPT_OR_INFO'
                    ELSE 'UNKNOWN'
                END AS three_ds_flow
            FROM oimt_base o
        )

        SELECT
            tc.*,
            pv.metodo_verificacion AS metodo_identificacion,
            td.leading_indicator,
            td.three_ds_status,
            td.three_ds_flow,
            td.c063,
            o.sucursal AS afiliacion,
            o.terminal AS numero_terminal,
            ob.adquirente
        FROM tc_base tc
        LEFT JOIN pin_verif pv
            ON pv.omi_id_operacion = tc.omi_id_operacion_raw
        LEFT JOIN three_ds td
            ON td.omi_id_operacion = tc.omi_id_operacion_raw
        LEFT JOIN is_pii_parabilium.parabilium_transactions pt
            ON pt.id = tc.omi_id_operacion_raw
        LEFT JOIN is_pii_parabilium.operaciones o
            ON o.id_operacion = tc.omi_id_operacion_raw
        LEFT JOIN oimt_base ob
            ON ob.omi_id_operacion = tc.omi_id_operacion_raw
    """

    cb_df = pd.read_sql(cb_query, get_db_conn())
    if cb_df.empty:
        return cb_df

    cb_df["trx_time"] = cb_df["trx_timestamp_mx"]
    cb_df["trx_timestamp_mx"] = pd.to_datetime(cb_df["trx_timestamp_mx"])
    cb_df["cb_timestamp"] = pd.to_datetime(cb_df["cb_timestamp"])
    cb_df["week_number"] = cb_df["trx_timestamp_mx"].dt.isocalendar().week
    cb_df["trx_date"] = cb_df["trx_timestamp_mx"].dt.date
    cb_df["trx_month"] = cb_df["trx_timestamp_mx"].dt.month
    cb_df["trx_day"] = cb_df["trx_timestamp_mx"].dt.day
    cb_df["trx_month_year"] = cb_df["trx_timestamp_mx"].dt.to_period("M")
    cb_df["trx_week_year"] = cb_df["trx_timestamp_mx"].dt.strftime("%Y-%W")
    cb_df["cb_date"] = cb_df["cb_timestamp"].dt.date
    cb_df["cb_month"] = cb_df["cb_timestamp"].dt.month
    cb_df["cb_day"] = cb_df["cb_timestamp"].dt.day
    cb_df["cb_month_year"] = cb_df["cb_timestamp"].dt.to_period("M")
    cb_df["cb_week_year"] = cb_df["cb_timestamp"].dt.strftime("%Y-%W")
    cb_df.drop_duplicates(subset=["transaction_id"], inplace=True, keep="first")
    cb_df = cb_df[(cb_df["transaction_id"].notna()) & (cb_df["amount"].notna())]
    cb_df = cb_df[cb_df["cb_reason"] != "Devolución de dinero"]
    cb_df["cb_reason_original"] = cb_df["cb_reason"]
    cb_df["cb_reason"] = cb_df["cb_reason"].map(
        {
            "Transacción por internet o compra telefónica": "Rembolso no recibido",
            "Error durante el proceso": "Cargo no reconocido",
            "Otro": "Otro",
            "Producto no recibido": "Rembolso no recibido",
            "Transacción duplicada": "Transacción duplicada",
            "Transacción declinada": "Transacción declinada",
            "Transacción excede el importe autorizado": "Rembolso no procesado",
            "Aclaración de Transacción de Cajero Automático": "Aclaración de Transacción de Cajero Automático",
            "ATM no entrega dinero": "Aclaración de Transacción de Cajero Automático",
            "Reporte de cargo no reconocido": "Cargo no reconocido",
            "TRANSACTION_EXCEEDS_AUTHORIZED_AMOUNT": "Rembolso no procesado",
            "Reembolso no procesado": "Rembolso no procesado",
            "REFUND_NOT_PROCESSED": "Rembolso no procesado",
            "TRANSACTION_DECLINED": "Transacción declinada",
            "OTHER": "Otro",
            "UNRECOGNIZED_TRANSACTION": "Cargo no reconocido",
            "INTERNET_PHONE_TRANSACTION": "Rembolso no recibido",
            "UNRECOGNIZED_CHARGE": "Cargo no reconocido",
            "DUPLICATE_TRANSACTION": "Transacción duplicada",
            "ATM_TRANSACTION_CLARIFICATION": "Aclaración de Transacción de Cajero Automático",
        }
    )
    cb_df["country"] = cb_df["merchant"].str[-2:]
    return cb_df


def chargeback_merchant_summary(
    merchant_name: str,
    blocking_date: str | dt.date | dt.datetime | pd.Timestamp,
) -> Dict[str, Dict]:
    report: Dict[str, Dict] = {}
    merchant_name = merchant_name.replace("*", "")
    blocking_ts = _normalize_blocking_timestamp(blocking_date)
    timeframes = _build_timeframes(blocking_date)
    merchant_cb_df = find_chargeback(merchant_name, blocking_date)

    if merchant_cb_df.empty:
        report[merchant_name] = {
            "merchant_name": merchant_name,
            "blocking_date": str(blocking_ts),
            "first_appearance": None,
            "last_appearance": None,
            "shared_commerces_summary": [],
            "shared_commerces_transactions": [],
            "timeframes": {},
        }
        return report

    merchant_summary = {
        "merchant_name": merchant_name,
        "blocking_date": str(blocking_ts),
        "first_appearance": str(merchant_cb_df["trx_timestamp_mx"].min()),
        "last_appearance": str(merchant_cb_df["trx_timestamp_mx"].max()),
        "timeframes": {},
    }

    for timeframe_name, bounds in timeframes.items():
        start_time = bounds["start_time"]
        end_time = bounds["end_time"]
        timeframe_df = merchant_cb_df[
            (merchant_cb_df["trx_timestamp_mx"] >= start_time)
            & (merchant_cb_df["trx_timestamp_mx"] <= end_time)
        ].copy()

        merchant_summary["timeframes"][timeframe_name] = {
            "start_time": str(start_time),
            "end_time": str(end_time),
            "num_chargebacks_reported": int(timeframe_df["transaction_id"].nunique()),
            "num_unique_users": int(timeframe_df["user_id"].nunique()),
            "num_klrids_per_card_type": _series_to_dict(
                timeframe_df.groupby("card_type")["klrid"].nunique()
            ),
            "num_klrids_per_product_type": _series_to_dict(
                timeframe_df.groupby("product_type")["klrid"].nunique()
            ),
            "num_transactions_per_cvv_indicator": _series_to_dict(
                timeframe_df.groupby("cvv_ind")["transaction_id"].nunique()
            ),
            "num_transactions_per_3ds_status": _series_to_dict(
                timeframe_df.groupby("three_ds_status")["transaction_id"].nunique()
            ),
        }

    report[merchant_name] = merchant_summary
    return report

In [18]:
def build_cod_risk_summary(merchant_to_block: str, block_date: str) -> str:

    ''' 
    INCLUDE OPERADOR NOT MERCHANT NAME 
    '''
    response_code_query = f"""
        WITH daily_codes AS (
        SELECT
            date_trunc('day', fecharegistro) AS day,
            operador,
            cod_respuesta,
            count(*) AS transaction_count,
            sum(importe) AS total_importe
        FROM is_pii_parabilium.operations_temp ot
        WHERE operador ILIKE '%' || '{merchant_to_block}' || '%'
            AND fecharegistro >= DATE '2025-01-05'
            and fecharegistro <= DATE '{block_date}'
        GROUP BY 1, 2, 3
        ),
        daily_totals AS (
        SELECT
            day,
            operador,
            sum(transaction_count) AS total_txn_day,
            sum(total_importe) AS total_importe_day
        FROM daily_codes
        GROUP BY 1, 2
        ),
        risky_codes AS (
        SELECT
            dc.day,
            dc.operador,
            dc.cod_respuesta,
            dc.transaction_count,
            dc.total_importe,
            dt.total_txn_day,
            ROUND(100.0 * dc.transaction_count / NULLIF(dt.total_txn_day, 0), 2) AS pct_of_day_txns,
            LAG(dc.transaction_count) OVER (
                PARTITION BY dc.operador, dc.cod_respuesta
                ORDER BY dc.day
            ) AS prev_txn_count,
            LAG(dc.total_importe) OVER (
                PARTITION BY dc.operador, dc.cod_respuesta
                ORDER BY dc.day
            ) AS prev_importe
        FROM daily_codes dc
        JOIN daily_totals dt
            ON dc.day = dt.day
        AND dc.operador = dt.operador
        WHERE dc.cod_respuesta IN ('87', '14')
        )
        SELECT
            day,
            operador,
            cod_respuesta,
            transaction_count,
            total_importe,
            total_txn_day,
            pct_of_day_txns,
            prev_txn_count,
            CASE
            WHEN prev_txn_count IS NULL OR prev_txn_count = 0 THEN NULL
            ELSE ROUND(100.0 * (transaction_count - prev_txn_count) / prev_txn_count, 2)
            END AS pct_change_vs_prev_day,
            CASE
            WHEN prev_txn_count IS NULL THEN 'no prior data'
            WHEN transaction_count > prev_txn_count THEN 'increasing'
            WHEN transaction_count < prev_txn_count THEN 'decreasing'
            ELSE 'flat'
            END AS trend_direction
        FROM risky_codes
        ORDER BY day DESC, operador, cod_respuesta;
    """
    df = pd.read_sql_query(response_code_query, con=get_db_conn())
    
    # Ensure sorting (latest first)
    df = df.sort_values(["day", "cod_respuesta"], ascending=[False, True])
    
    summaries = []
    
    for day, group in df.groupby("day", sort=False):
        operador = group["operador"].iloc[0].strip()
        total_txn = int(group["total_txn_day"].iloc[0])
        
        day_summary = [f"Date: {day.date()} | Merchant: {operador} | Total transactions: {total_txn}."]
        
        for _, row in group.iterrows():
            code = row["cod_respuesta"]
            txns = int(row["transaction_count"])
            pct = row["pct_of_day_txns"]
            trend = row["trend_direction"]
            change = row["pct_change_vs_prev_day"]
            
            # Handle NaNs nicely
            if pd.isna(change):
                change_text = "no prior comparison"
            else:
                change_text = f"{change:.2f}% vs previous day"
            
            line = (
                f"Code {code}: {txns} transactions "
                f"({pct:.2f}% of volume), trend is {trend}"
                f" ({change_text})."
            )
            
            day_summary.append(line)
        
        summaries.append(" ".join(day_summary))
    
    return "\n".join(summaries)

In [19]:
from typing import Any, Dict

def _normalize_prompt_value(value: Any) -> str:
    if value is None:
        return "null"

    text = str(value).strip()
    if text == "" or text.lower() == "nan":
        return "null"

    return text


def format_commerce_summary_for_prompt(commerce_summary: pl.DataFrame | Any) -> str:
    """
    Convert the Polars merchant summary dataframe into a compact, readable
    prompt section instead of dumping the dataframe object with json.dumps.
    """
    if commerce_summary is None:
        return "No transactional summary available."

    if not isinstance(commerce_summary, pl.DataFrame):
        return json.dumps(commerce_summary, indent=2, default=str)

    if commerce_summary.is_empty():
        return "No transactional summary available."

    expected_columns = {"metric", "t1d", "t1w", "ytd"}
    if expected_columns.issubset(set(commerce_summary.columns)):
        lines = []
        for row in commerce_summary.iter_rows(named=True):
            metric = row.get("metric", "unknown_metric")
            t1d = _normalize_prompt_value(row.get("t1d"))
            t1w = _normalize_prompt_value(row.get("t1w"))
            ytd = _normalize_prompt_value(row.get("ytd"))
            lines.append(f"- {metric}: t1d={t1d}, t1w={t1w}, ytd={ytd}")
        return "\n".join(lines)

    return commerce_summary.write_json(row_oriented=True)

In [20]:
def build_card_verification_query(merchant: str) -> str:
    merchant = merchant.replace("'", "''")  # escape single quotes for SQL

    return f"""
WITH params AS (
    SELECT
        date_trunc('hour', current_timestamp) - interval '1 hour' AS current_hour_start,
        date_trunc('hour', current_timestamp) AS current_hour_end
),
base AS (
    SELECT
        ot.operador,
        RIGHT(ot.operador, 2) AS pais,
        ot.fecharegistro,
        ot.importe
    FROM is_pii_parabilium.operations_temp ot
    LEFT JOIN is_provider_parabilium.auth_blacklist_elements bl
        ON LEFT(ot.operador, 22) = LEFT(bl.value, 22)
    CROSS JOIN params p
    WHERE
        ot.operador = '{merchant}'
        AND RIGHT(ot.operador, 2) NOT IN ('MX', 'Mx')
        AND bl.value IS NULL
        AND ot.fecharegistro >= p.current_hour_start - interval '7 days'
        AND ot.fecharegistro < p.current_hour_end
),
current_hour AS (
    SELECT
        operador,
        pais,
        COUNT(*) AS total_count_1h,
        SUM(CASE WHEN importe = 0 THEN 1 ELSE 0 END) AS validation_count_1h,
        SUM(CASE WHEN importe = 0 THEN 1 ELSE 0 END)::float / NULLIF(COUNT(*), 0) AS validation_rate_1h
    FROM base b
    CROSS JOIN params p
    WHERE
        b.fecharegistro >= p.current_hour_start
        AND b.fecharegistro < p.current_hour_end
    GROUP BY
        operador,
        pais
),
historical_same_hour AS (
    SELECT
        operador,
        date_trunc('hour', fecharegistro) AS hora,
        COUNT(*) AS total_count_hour,
        SUM(CASE WHEN importe = 0 THEN 1 ELSE 0 END) AS validation_count_hour,
        SUM(CASE WHEN importe = 0 THEN 1 ELSE 0 END)::float / NULLIF(COUNT(*), 0) AS validation_rate_hour
    FROM base b
    CROSS JOIN params p
    WHERE
        b.fecharegistro >= p.current_hour_start - interval '7 days'
        AND b.fecharegistro < p.current_hour_start
        AND EXTRACT(hour FROM b.fecharegistro) = EXTRACT(hour FROM p.current_hour_start)
    GROUP BY
        operador,
        date_trunc('hour', fecharegistro)
),
historical_baseline AS (
    SELECT
        operador,
        AVG(total_count_hour) AS avg_total_count_same_hour_7d,
        AVG(validation_count_hour) AS avg_validation_count_same_hour_7d,
        AVG(validation_rate_hour) AS avg_validation_rate_same_hour_7d,
        MAX(validation_count_hour) AS max_validation_count_same_hour_7d,
        MAX(validation_rate_hour) AS max_validation_rate_same_hour_7d,
        COUNT(*) AS baseline_hours
    FROM historical_same_hour
    GROUP BY
        operador
)
SELECT
    c.operador,
    c.pais,
    c.total_count_1h,
    c.validation_count_1h,
    c.validation_rate_1h,
    h.avg_total_count_same_hour_7d,
    h.avg_validation_count_same_hour_7d,
    h.avg_validation_rate_same_hour_7d,
    h.max_validation_count_same_hour_7d,
    h.max_validation_rate_same_hour_7d,
    h.baseline_hours,
    c.validation_count_1h - h.avg_validation_count_same_hour_7d AS validation_count_lift,
    c.validation_rate_1h / NULLIF(h.avg_validation_rate_same_hour_7d, 0) AS validation_rate_multiplier
FROM current_hour c
LEFT JOIN historical_baseline h
    ON c.operador = h.operador
WHERE
    c.validation_count_1h >= 5 ------ MODIFY
    AND c.validation_rate_1h >= 0.40
ORDER BY
    c.validation_count_1h DESC;
"""

def summarize_card_verification_anomaly(merchant: str) -> str:

    query = build_card_verification_query(merchant)
    card_verification_df = pd.read_sql(query, con=get_db_conn())
    if card_verification_df is None or card_verification_df.empty:
        return "No card verification anomaly matched the configured thresholds in the last hour."

    required_columns = [
        "operador",
        "validation_count_1h",
        "validation_rate_1h",
        "avg_validation_count_same_hour_7d",
        "avg_validation_rate_same_hour_7d",
        "validation_rate_multiplier",
    ]
    missing_columns = [col for col in required_columns if col not in card_verification_df.columns]
    if missing_columns:
        raise ValueError(f"Missing expected columns: {', '.join(missing_columns)}")

    def _clean_value(value):
        return None if pd.isna(value) else value

    def _format_number(value, decimals: int = 1) -> str:
        value = _clean_value(value)
        if value is None:
            return "N/A"
        return f"{value:.{decimals}f}"

    def _format_pct(value) -> str:
        value = _clean_value(value)
        if value is None:
            return "N/A"
        return f"{value * 100:.1f}%"

    def _summarize_row(row: pd.Series) -> str:
        merchant = str(_clean_value(row["operador"]) or "Unknown merchant").strip()
        current_count = _clean_value(row["validation_count_1h"])
        current_rate = _clean_value(row["validation_rate_1h"])
        avg_count = _clean_value(row["avg_validation_count_same_hour_7d"])
        avg_rate = _clean_value(row["avg_validation_rate_same_hour_7d"])
        multiplier = _clean_value(row["validation_rate_multiplier"])

        if avg_count is None or avg_rate is None:
            return (
                f"{merchant} had {_format_number(current_count, 0)} card verifications in the last hour, "
                f"with a verification rate of {_format_pct(current_rate)}. "
                "No reliable 7-day same-hour baseline was available, so this should be reviewed manually."
            )

        return (
            f"{merchant} had {_format_number(current_count, 0)} card verifications in the last hour, "
            f"versus a 7-day same-hour average of {_format_number(avg_count)}. "
            f"The current verification rate is {_format_pct(current_rate)}, compared with a historical "
            f"same-hour average of {_format_pct(avg_rate)}. "
            f"That is about {_format_number(multiplier)}x the normal verification rate, suggesting abnormal "
            "card-testing or card-validation behavior."
        )

    summaries = [_summarize_row(row) for _, row in card_verification_df.iterrows()]
    return summaries[0] if len(summaries) == 1 else "\n".join(f"- {summary}" for summary in summaries)

In [21]:
def build_final_report(
    merchant: str,
    blocked_date: str,
    commerce_summary: pl.DataFrame,
    chargebacks_summary: Dict,
    cod_analysis_df: str,
    alert_type: str,
    card_verifications_summary: str = "",
) -> str:
    """
    Standalone version of the notebook prompt builder that formats the Polars
    commerce summary before embedding it into the prompt.
    """
    formatted_commerce_summary = format_commerce_summary_for_prompt(commerce_summary)
    formatted_chargebacks_summary = (
        json.dumps(chargebacks_summary, indent=2, default=str)
        if chargebacks_summary
        else "No chargeback records found for the specified merchant."
    )
    formatted_cod_analysis = (
        cod_analysis_df
        if cod_analysis_df
        else "No response code data available for analysis."
    )
    formatted_card_verifications_summary = str(card_verifications_summary).strip() if card_verifications_summary else ""
    if not formatted_card_verifications_summary or formatted_card_verifications_summary.lower() == "nan":
        formatted_card_verifications_summary = "No card verification anomaly summary available."


    fraud_prompt_final = f"""
    MERCHANT FRAUD ANALYSIS REQUEST for alert {alert_type}
    ================================

    MERCHANT CONTEXT:
    {merchant} was blocked on {blocked_date} due to "Card Verifications".

    ---

    PAST TRANSACTIONALITY SUMMARY:
    {formatted_commerce_summary}

    ---

    CHARGEBACKS SUMMARY:
    {formatted_chargebacks_summary}

    ---

    RESPONSE CODES ANALYSIS:
    {formatted_cod_analysis}

    ---

    CARD VERIFICATIONS SUMMARY:
    {formatted_card_verifications_summary}

    ---

    ANALYSIS REQUIREMENTS:
    1. Evaluate the merchant based on all three data dimensions (transactions, chargebacks, response codes)
    2. Identify patterns that indicate fraud or card testing activities
    3. Consider the relationship between failed transaction counts and specific response codes
    4. Assess the risk of this merchant based on:
    - Transaction velocity and volume
    - Chargeback patterns and frequency
    - Response code distribution (especially codes 14, 87, 51)
    - Temporal patterns in activity
    5. Provide a clear recommendation: BLOCK or DO NOT BLOCK

    Make a comprehensive decision based on all provided data.
    """
    return fraud_prompt_final

In [22]:
def prompt_pipeline(merchant: str, blocked_date: str, alert_type: str) -> str:
    trx_summary_df = merchant_trx_summary(merchant=merchant, blocked_date=blocked_date)
    # create chargeback summary for the merchant
    cb_df = chargeback_merchant_summary(merchant_name=merchant, blocking_date=blocked_date)
    # create cod response df
    cod_df = build_cod_risk_summary(merchant_to_block=merchant, block_date=blocked_date)
    # create card verification df
    cv_summary = summarize_card_verification_anomaly(merchant=merchant)

    # build the final report for the agent
    user_prompt = build_final_report(
        merchant=merchant,
        blocked_date=blocked_date,
        commerce_summary=trx_summary_df,
        chargebacks_summary=cb_df,
        cod_analysis_df=cod_df,
        card_verifications_summary=cv_summary,
        alert_type=alert_type,
    )
    
    return user_prompt

In [23]:
async def fraud_CV_agent(final_prompt: str) :
    # read prompt txt from file
    with open("/Users/camila.cusicanqui/Documents/klar/mini-tasks/agents-automization/fraud_alerts_instruction_prompt.txt", "r") as file:
        instructions_fraud = file.read()
        
    agent_fraude = Agent(
        name="Fraud Analyst",
        instructions=instructions_fraud,
        output_type=FraudFinding,
    )
    result = await Runner.run(
        agent_fraude,
        final_prompt,
    )
    return result
    #print(result)

In [24]:
SERVICE_ACCOUNT_FILE = r'.config/klar-cami-cusi.json'
gc = gspread.service_account(filename=SERVICE_ACCOUNT_FILE)
sheet_id = "15JrCjqynUuPd8kXlixAIIYeYNcADiG48GeSLxeIy0ks"
worksheet_gid = '601362568'
spreadsheet = gc.open_by_key(sheet_id)
# connect to ghseets
worksheet = spreadsheet.worksheet('actual_bl')
bl_merchants_df = pd.DataFrame(worksheet.get_all_records())
bl_merchants_df.rename(columns={'merchant_name': 'operador'}, inplace=True)
bl_merchants_df["updated_at"] = pd.to_datetime(bl_merchants_df["updated_at"])
# remove the * from the merchant names
bl_merchants_df["merchant"] = bl_merchants_df["operador"].str.replace('*', '', regex=False)
bl_merchants_df["operador_length"] = bl_merchants_df["operador"].apply(lambda x: len(x))
bl_merchants_df["merchant_length"] = bl_merchants_df["merchant"].apply(lambda x: len(x))

# obtain the merchants that we need to analyze from the BL list, filter by date and reason of block
bl_merchants_to_test = bl_merchants_df[
    (bl_merchants_df["updated_at"] >= '2026-01-01')
    & (bl_merchants_df["status"] == 'Bloqueado')
    & (bl_merchants_df["reason"] == 'Card Verifications')
][["merchant", 'updated_at']]

In [32]:
len('ANTHROPIC             SAN FRANCISCOCA US')

40

In [25]:
# TODO: also consider the related commerce summary for the shared commerce analysis

In [26]:
bl_merchants_to_test.iloc[-2:]

                                     merchant          updated_at
359  WWW.TECH-VAULT.COM    SINGAPORE       SG 2026-02-07 07:05:59
361  OBERWEIS HOME DELIVERYNORTH AURORA IL US 2026-01-31 04:06:34

In [33]:
# antropic_test
TEST_MERCHANT = 'ANTHROPIC             SAN FRANCISCOCA US'
TEST_BLOCKED_DATE = '2026-04-01 05:07:36'
print(f"Analyzing merchant: {TEST_MERCHANT} | Blocked at: {TEST_BLOCKED_DATE}")
print("Fetching transaction data summary...")
# obtain the transaction summary for the merchant
user_prompt = prompt_pipeline(
    merchant=TEST_MERCHANT,
    blocked_date=TEST_BLOCKED_DATE,
    alert_type= 'ABNORMAL CARD VERIFICATIONS'
)
print("Final comprehensive prompt for analysis:")
result = await fraud_CV_agent(user_prompt)
print("Agent result:")
result = result.final_output.model_dump()  # Pydantic v2
result["suspicious_signals"] = "\n".join(result["suspicious_signals"])
print(result)

print('Finished analyzing merchant:', TEST_MERCHANT, '.....\n')
print(' ')
print(' ')

Analyzing merchant: ANTHROPIC             SAN FRANCISCOCA US | Blocked at: 2026-04-01 05:07:36
Fetching transaction data summary...

/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2016719537.py:194: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cb_df = pd.read_sql(cb_query, get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2004360204.py:74: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(response_code_query, con=get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/3607359053.py:100: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  card_verification_df = pd.read_sql(query, con=get_db_conn())

Final comprehensive prompt for analysis:
Agent result:
{'merchant_name': 'ANTHROPIC             SAN FRANCISCOCA US', 'risk_level': 'high', 'summary': 'The merchant demonstrates persistent abnormal card verification rates (72.7% vs 67.2% baseline), an elevated and increasing rate of risky code 87 response (with spikes up to 46% of daily transactions), and 2 chargebacks YTD (both on cards with no CVV and unknown 3DS). Transaction history shows significant failed/canceled states and a notable percentage of no-CVV/no-3DS attempts. These combined factors, alongside the already-blocked status for card verifications, show a strong and repeated pattern of card-testing or validation abuse.', 'suspicious_signals': 'Abnormal card verification rate currently 72.7% vs 67.2% baseline (1.1x lift)\nFrequent and sometimes high concentration of response code 87 (e.g., >10% many days, spikes up to 46.15% of daily volume)\nTrend of code 87 spikes and instability in use, including recent increases\n2 chargebacks YTD, both associated with no CVV provided\nHigh failed/canceled transaction counts (e.g., 220 in last week vs 194 authorized/settled)\nVery high volume of no 3DS / no CVV verifications\nCard verification alert triggered and merchant already previously blocked', 'recommendation': 'BLOCK', 'confidence': 0.98}
Finished analyzing merchant: ANTHROPIC             SAN FRANCISCOCA US .....

In [27]:
extra_merchant_result = {}

for merchant, blocked_date in bl_merchants_to_test.drop(index=[3,7,8]).itertuples(index=False):
# bl_merchants_to_test.drop([0,1]).itertuples(index=False):
    blocked_date = str(blocked_date)
    print(f"Analyzing merchant: {merchant} | Blocked at: {blocked_date}")
    print("Fetching transaction data summary...")
    # obtain the transaction summary for the merchant
    user_prompt = prompt_pipeline(
        merchant=merchant,
        blocked_date=blocked_date,
        alert_type= 'ABNORMAL CARD VERIFICATIONS'
    )
    print("Final comprehensive prompt for analysis:")
    result = await fraud_CV_agent(user_prompt)
    print("Agent result:")
    result = result.final_output.model_dump()  # Pydantic v2
    result["suspicious_signals"] = "\n".join(result["suspicious_signals"])
    print(result)
    df = pd.DataFrame([result])
    extra_merchant_result[merchant] = df
    print('Finished analyzing merchant:', merchant, '.....\n')
    print(' ')
    print(' ')

Analyzing merchant: FOUNDERSCARD.COM      NEW YORK     NY US | Blocked at: 2026-05-06 18:48:05
Fetching transaction data summary...

/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2016719537.py:194: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cb_df = pd.read_sql(cb_query, get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2004360204.py:74: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(response_code_query, con=get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/3607359053.py:100: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  card_verification_df = pd.read_sql(query, con=get_db_conn())

Final comprehensive prompt for analysis:
Agent result:
{'merchant_name': 'FOUNDERSCARD.COM      NEW YORK     NY US', 'risk_level': 'high', 'summary': "The merchant has only 2 transactions on record, both occurring within a short timeframe (t1w: 2026-05-05 09:26-09:27), from a single user. Both transactions returned response code 87 (CVV incorrect/missing), indicating a 100% failure rate due to invalid CVV information—a strong card-testing indicator. There is no normal authorization or settlement activity beyond these, and no card verifications exceeded alert thresholds, possibly due to low attempt volume. No chargebacks are reported yet, but the absence is not exculpatory given the merchant's newness and very limited history.", 'suspicious_signals': 'Only 2 transactions, both within 1 minute window\n100% failed transactions with response code 87 (CVV incorrect/missing)\nTransactions from a single unique user\nNo normal transaction activity\nSudden merchant activation and immediate failure pattern', 'recommendation': 'BLOCK', 'confidence': 0.95}
Finished analyzing merchant: FOUNDERSCARD.COM      NEW YORK     NY US .....



Analyzing merchant: EMPATHIQ              SAN DIEGO    CA US | Blocked at: 2026-05-05 13:08:43
Fetching transaction data summary...

/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2016719537.py:194: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cb_df = pd.read_sql(cb_query, get_db_conn())
[non-fatal] Tracing client error 429: {
  "error": {
    "message": "You've exceeded the rate limit, please slow down and try again after 60.055806 seconds.",
    "type": "invalid_request_error",
    "param": null,
    "code": "rate_limit_exceeded"
  }
}
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2004360204.py:74: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(response_code_query, con=get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/3607359053.py:100: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  card_verification_df = pd.read_sql(query, con=get_db_conn())

Final comprehensive prompt for analysis:
Agent result:
{'merchant_name': 'EMPATHIQ              SAN DIEGO    CA US', 'risk_level': 'high', 'summary': 'The merchant shows extremely recent activity with a high concentration of risky response codes: code 14 (invalid card) and code 87 (CVV errors) together make up a large share of the past days’ transactions (up to 100%), with only 4 unique users and previously little to no history. No chargebacks are present, but the strong pattern of failed and declined card validations, repeated in a short window, and a very low user count, indicate clear card-testing or validation attacks.', 'suspicious_signals': 'Very recent first and last transactions, merchant is likely new\nExtremely low unique user count (2 in t1d, 4 in t1w/ytd)\nCode 14 (invalid card) and 87 (CVV error) account for up to 100% of daily volume\nCode 87 spiking from 14% to 67% of volume day-over-day\nHigh count of failed/canceled transactions relative to total\nNo card verification anomaly in last hour but prior window shows clear abnormalities\nNo chargebacks, but alarming card auth/response code pattern', 'recommendation': 'BLOCK', 'confidence': 0.95}
Finished analyzing merchant: EMPATHIQ              SAN DIEGO    CA US .....



Analyzing merchant: VINAUDIT COM INC      KIRKLAND     WA US | Blocked at: 2026-04-30 23:15:18
Fetching transaction data summary...

/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2016719537.py:194: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cb_df = pd.read_sql(cb_query, get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2004360204.py:74: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(response_code_query, con=get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/3607359053.py:100: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  card_verification_df = pd.read_sql(query, con=get_db_conn())

Final comprehensive prompt for analysis:
Agent result:
{'merchant_name': 'VINAUDIT COM INC      KIRKLAND     WA US', 'risk_level': 'high', 'summary': 'This merchant shows classic signs of card testing: it has just started activity (first and last transactions occurred within minutes), a very high failed/canceled rate (68 out of 72 total transactions), a heavy concentration of code 87 (61 transactions, suggesting card validation failure), substantial code 51 activity (16 times), and all authorized transactions appear to have been processed without 3DS or CVV. Additionally, failed transactions far outnumber successful ones (68 failed/canceled vs 4 authorized/settled), and all approved transactions lack 3DS/CVV. This suspicious pattern, plus the absence of prior history and clustering of risky response codes, strongly supports that this is a card-testing merchant.', 'suspicious_signals': 'Sudden and recent transactional activity (first and last transaction within 1 minute)\nHigh volume of failed/canceled transactions (68 of 72 total)\nVery high code 87 (card validation fail) count: 61\nSignificant code 51 (insufficient funds) count: 16, mostly without 3DS/CVV\nAll 4 authorized/settled transactions are no_3ds_no_cvv\nAll activity occurred on the same day with no prior history\nFailed/canceled to authorized ratio is extremely high (68:4)\nHighly concentrated card entry with physical credit cards from one BIN without CVV/3DS', 'recommendation': 'BLOCK', 'confidence': 0.98}
Finished analyzing merchant: VINAUDIT COM INC      KIRKLAND     WA US .....



Analyzing merchant: Smoke Club FL LLC     Orlando      FL US | Blocked at: 2026-04-18 22:05:52
Fetching transaction data summary...

/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2016719537.py:194: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cb_df = pd.read_sql(cb_query, get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2004360204.py:74: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(response_code_query, con=get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/3607359053.py:100: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  card_verification_df = pd.read_sql(query, con=get_db_conn())

Final comprehensive prompt for analysis:
Agent result:
{'merchant_name': 'Smoke Club FL LLC     Orlando      FL US', 'risk_level': 'high', 'summary': 'The merchant shows strong signs of card testing and card validation abuse, including extremely high concentrations of response codes 14 (invalid card number) and 87 (CVV incorrect) on 2026-04-17, representing 44.8% and 55.2% of total transactions, respectively. The merchant has very recent, compact activity (most activity within ~1 day), low unique user count (5 in t1d, 12 in t1w/ytd), and a high number of failed or canceled transactions relative to total activity. No chargeback evidence is present, but the extreme concentration of risky response codes and rapid, clustered transaction activity with low user diversity strongly support card testing abuse.', 'suspicious_signals': '44.8% of transactions with code 14 (invalid card number) on 2026-04-17\n55.2% of transactions with code 87 (CVV incorrect) on 2026-04-17\n33 transactions with code 14 in t1d, 46 in t1w/ytd (showing abrupt clustering)\n4 transactions with code 87 in t1d, 20 in t1w/ytd\n12 unique users in total, with clustered activity\nRecent merchant activity, starting 2026-04-17, latest on 2026-04-18\nSignificant failed/canceled transactions (5 in t1d, 18 in t1w/ytd)', 'recommendation': 'BLOCK', 'confidence': 0.95}
Finished analyzing merchant: Smoke Club FL LLC     Orlando      FL US .....



Analyzing merchant: Paul Stuart Inc       2126820320   NY US | Blocked at: 2026-04-12 15:05:57
Fetching transaction data summary...

/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2016719537.py:194: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cb_df = pd.read_sql(cb_query, get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2004360204.py:74: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(response_code_query, con=get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/3607359053.py:100: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  card_verification_df = pd.read_sql(query, con=get_db_conn())

Final comprehensive prompt for analysis:
Agent result:
{'merchant_name': 'Paul Stuart Inc       2126820320   NY US', 'risk_level': 'high', 'summary': 'The merchant shows a clear pattern of card testing, indicated by very recent first activity, high counts of response codes 14 (62 instances) and 87 (23 instances) within roughly 5 hours, and only 14 unique users, suggesting concentrated abuse. All suspicious activity occurred on the same day with no meaningful legitimate transaction history, and a high ratio of card-verification failure codes relative to unique users further supports a card-testing pattern.', 'suspicious_signals': 'First and only activity within a single day (all first_tx_date and last_tx_date data: 2026-04-12)\nHigh cnt_cr_14 (62) and cnt_cr_87 (23) in a 5-hour window\nLow unique user count (14) compared to high failed/canceled attempts\nHigh failed/canceled transaction count (20) relative to lifespan and user volume\nNo meaningful legitimate transaction history\nNo chargebacks yet, but merchant is extremely new', 'recommendation': 'BLOCK', 'confidence': 0.95}
Finished analyzing merchant: Paul Stuart Inc       2126820320   NY US .....



Analyzing merchant: M800 LIMITED          KOWLOON BAY  KowHK | Blocked at: 2026-04-10 21:55:52
Fetching transaction data summary...

/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2016719537.py:194: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cb_df = pd.read_sql(cb_query, get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2004360204.py:74: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(response_code_query, con=get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/3607359053.py:100: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  card_verification_df = pd.read_sql(query, con=get_db_conn())

Final comprehensive prompt for analysis:
Agent result:
{'merchant_name': 'M800 LIMITED          KOWLOON BAY  KowHK', 'risk_level': 'medium', 'summary': 'The merchant shows some abnormal response-code patterns (elevated code 87 and code 14 rates on specific days, and an increasing trend in code 87), but recent card verification activity does not currently exceed thresholds. Transactional volume is low and concentrated, and there is no evidence of chargebacks. The merchant was already blocked previously for card verifications. While some risk signals exist, there is insufficient current activity and chargeback evidence to warrant a block solely on the current data.', 'suspicious_signals': 'Increasing trend in response code 87 (6.06% of volume on 2026-03-25)\nCode 14 appearing at 3.98% of volume on 2026-03-17\nPrior block for card verifications\nMajority of t1d/t1w transactions authorized, but with historically a high number of failed/canceled attempts (ytd=204) vs settled (ytd=13)', 'recommendation': 'NOT BLOCK', 'confidence': 0.65}
Finished analyzing merchant: M800 LIMITED          KOWLOON BAY  KowHK .....



Analyzing merchant: NY POST DIGITAL MEMBERNEW YORK     NY US | Blocked at: 2026-04-09 23:07:39
Fetching transaction data summary...

/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2016719537.py:194: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cb_df = pd.read_sql(cb_query, get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2004360204.py:74: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(response_code_query, con=get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/3607359053.py:100: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  card_verification_df = pd.read_sql(query, con=get_db_conn())

Final comprehensive prompt for analysis:
Agent result:
{'merchant_name': 'NY POST DIGITAL MEMBERNEW YORK     NY US', 'risk_level': 'high', 'summary': 'This merchant shows a clear card verification pattern with high counts of suspicious response codes (14 and 87), all activity confined to a very short period, a low number of unique users, high failed/canceled transactions, and no prior transactional history. No card verification anomaly was detected in the last hour, but the prior activity is highly consistent with card testing/validation abuse.', 'suspicious_signals': 'First and last transaction within six minutes, all on one day\n14 transactions with response code 14 (invalid card number) and 9 with code 87 (CVV invalid/missing), making up all reported activity\nOnly 7 unique users across 14+9 transactions, indicating testing rather than normal customer activity\n7 failed/canceled transactions, suggesting repeated unsuccessful attempts\nMerchant was previously blocked for card verifications\nNo chargebacks, but merchant is extremely new and has only card-testing style activity', 'recommendation': 'BLOCK', 'confidence': 0.95}
Finished analyzing merchant: NY POST DIGITAL MEMBERNEW YORK     NY US .....



Analyzing merchant: COOK MEMORIAL PUBLIC  LIBERTYVILLE IL US | Blocked at: 2026-04-09 18:05:37
Fetching transaction data summary...

/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2016719537.py:194: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cb_df = pd.read_sql(cb_query, get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2004360204.py:74: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(response_code_query, con=get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/3607359053.py:100: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  card_verification_df = pd.read_sql(query, con=get_db_conn())

Final comprehensive prompt for analysis:
Agent result:
{'merchant_name': 'COOK MEMORIAL PUBLIC  LIBERTYVILLE IL US', 'risk_level': 'high', 'summary': 'The merchant initiated activity very recently, with all transactional history confined within minutes on the same day, and shows high counts of card-testing response codes (35 for code 14 and 27 for code 87) alongside 21 failed/canceled transactions from only 20 users, signaling concentrated and abusive card verification attempts. No chargeback cases or response-code analysis are present to mitigate risk, and verification thresholds were apparently not triggered in the last hour, but the raw activity and profile strongly indicate card testing.', 'suspicious_signals': 'Transaction history extremely short (all activity in minutes on the same day)\nHigh counts of card validation response codes (35 with code 14, 27 with code 87)\n21 failed/canceled transactions out of a narrow total user base (20 unique users)\nActivity coincides with the merchant immediately being blocked for card verifications\nNo normal transaction history or prior merchant presence', 'recommendation': 'BLOCK', 'confidence': 0.96}
Finished analyzing merchant: COOK MEMORIAL PUBLIC  LIBERTYVILLE IL US .....



Analyzing merchant: LUAN MEIRELLES DIAS PARIBEIRAO PRETSP BR | Blocked at: 2026-04-08 23:24:40
Fetching transaction data summary...

/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2016719537.py:194: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cb_df = pd.read_sql(cb_query, get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2004360204.py:74: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(response_code_query, con=get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/3607359053.py:100: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  card_verification_df = pd.read_sql(query, con=get_db_conn())

Final comprehensive prompt for analysis:
Agent result:
{'merchant_name': 'LUAN MEIRELLES DIAS PARIBEIRAO PRETSP BR', 'risk_level': 'medium', 'summary': 'The merchant demonstrates extremely limited history, with only one transaction, one user, and one authorization, all occurring on the same date. There is a confirmed chargeback associated with this single transaction, which occurred without 3DS or CVV, using a physical, platinum card. However, there is no response code data indicating a pattern of card-testing or verification abuse, and no evidence of high transaction or verification velocity. The case is suspicious due to the immediate chargeback, but the volume is too limited, and further patterns of abuse are not evident based on the available data.', 'suspicious_signals': 'Only one transaction and one user appear in the record\nThe single transaction resulted in a chargeback within days of first appearance\nNo CVV and no 3DS present in the transaction\nPHYSICAL/platinum card used\nNo subsequent activity or transaction velocity observed', 'recommendation': 'NOT BLOCK', 'confidence': 0.7}
Finished analyzing merchant: LUAN MEIRELLES DIAS PARIBEIRAO PRETSP BR .....



Analyzing merchant: IONOS INC             CHESTERBROOK PA US | Blocked at: 2026-04-05 01:07:52
Fetching transaction data summary...

/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2016719537.py:194: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cb_df = pd.read_sql(cb_query, get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2004360204.py:74: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(response_code_query, con=get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/3607359053.py:100: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  card_verification_df = pd.read_sql(query, con=get_db_conn())

Final comprehensive prompt for analysis:
Agent result:
{'merchant_name': 'IONOS INC             CHESTERBROOK PA US', 'risk_level': 'medium', 'summary': 'The merchant shows some suspicious signals including a history of failed/canceled transactions, a high concentration of no CVV/no 3DS transactions, repeated unauthorized attempts, and a confirmed chargeback with a virtual card and no CVV. However, there is no current spike in card verifications and the response code 87 rates, while elevated at times, are not extremely high or rapidly increasing now. Recent chargeback activity is low, but transaction patterns and authentication methods warrant concern.', 'suspicious_signals': 'High number of failed/canceled transactions in relation to authorized/settled transactions (t1w: 101 failed/canceled vs 66 authorized)\nLarge proportion of transactions with no 3DS and no CVV (t1w: 955/1436 total)\nRecent chargeback for a virtual card with no CVV or 3DS\nHistoric response code 87 spikes to above 10% of activity on certain days\nConcentration in VIRTUAL card types and CREDIT_5401_BIN with no CVV/3DS', 'recommendation': 'SCALE TO HUMAN INTERVENTION', 'confidence': 0.75}
Finished analyzing merchant: IONOS INC             CHESTERBROOK PA US .....



Analyzing merchant: Hims and Hers Inc.    San FranciscoCA US | Blocked at: 2026-04-04 00:05:42
Fetching transaction data summary...

/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2016719537.py:194: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cb_df = pd.read_sql(cb_query, get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2004360204.py:74: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(response_code_query, con=get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/3607359053.py:100: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  card_verification_df = pd.read_sql(query, con=get_db_conn())

Final comprehensive prompt for analysis:
Agent result:
{'merchant_name': 'Hims and Hers Inc.    San FranciscoCA US', 'risk_level': 'high', 'summary': 'The merchant shows a strong pattern of card testing or card validation abuse, with 100% of recent transactions (25/25) receiving response code 14 (invalid card number), and a significant day-over-day spike (257% increase from previous period). This activity is concentrated among only 5 unique users with matching failed/canceled states and a total lack of successful or regular transactional activity. No chargebacks are present yet, but the response code concentration and lack of normal customer behavior indicate high risk.', 'suspicious_signals': '100% of 25 recent transactions received response code 14 (invalid card number)\n257% increase in code 14 transactions vs. prior day\nHistorical presence of code 87 (5/12, 41.67% of previous window)\nVery low user diversity (5 unique users)\nNo successful transactions; all failed/canceled\nSudden, anomalous card-verification-like activity', 'recommendation': 'BLOCK', 'confidence': 0.95}
Finished analyzing merchant: Hims and Hers Inc.    San FranciscoCA US .....



Analyzing merchant: ELKWEDY PERFUMES AND GDubai        000AE | Blocked at: 2026-04-03 08:06:53
Fetching transaction data summary...

/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2016719537.py:194: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cb_df = pd.read_sql(cb_query, get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2004360204.py:74: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(response_code_query, con=get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/3607359053.py:100: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  card_verification_df = pd.read_sql(query, con=get_db_conn())

Final comprehensive prompt for analysis:
Agent result:
{'merchant_name': 'ELKWEDY PERFUMES AND GDubai        000AE', 'risk_level': 'medium', 'summary': 'The merchant shows suspicious signals including very short history (first and last transaction within an hour), all 41 transactions failed or canceled with response code 51 (insufficient funds), all without 3DS or CVV, and activity distributed over only 25 unique users. However, there are no confirmed chargebacks and no abnormal card verifications matched in the last hour, and no response code 14 or 87 activity is reported. Lack of supporting response code anomalies and no chargebacks means strong card-testing/fraud patterns are unconfirmed.', 'suspicious_signals': 'All 41 transactions failed/canceled with code 51 in less than one hour\nAll transactions are no 3DS and no CVV\nVery recent merchant history (first and last tx same hour)\nPhysical and virtual card attempts\nActivity spread over only 25 unique users', 'recommendation': 'SCALE TO HUMAN INTERVENTION', 'confidence': 0.7}
Finished analyzing merchant: ELKWEDY PERFUMES AND GDubai        000AE .....



Analyzing merchant: ELKWEDY FASHION DESIGNDubai        000AE | Blocked at: 2026-04-01 05:07:36
Fetching transaction data summary...

/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2016719537.py:194: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cb_df = pd.read_sql(cb_query, get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2004360204.py:74: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(response_code_query, con=get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/3607359053.py:100: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  card_verification_df = pd.read_sql(query, con=get_db_conn())

Final comprehensive prompt for analysis:
Agent result:
{'merchant_name': 'ELKWEDY FASHION DESIGNDubai        000AE', 'risk_level': 'high', 'summary': 'This merchant shows strong evidence of abuse with a pattern consistent with card testing or card validation attacks. There is a very short and abrupt merchant history (activity starting and ending within ~6 hours), no authorizations on t1d, 50 failed/canceled transactions in one week versus just 14 authorizations, and 12 chargebacks from a single user using a physical credit card (CREDIT_5401_BIN) with all chargebacks for no CVV and unknown 3DS status. Concentration of chargebacks to one user and a high ratio of failed/canceled transactions relative to successful ones strongly indicate abusive, possibly fraudulent activity. The absence of detailed response-code data does not offset the strong chargeback and failed-transaction evidence.', 'suspicious_signals': '50 failed/canceled transactions in one week\n14 authorized/settled transactions in one week\nAll chargebacks (12) concentrated to a single user on a single card/bin/type\nAll chargebacks with no CVV and unknown 3DS status\nVery short and sudden transaction history (first and last tx within a few hours)\nHigh count of failed/canceled, mostly no CVV and no 3DS\nNo card verification anomalies in last hour, but prior failed patterns persist', 'recommendation': 'BLOCK', 'confidence': 0.95}
Finished analyzing merchant: ELKWEDY FASHION DESIGNDubai        000AE .....



Analyzing merchant: Nova Wave Trading FZLLRas AlKhaima000AE | Blocked at: 2026-03-31 16:51:00
Fetching transaction data summary...

/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2016719537.py:194: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cb_df = pd.read_sql(cb_query, get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2004360204.py:74: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(response_code_query, con=get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/3607359053.py:100: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  card_verification_df = pd.read_sql(query, con=get_db_conn())

Final comprehensive prompt for analysis:
Agent result:
{'merchant_name': 'Nova Wave Trading FZLLRas AlKhaima000AE', 'risk_level': 'low', 'summary': 'There is no transactional, chargeback, or response code evidence showing current suspicious activity or card-testing behavior, and no current card-verification anomalies have been detected. The merchant was previously blocked for card verifications, but no concrete evidence of abuse is present in the available data.', 'suspicious_signals': 'Previously blocked for card verifications on 2026-03-31', 'recommendation': 'NOT BLOCK', 'confidence': 0.3}
Finished analyzing merchant: Nova Wave Trading FZLLRas AlKhaima000AE .....



Analyzing merchant: SIMPLISAFE            BOSTON       MA US | Blocked at: 2026-03-31 08:06:11
Fetching transaction data summary...

/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2016719537.py:194: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cb_df = pd.read_sql(cb_query, get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2004360204.py:74: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(response_code_query, con=get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/3607359053.py:100: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  card_verification_df = pd.read_sql(query, con=get_db_conn())

Final comprehensive prompt for analysis:
Agent result:
{'merchant_name': 'SIMPLISAFE            BOSTON       MA US', 'risk_level': 'medium', 'summary': 'The merchant was previously blocked for card verifications, and recent transactions show a cluster of 20 response code 14 (invalid card number) events in a very short period with no successful authorizations and a notable count of failed/canceled states (54 year-to-date). There is only one instance of code 87. Chargebacks are absent, and there are no recent card-verification anomalies per system thresholds. The evidence shows possible card-testing or card-validation probing, especially due to the high concentration of code 14 events, but the absence of card-verification anomalies and chargebacks makes the case less decisive.', 'suspicious_signals': 'High concentration of response code 14 (20 transactions in short time frame)\nZero successful authorizations in t1d and t1w\nHigh number of failed/canceled transactions (54 ytd)\nNo card verification anomaly met threshold in last hour\nNo chargebacks present\nOnly 1 code 87 event (not a cluster)', 'recommendation': 'SCALE TO HUMAN INTERVENTION', 'confidence': 0.7}
Finished analyzing merchant: SIMPLISAFE            BOSTON       MA US .....



Analyzing merchant: MAKRAM HANNA PERFUMES Dubai        000AE | Blocked at: 2026-03-30 14:06:12
Fetching transaction data summary...

/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2016719537.py:194: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cb_df = pd.read_sql(cb_query, get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2004360204.py:74: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(response_code_query, con=get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/3607359053.py:100: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  card_verification_df = pd.read_sql(query, con=get_db_conn())

Final comprehensive prompt for analysis:
Agent result:
{'merchant_name': 'MAKRAM HANNA PERFUMES Dubai        000AE', 'risk_level': 'high', 'summary': "The merchant shows highly suspicious signals: all activity occurred within a single day, with the first transaction at 07:31 and the last at 08:04, suggesting a sudden burst of activity with no prior history. There is a high count of failed/canceled transactions (52) versus only 11 authorized, and all failed attempts lacked both 3DS and CVV. There are 5 chargebacks from just 2 unique users in a single week, all linked to 'no cvv' transactions and unknown 3DS status. The majority of transactions target a specific BIN/product type, showing concentrated and anomalous behavior consistent with card testing. No supportive benign signals are present.", 'suspicious_signals': "All merchant activity occurred within a ~30-minute window, suggesting recent and sudden start\nHigh failed/canceled transaction count (52) compared to authorized (11)\nAll failed/canceled transactions had no CVV and no 3DS\nChargebacks reported immediately: 5 chargebacks from 2 unique users within same week, also all 'no cvv'\nConcentration on PHYSICAL cards and CREDIT_5401_BIN\nNo prior transaction history before this suspicious window\nNo 3DS or CVV for any of the high-risk activity", 'recommendation': 'BLOCK', 'confidence': 0.98}
Finished analyzing merchant: MAKRAM HANNA PERFUMES Dubai        000AE .....



Analyzing merchant: Partyrama             Milton KeynesENGGB | Blocked at: 2026-03-30 10:06:35
Fetching transaction data summary...

/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2016719537.py:194: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cb_df = pd.read_sql(cb_query, get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2004360204.py:74: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(response_code_query, con=get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/3607359053.py:100: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  card_verification_df = pd.read_sql(query, con=get_db_conn())

Final comprehensive prompt for analysis:
Agent result:
{'merchant_name': 'Partyrama             Milton KeynesENGGB', 'risk_level': 'high', 'summary': "The merchant shows strong signs of card-testing abuse: in under 24 hours, there were 46 'invalid card number' (code 14) and 24 'CVV incorrect' (code 87) declines, with only 3 successful authorizations, all attempts clustered within a short window and generated by only 22-24 unique users. There are also many failed/canceled transactions relative to authorizations. This pattern, combined with the lack of normal ongoing transaction volume and absence of chargebacks likely due to novelty, strongly supports a BLOCK decision.", 'suspicious_signals': "46 response code 14 ('invalid card number') in one day\n24 response code 87 ('CVV incorrect') in one day\nOnly 3 successful transactions vs 70+ risky declines\nHigh ratio of failed/canceled to approved txns\nShort history: transactional activity started only in the last day\nLow unique user diversity relative to attempted transactions\nNo supporting legitimate volume or historical context", 'recommendation': 'BLOCK', 'confidence': 0.98}
Finished analyzing merchant: Partyrama             Milton KeynesENGGB .....



Analyzing merchant: CANEX.CA HPS          OTTAWA       000CA | Blocked at: 2026-03-29 23:07:57
Fetching transaction data summary...

/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2016719537.py:194: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cb_df = pd.read_sql(cb_query, get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2004360204.py:74: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(response_code_query, con=get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/3607359053.py:100: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  card_verification_df = pd.read_sql(query, con=get_db_conn())

Final comprehensive prompt for analysis:
Agent result:
{'merchant_name': 'CANEX.CA HPS          OTTAWA       000CA', 'risk_level': 'high', 'summary': 'This merchant exhibits strong card-testing patterns with a high number of failed or canceled transactions relative to total attempts, high rates of response codes 14 and 87, many no 3DS/no CVV attempts, and a short transaction history. 33 failed/canceled transactions occurred in t1d, with up to 33 unique users, and a high proportion of failed attempts are linked to no-3DS/no-CVV, virtual, and specific BIN cards. Recent daily code 87 rates have ranged from 22%–26%, while t1d period shows 12 code 14 and 4 code 87 events. There are no active chargebacks, but the signals indicate strong card-validation abuse.', 'suspicious_signals': 'High count of code 14 (12 in t1d) and code 87 (4 in t1d, 15 ytd) responses, both indicative of card testing/validation\nAll (t1d=1, t1w=5, ytd=7) authorized transactions are no-3ds/no-cvv, showing lack of expected authentication\nVery high failed/canceled volume (33 in t1d, 62 in t1w, 80 in ytd) with low successful authorizations, indicating mass attempts\nHeavy use of virtual cards and specific BINs with no 3DS/no CVV (15 in t1d, 48 ytd)\nShort transaction history with sudden volume increase\nHigh code 51 (14 in t1d, 41 ytd) with all as no 3DS/no CVV', 'recommendation': 'BLOCK', 'confidence': 0.95}
Finished analyzing merchant: CANEX.CA HPS          OTTAWA       000CA .....



Analyzing merchant: Nova Wave Trading FZLLRas Al Khaima000AE | Blocked at: 2026-03-27 07:05:52
Fetching transaction data summary...

/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2016719537.py:194: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cb_df = pd.read_sql(cb_query, get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2004360204.py:74: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(response_code_query, con=get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/3607359053.py:100: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  card_verification_df = pd.read_sql(query, con=get_db_conn())

Final comprehensive prompt for analysis:
Agent result:
{'merchant_name': 'Nova Wave Trading FZLLRas Al Khaima000AE', 'risk_level': 'medium', 'summary': 'The merchant exhibited a very recent and sudden spike in activity with all transactions occurring in a tight recent window (first_tx_date and last_tx_date within hours), showing 22 total failed/canceled transactions highly concentrated on no-3DS/no-CVV attempts, split between only 16 unique users. However, there are no confirmed chargebacks, and no supporting response code or card-verification anomaly data to further confirm card testing or fraud. The suspicious signals suggest caution, but the lack of direct evidence of fraudulent intent or card testing means the case is not strong enough for immediate block.', 'suspicious_signals': "Recent merchant activity: all transactions occurred within a few hours\nHigh transaction failure/cancel count: 22 failed/canceled attempts\nAll failed/canceled transactions are no-3DS/no-CVV\n16 unique users for 22 attempts indicates some concentration\nMajority of product type is CREDIT_5401_BIN (18 out of 22 attempts)\nBlocked previously for 'Card Verifications'", 'recommendation': 'SCALE TO HUMAN INTERVENTION', 'confidence': 0.65}
Finished analyzing merchant: Nova Wave Trading FZLLRas Al Khaima000AE .....



Analyzing merchant: WARRANTY PURCHASE     LOUISVILLE   KY US | Blocked at: 2026-03-26 20:05:46
Fetching transaction data summary...

/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2016719537.py:194: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cb_df = pd.read_sql(cb_query, get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2004360204.py:74: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(response_code_query, con=get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/3607359053.py:100: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  card_verification_df = pd.read_sql(query, con=get_db_conn())

Final comprehensive prompt for analysis:
Agent result:
{'merchant_name': 'WARRANTY PURCHASE     LOUISVILLE   KY US', 'risk_level': 'high', 'summary': 'The merchant displays classic card-testing behavior: an extremely high and increasing concentration of response codes 14 (invalid card number) and 87 (CVV incorrect/no CVV), accounting for 46.94% and 24.49% of transactions respectively on 2026-03-25, with massive spikes compared to previous days. Approved transactions are almost non-existent, with nearly all activity resulting in failure/cancel states and only 1 authorized/settled transaction vs 22 failed/canceled on t1d. Chargebacks exist for two separate users, both on virtual cards with no CVV and unknown 3DS, indicating actual financial losses and confirming user complaints. Most activity is on virtual cards and is unauthenticated (no CVV, no 3DS), supporting the card-testing interpretation. The risk signals are strong, consistent, and escalating, with virtually no signs of legitimate user activity.', 'suspicious_signals': 'Response code 14 (invalid card number) at 46.94% of recent volume, increasing 1280% vs previous day\nResponse code 87 (CVV incorrect/missing) at 24.49% of recent volume, increasing 800% vs previous day\nOnly 1 authorized/settled transaction vs 22 failed/canceled on t1d\nRecent chargebacks from two unique users, all with virtual cards, no CVV, unknown 3DS\nHigh failed/canceled to approved volume ratio\nMost transactions unauthenticated (no CVV, no 3DS)\nActivity strongly concentrated in card-testing loss patterns\nRepeated, escalating code 14/87 in transaction history', 'recommendation': 'BLOCK', 'confidence': 0.99}
Finished analyzing merchant: WARRANTY PURCHASE     LOUISVILLE   KY US .....



Analyzing merchant: MAKRAM HANNA FASHION DDubai        000AE | Blocked at: 2026-03-25 19:07:02
Fetching transaction data summary...

/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2016719537.py:194: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cb_df = pd.read_sql(cb_query, get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2004360204.py:74: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(response_code_query, con=get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/3607359053.py:100: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  card_verification_df = pd.read_sql(query, con=get_db_conn())

Final comprehensive prompt for analysis:
Agent result:
{'merchant_name': 'MAKRAM HANNA FASHION DDubai        000AE', 'risk_level': 'high', 'summary': 'This merchant shows a clear pattern of abuse with 54 failed/canceled transactions and only 8 authorized in its very first 45 minutes of transactional activity, all occurring without 3DS or CVV. There are 8 chargebacks from just 2 users, concentrated in a single product and card type, with no-cvv and unknown 3DS status, indicating strong card-testing or validation-fraud behavior. There is no legitimate history prior to the incident. Despite the lack of granular response code data, the failed/canceled transaction volume and immediate chargeback pattern provide strong evidence of high risk.', 'suspicious_signals': 'All activity occurred in less than an hour since first_tx_date, suggesting sudden onset.\n54 failed/canceled transactions to just 8 authorized, extremely high failed ratio.\nAll attempts (62) did not use 3DS or CVV; 44 physical, 18 virtual cards.\n8 chargebacks reported in <1h, affecting 2 users, all with no CVV and unknown 3DS.\nAll chargebacks involved physical cards and a single BIN/product type.', 'recommendation': 'BLOCK', 'confidence': 0.98}
Finished analyzing merchant: MAKRAM HANNA FASHION DDubai        000AE .....



Analyzing merchant: ALZDJALY FOR PERFUMES Dubai        000AE | Blocked at: 2026-03-22 10:06:41
Fetching transaction data summary...

/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2016719537.py:194: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cb_df = pd.read_sql(cb_query, get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2004360204.py:74: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(response_code_query, con=get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/3607359053.py:100: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  card_verification_df = pd.read_sql(query, con=get_db_conn())

Final comprehensive prompt for analysis:
Agent result:
{'merchant_name': 'ALZDJALY FOR PERFUMES Dubai        000AE', 'risk_level': 'high', 'summary': 'This merchant shows a strong pattern of suspicious activity occurring within a very short window: it is new with all activity on the same day, 17 failed/canceled transactions vs only 1 authorized, and all failures correspond to response code 51 (insufficient funds) with no 3DS and no CVV. There is also a chargeback on a virtual card (no CVV, UNKNOWN 3DS), which further elevates the risk. The failed transaction concentration, rapid velocity, and chargeback all indicate likely card-testing or fraudulent behavior.', 'suspicious_signals': 'All transaction history occurred within ~1 hour of merchant creation (new merchant, high velocity)\n17 failed/canceled attempts vs only 1 authorized transaction\nAll failed transactions were no CVV and no 3DS\nBoth physical and virtual cards were used, with a large share of failed attempts on virtual cards\nChargeback within the first day on a no CVV, virtual card transaction\nHigh concentration of failed attempts (cnt_cr_51 = 17), suggesting aggressive testing/abuse\nNo evidence of legitimate distributed user activity', 'recommendation': 'BLOCK', 'confidence': 0.98}
Finished analyzing merchant: ALZDJALY FOR PERFUMES Dubai        000AE .....



Analyzing merchant: MAXFY                 MILDENHALL   ENGGB | Blocked at: 2026-03-14 01:27:11
Fetching transaction data summary...

/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2016719537.py:194: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cb_df = pd.read_sql(cb_query, get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2004360204.py:74: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(response_code_query, con=get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/3607359053.py:100: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  card_verification_df = pd.read_sql(query, con=get_db_conn())

Final comprehensive prompt for analysis:
Agent result:
{'merchant_name': 'MAXFY                 MILDENHALL   ENGGB', 'risk_level': 'high', 'summary': 'This merchant exhibits strong and sustained fraudulent patterns: a very high and rising incidence of code 87 (incorrect CVV) responses, repeated over multiple dates with spikes up to 30% of daily volume and increasing trends; extremely high chargeback rates (63 ytd, 39 in the last month, 8 in the last week) and chargebacks distributed across many unique users and different card/product types; plus a significant volume of failed/canceled transactions alongside authorizations. The spread of chargebacks and repeated response-code 87 spikes indicate ongoing card-testing or card-abuse behaviors. There is no evidence contradicting these findings, and no recent normal card verification activity to explain the risk.', 'suspicious_signals': 'Code 87 (CVV incorrect) repeatedly constitutes 14%-30% of daily transaction volume with increasing trends (e.g., 8/26 txs on 2026-03-11, up 300% vs prior day)\n63 chargebacks year-to-date, 39 in last month, 8 in last week, involving 40 unique users—very high and abnormal for merchant volume\nChargebacks occur across both physical and virtual card types as well as multiple product bins, indicating systemic abuse\n122 failed/canceled txs ytd, 28 in last week—substantial relative to authorizations\nNo sign of recent legitimate volume surge or explanation for anomalies', 'recommendation': 'BLOCK', 'confidence': 0.98}
Finished analyzing merchant: MAXFY                 MILDENHALL   ENGGB .....



Analyzing merchant: KCPBUSCLAS           CIUDAD DE MEX001MX | Blocked at: 2026-03-14 01:01:33
Fetching transaction data summary...

/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2016719537.py:194: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cb_df = pd.read_sql(cb_query, get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2004360204.py:74: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(response_code_query, con=get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/3607359053.py:100: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  card_verification_df = pd.read_sql(query, con=get_db_conn())

Final comprehensive prompt for analysis:
Agent result:
{'merchant_name': 'KCPBUSCLAS           CIUDAD DE MEX001MX', 'risk_level': 'high', 'summary': "The merchant has 21 chargebacks in the last month/ytd, all associated with 'no cvv' transactions and unconfirmed 3DS status, spread across 21 unique users. No transactional nor response code volume is available, but the chargeback pattern with 'no cvv' and 'UNKNOWN' 3DS indicates abusive or card-testing behavior, especially given all chargebacks involve cards from the same CREDIT_5456_BIN. This risk persists even without documented spikes in card verifications in the last hour, as the chargebacks alone are a strong signal of abuse.", 'suspicious_signals': "21 chargebacks in last month/ytd (all with 'no cvv')\nChargebacks across 21 unique users\nChargebacks only on CREDIT_5456_BIN\nNo 3DS or CVV present in high-risk transactions\nNo normal transaction or approval evidence", 'recommendation': 'BLOCK', 'confidence': 0.95}
Finished analyzing merchant: KCPBUSCLAS           CIUDAD DE MEX001MX .....



Analyzing merchant: KCPBSK               CIUDAD DE MEX001MX | Blocked at: 2026-03-14 00:57:51
Fetching transaction data summary...

/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2016719537.py:194: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cb_df = pd.read_sql(cb_query, get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2004360204.py:74: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(response_code_query, con=get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/3607359053.py:100: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  card_verification_df = pd.read_sql(query, con=get_db_conn())

Final comprehensive prompt for analysis:
Agent result:
{'merchant_name': 'KCPBSK               CIUDAD DE MEX001MX', 'risk_level': 'high', 'summary': "The merchant exhibits a very high volume of chargebacks concentrated over a short period, all associated with 'no cvv' and 'UNKNOWN' 3DS status, and affecting both physical and virtual cards under the same credit BIN. There is no evidence of legitimate transactions or benign response code patterns, and the merchant was previously blocked for card verifications. Despite the absence of new card-verification or response-code alerts in the last hour, the clear chargeback and authentication-abuse pattern is highly indicative of fraud or card-testing.", 'suspicious_signals': "264 chargebacks in past month, 397 YTD\nAll chargebacks are 'no cvv' and 'UNKNOWN' 3DS status\nChargebacks affect both physical and virtual cards\nAll chargebacks concentrate on CREDIT_5456_BIN product type\nPreviously blocked for card verifications\nNo legitimate transaction or response code history provided", 'recommendation': 'BLOCK', 'confidence': 0.95}
Finished analyzing merchant: KCPBSK               CIUDAD DE MEX001MX .....



Analyzing merchant: ATLAS EXCHANGE LIMITEDLusaka       000KE | Blocked at: 2026-03-04 06:02:51
Fetching transaction data summary...

/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2016719537.py:194: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cb_df = pd.read_sql(cb_query, get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2004360204.py:74: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(response_code_query, con=get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/3607359053.py:100: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  card_verification_df = pd.read_sql(query, con=get_db_conn())

Final comprehensive prompt for analysis:
Agent result:
{'merchant_name': 'ATLAS EXCHANGE LIMITEDLusaka       000KE', 'risk_level': 'medium', 'summary': 'This merchant shows very low transaction volume with only 5 transactions YTD and 2 in the past week, from a small user base and with almost all attempts authorized. However, the existence of 2 chargebacks involving 2 unique users in the last month—representing a high percentage relative to the overall low transaction count—raises concern. There are no recent abnormal card verifications or response-code spikes, and failed/canceled transaction counts are negligible. The chargebacks are notable, but there is insufficient evidence for ongoing or coordinated card testing or mass abuse.', 'suspicious_signals': 'Very low transaction volume (5 YTD, 2 in last week, only 6 unique users YTD)\n2 chargebacks from 2 users in the last month, both on the same card and product type\nNo abnormal card verification activity in the last hour\nNo evidence of response-code anomalies (no data)\nNegligible failed/canceled counts, most transactions authorized', 'recommendation': 'SCALE TO HUMAN INTERVENTION', 'confidence': 0.65}
Finished analyzing merchant: ATLAS EXCHANGE LIMITEDLusaka       000KE .....



Analyzing merchant: CS ONLINESHOP         BOSTON       MA US | Blocked at: 2026-03-02 08:07:19
Fetching transaction data summary...

/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2016719537.py:194: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cb_df = pd.read_sql(cb_query, get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2004360204.py:74: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(response_code_query, con=get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/3607359053.py:100: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  card_verification_df = pd.read_sql(query, con=get_db_conn())

Final comprehensive prompt for analysis:
Agent result:
{'merchant_name': 'CS ONLINESHOP         BOSTON       MA US', 'risk_level': 'high', 'summary': 'This merchant shows a textbook case of fresh card-testing activity: all transactional history started within the same brief time window (t1d/t1w/ytd are identical), 49 response code 14 (invalid card number) and 9 response code 87 (incorrect/absent CVV) within just 14 minutes, and only 10 unique users. There are also 11 failed/canceled transactions and no evidence of legitimate transactional spread or long history. The pattern is highly concentrated and almost entirely consists of verification failures with risky response codes, fitting a card-testing scenario.', 'suspicious_signals': 'All transaction activity began and ended within a 14-minute window\ncnt_cr_14 (Invalid card number) = 49 in 14 minutes\ncnt_cr_87 (CVV incorrect/absent) = 9 in 14 minutes\nOnly 10 unique users for all failed attempts\n11 failed/canceled states, no evidence of successful authorizations\nNo card verification anomaly in most recent 1 hour, but full activity window predates this', 'recommendation': 'BLOCK', 'confidence': 0.95}
Finished analyzing merchant: CS ONLINESHOP         BOSTON       MA US .....



Analyzing merchant: AARON ABKE 4D UNIVERS+14082066220 TX US | Blocked at: 2026-02-24 23:45:38
Fetching transaction data summary...

/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2016719537.py:194: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cb_df = pd.read_sql(cb_query, get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2004360204.py:74: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(response_code_query, con=get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/3607359053.py:100: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  card_verification_df = pd.read_sql(query, con=get_db_conn())

Final comprehensive prompt for analysis:
Agent result:
{'merchant_name': 'AARON ABKE 4D UNIVERS+14082066220 TX US', 'risk_level': 'low', 'summary': 'There are no strong indicators of fraud or card testing: no transactional data, no chargebacks, no abnormal response code distribution, and no recent card-verification anomalies matched the configured thresholds. The absence of negative evidence means there is no support for continuing or reinstating a block.', 'suspicious_signals': 'No transactional data available\nNo chargebacks reported in any time frame\nNo response code data available\nNo recent card verification anomaly matched the alert thresholds', 'recommendation': 'NOT BLOCK', 'confidence': 0.9}
Finished analyzing merchant: AARON ABKE 4D UNIVERS+14082066220 TX US .....



Analyzing merchant: EASY MONEY CHEAP RIDESNEWPORT      OR US | Blocked at: 2026-02-23 00:07:29
Fetching transaction data summary...

/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2016719537.py:194: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cb_df = pd.read_sql(cb_query, get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2004360204.py:74: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(response_code_query, con=get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/3607359053.py:100: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  card_verification_df = pd.read_sql(query, con=get_db_conn())

Final comprehensive prompt for analysis:
Agent result:
{'merchant_name': 'EASY MONEY CHEAP RIDESNEWPORT      OR US', 'risk_level': 'high', 'summary': "The merchant exhibits strong card-testing and fraud signals: sustained and increasing high rates of code 87 (up to 44% of transaction volume, with recent spikes over 900% in daily growth), repeated and recent chargebacks (6 in the last week across 6 users, 9 YTD), all chargebacks on 'no cvv' transactions, and a very high concentration of non-authenticated transaction attempts. Transaction attempts are focused on 'no CVV/no 3DS', with failed/canceled states, and limited histories. These combined data points show clear large-scale abuse and card-testing behavior.", 'suspicious_signals': "Extremely high recent volume of code 87 declines (44% of total transactions on last measured day, with 966% daily increase)\nSustained code 87 activity across multiple days with increasing trends\nAll recent chargebacks (6 in last week, 9 YTD) originated from 'no cvv' transactions\nChargebacks distributed across multiple users and both PHYSICAL and VIRTUAL cards\nHigh failed/canceled transaction rates\nHigh concentration of non-authenticated (no CVV/no 3DS) transactions\nAbnormal transaction activity began recently, with many failed attempts and little prior history", 'recommendation': 'BLOCK', 'confidence': 0.98}
Finished analyzing merchant: EASY MONEY CHEAP RIDESNEWPORT      OR US .....



Analyzing merchant: VOGO GLOBAL           RALEIGH      NC US | Blocked at: 2026-02-23 00:07:28
Fetching transaction data summary...

/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2016719537.py:194: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cb_df = pd.read_sql(cb_query, get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2004360204.py:74: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(response_code_query, con=get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/3607359053.py:100: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  card_verification_df = pd.read_sql(query, con=get_db_conn())

Final comprehensive prompt for analysis:
Agent result:
{'merchant_name': 'VOGO GLOBAL           RALEIGH      NC US', 'risk_level': 'high', 'summary': 'The merchant shows strong signals of card testing and fraud: nearly half of all transactions (46.27%) received response code 87 (CVV error), which is a hallmark of card-testing attacks. Transaction activity started suddenly on 2026-02-22, with no historical baseline, and all 16 users tried cards with no 3DS or CVV, suggesting a focus on weak card-entry channels. There are also 2 chargebacks from 2 unique users, which is significant for such a small, short-lived transaction history. These coordinated, abnormal signals together indicate high risk of abuse and card testing.', 'suspicious_signals': '31 out of 67 transactions (46.27%) had response code 87 (CVV error)\nAll 16 unique users over the week used cards with no 3DS and no CVV\nFirst transaction less than 1 day before block, indicating abrupt activity onset\n2 chargebacks from 2 unique users within only one week and small transaction base\nAll chargeback transactions used PHYSICAL cards, CREDIT_5401_BIN, no CVV, and unknown 3DS\nHigh ratio of failed/canceled transactions to successful ones: 11 failed/canceled vs 5 authorized/settled', 'recommendation': 'BLOCK', 'confidence': 0.98}
Finished analyzing merchant: VOGO GLOBAL           RALEIGH      NC US .....



Analyzing merchant: OMNIVISIX             BAD ISCHL    AT AT | Blocked at: 2026-02-23 00:07:28
Fetching transaction data summary...

/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2016719537.py:194: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cb_df = pd.read_sql(cb_query, get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2004360204.py:74: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(response_code_query, con=get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/3607359053.py:100: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  card_verification_df = pd.read_sql(query, con=get_db_conn())

Final comprehensive prompt for analysis:
Agent result:
{'merchant_name': 'OMNIVISIX             BAD ISCHL    AT AT', 'risk_level': 'high', 'summary': 'The merchant demonstrates clear and consistent high-risk behavior with strong evidence of card-testing or fraudulent activity: extremely high percentage of code 87 (up to 54% of daily volume), rising response code 14 activity, large counts of failed/canceled transactions, and an abnormal chargeback pattern with 19 chargebacks YTD from 19 unique users, all on PHYSICAL CREDIT_5401_BIN cards with no CVV and unknown 3DS, over a short transactional history.', 'suspicious_signals': 'Code 87 spikes: 54% (33/61) of 2026-02-22 transactions, consistently high in previous days.\nCode 14 present and increasing (3/93, 3.23% of 2026-02-21, up 200% day-on-day).\nChargebacks: 19 reported YTD, all unique users, all PHYSICAL, CREDIT_5401_BIN, no CVV, unknown 3DS.\nFailed/canceled transactions high: 71 YTD vs 36 authorized/settled YTD.\nNo CVV/no 3DS on nearly all activity.\nShort transaction history, recent activity spikes.\nChargebacks distributed across multiple users/cards, not concentrated to one.', 'recommendation': 'BLOCK', 'confidence': 0.98}
Finished analyzing merchant: OMNIVISIX             BAD ISCHL    AT AT .....



Analyzing merchant: WONDERFUL             BLOOMFIELD   NJ US | Blocked at: 2026-02-21 15:06:06
Fetching transaction data summary...

/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2016719537.py:194: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cb_df = pd.read_sql(cb_query, get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2004360204.py:74: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(response_code_query, con=get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/3607359053.py:100: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  card_verification_df = pd.read_sql(query, con=get_db_conn())

Final comprehensive prompt for analysis:
Agent result:
{'merchant_name': 'WONDERFUL             BLOOMFIELD   NJ US', 'risk_level': 'high', 'summary': 'The merchant has a very short transaction history (first tx on 2026-02-16), high counts of declined card verifications (47 with code 87 and 9 with code 14 out of a total of roughly 81 transactions), all with no 3DS or CVV, and an elevated failed/canceled count. Critically, there are 6 chargebacks from 6 unique users, focused on physical cards, a single credit BIN, and all involving no CVV and no 3DS. These patterns are classic indicators of card-testing or card-validation fraud, supported by rapid chargebacks and concentrated payment parameters.', 'suspicious_signals': 'High number of code 87 card-verification declines (47) and code 14 declines (9) in a small time window\nAll card verifications and failed transactions lack 3DS and CVV\nFast onset: all activity since 2026-02-16, past 5 days only\n6 chargebacks from 6 unique users, focused on physical/credit cards with no CVV/3DS\nFailed/canceled volume high, nearly double authorized/settled volume\nPatterns consistent with card-testing/validation abuse', 'recommendation': 'BLOCK', 'confidence': 0.98}
Finished analyzing merchant: WONDERFUL             BLOOMFIELD   NJ US .....



Analyzing merchant: PLANTARWEB BY IMT SRL MILANO       MI IT | Blocked at: 2026-02-17 17:09:44
Fetching transaction data summary...

/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2016719537.py:194: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cb_df = pd.read_sql(cb_query, get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2004360204.py:74: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(response_code_query, con=get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/3607359053.py:100: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  card_verification_df = pd.read_sql(query, con=get_db_conn())

Final comprehensive prompt for analysis:
Agent result:
{'merchant_name': 'PLANTARWEB BY IMT SRL MILANO       MI IT', 'risk_level': 'high', 'summary': "The merchant shows strong evidence of card-testing or card-validation abuse. There are 15 transactions with response code 87 (CVV incorrect or missing), all within a very short period and from a single unique user, with all activity concentrated on the first and only day of processing. Furthermore, one chargeback is already confirmed, associated with a virtual card, no CVV, no 3DS, and credit product, indicating early and concrete financial loss to customers. No genuine customer activity or broader user/card diversity is present, and the merchant's abrupt activity start and immediate chargeback reinforce the high-risk pattern. The lack of response-code details does not change the risk, as the available signals are decisive.", 'suspicious_signals': "15 transactions with response code 87 (CVV incorrect/missing) in a single day\nAll activity concentrated on first day of merchant's history\nOnly 1 unique user involved in all activity\nConfirmed chargeback within the first day, virtual card, no CVV, no 3DS\nNo evidence of normal, distributed customer activity\nNo follow-up authorized/settled volume of note", 'recommendation': 'BLOCK', 'confidence': 0.98}
Finished analyzing merchant: PLANTARWEB BY IMT SRL MILANO       MI IT .....



Analyzing merchant: CBI BALFOUR           AUSTIN       TX US | Blocked at: 2026-02-15 23:07:03
Fetching transaction data summary...

/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2016719537.py:194: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cb_df = pd.read_sql(cb_query, get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2004360204.py:74: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(response_code_query, con=get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/3607359053.py:100: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  card_verification_df = pd.read_sql(query, con=get_db_conn())

Final comprehensive prompt for analysis:
Agent result:
{'merchant_name': 'CBI BALFOUR           AUSTIN       TX US', 'risk_level': 'high', 'summary': 'The merchant displays persistent and abnormal high rates of response codes 14 and 87 over multiple dates, with recent card verification activity, despite no formal card verification anomaly triggered in the last hour. Historical transactions show repeated and concentrated failed authorization attempts—100% code 87 or 14 on multiple days—indicative of card testing behavior. There are no chargeback records yet, but the velocity and pattern of failed transactions using testing-related codes create a clear card-testing/validation abuse risk.', 'suspicious_signals': 'Multiple recent days with 100% of transactions either code 14 or code 87\nConsistent high volume of failed transactions with card testing codes (14/87)\nSudden activity after little prior history, suggesting recent abuse onset\nNo normal charged activity or legitimate authorizations, only testing declines', 'recommendation': 'BLOCK', 'confidence': 0.96}
Finished analyzing merchant: CBI BALFOUR           AUSTIN       TX US .....



Analyzing merchant: BIOLONGEVITY          LAS VEGAS    NV US | Blocked at: 2026-02-15 01:07:20
Fetching transaction data summary...

/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2016719537.py:194: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cb_df = pd.read_sql(cb_query, get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2004360204.py:74: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(response_code_query, con=get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/3607359053.py:100: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  card_verification_df = pd.read_sql(query, con=get_db_conn())

Final comprehensive prompt for analysis:
Agent result:
{'merchant_name': 'BIOLONGEVITY          LAS VEGAS    NV US', 'risk_level': 'high', 'summary': 'The merchant displays a strong card-testing pattern: sudden, recent transaction activity with half of all attempts resulting in code 14 (invalid card number) and half in code 87 (CVV issues), with both together making up 100% of all recent transactions, and activity began only a few days ago. Volume spiked sharply (800% increase), and there are no legitimate approvals and no historical transaction base, with card-verification anomalies at threshold. There is no chargeback evidence yet, but the aggregation of failed authorization attempts via critical response codes is sufficient to confirm abuse.', 'suspicious_signals': 'Extreme concentration of high-risk response codes (14 and 87), representing 100% of recent transactions\n800% surge in code 14 versus prior day\nVery recent first transaction; all t1w and ytd metrics align, suggesting new merchant\nNo history of approved or normal transactions, only failed attempts\nNo chargebacks, but absence likely due to short operational window\nNo card verification anomalies in the last hour, but full activity still fits card testing narrative', 'recommendation': 'BLOCK', 'confidence': 0.95}
Finished analyzing merchant: BIOLONGEVITY          LAS VEGAS    NV US .....



Analyzing merchant: B2 SUPERVALUE CHECKS NEW BRAUNFELSTX US | Blocked at: 2026-02-11 23:07:00
Fetching transaction data summary...

/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2016719537.py:194: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cb_df = pd.read_sql(cb_query, get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2004360204.py:74: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(response_code_query, con=get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/3607359053.py:100: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  card_verification_df = pd.read_sql(query, con=get_db_conn())

Final comprehensive prompt for analysis:
Agent result:
{'merchant_name': 'B2 SUPERVALUE CHECKS NEW BRAUNFELSTX US', 'risk_level': 'low', 'summary': 'There is no transactional summary, no evidence of chargebacks or unrecognized charges, no available response code analysis, and no recent card verification anomalies matched the configured thresholds. The only signal is that the merchant was previously blocked due to card verifications, but the current data does not show renewed risk or abnormality.', 'suspicious_signals': 'Merchant was previously blocked for card verifications', 'recommendation': 'NOT BLOCK', 'confidence': 0.3}
Finished analyzing merchant: B2 SUPERVALUE CHECKS NEW BRAUNFELSTX US .....



Analyzing merchant: STARCROWN, INC.       NAHASHI      okiJP | Blocked at: 2026-02-10 15:05:40
Fetching transaction data summary...

/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2016719537.py:194: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cb_df = pd.read_sql(cb_query, get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2004360204.py:74: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(response_code_query, con=get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/3607359053.py:100: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  card_verification_df = pd.read_sql(query, con=get_db_conn())

Final comprehensive prompt for analysis:
Agent result:
{'merchant_name': 'STARCROWN, INC.       NAHASHI      okiJP', 'risk_level': 'high', 'summary': "The merchant exhibits strong signs of card testing: nearly all transaction attempts are failed with high concentrations of response codes 14 (15 attempts) and 87 (4 attempts), extremely low unique user and card counts, nearly all activity occurred in a single, very recent window, and no chargeback cases are present but this is likely due to the merchant's novelty. Only one authorized transaction exists. The response code pattern, failed/canceled state, and concentration of no-3DS/no-CVV activity strongly support a high-risk assessment consistent with card testing or validation abuse.", 'suspicious_signals': 'High count of response code 14 (15 of 23 total attempts)\nElevated response code 87 (4 occurrences)\nLow unique user count (2 to 3) versus total attempts\nNearly all activity concentrated in a single day and hour\nFirst and last transaction dates nearly identical (bursty, new activity)\nMost transactions were no-3DS and no-CVV\nOnly 1 authorized/settled transaction, suggesting most transactions are test attempts', 'recommendation': 'BLOCK', 'confidence': 0.95}
Finished analyzing merchant: STARCROWN, INC.       NAHASHI      okiJP .....



Analyzing merchant: MOOVTOO.COM           PARIS        IleFR | Blocked at: 2026-02-07 19:05:43
Fetching transaction data summary...

/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2016719537.py:194: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cb_df = pd.read_sql(cb_query, get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2004360204.py:74: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(response_code_query, con=get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/3607359053.py:100: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  card_verification_df = pd.read_sql(query, con=get_db_conn())

Final comprehensive prompt for analysis:
Agent result:
{'merchant_name': 'MOOVTOO.COM           PARIS        IleFR', 'risk_level': 'high', 'summary': 'MOOVTOO.COM shows strong evidence of card-testing behavior, including a high volume of response codes 14 and 87 (53 card verification errors out of a small number of total transactions), a very recent startup/velocity pattern, little or no prior history, and 2 chargeback cases from 2 unique users within the first week of activity. Almost all failed transactions were made without 3DS or CVV, and the same BIN, card type, and lack of authentication are shown in both chargeback and transaction attempts. Authorized/settled volume is extremely low relative to failed/canceled and declined attempts, reinforcing card-testing and fraud concerns.', 'suspicious_signals': 'High cnt_cr_14 and cnt_cr_87 (21 and 32, respectively) in only a few days (most volume since first_tx_date: 2026-02-07)\nAll (or nearly all) failed/canceled transactions and chargebacks have no 3DS or CVV\nTransaction pattern is very recent, with t1d, t1w, and ytd nearly identical, indicating brand new or just-activated merchant\n2 chargebacks from 2 users and same bin/card type within a single week (very early in merchant life)\nLow number of authorized/settled transactions (4/5 total) compared to failed attempts\nChargebacks are specifically tied to no-cvv, no-3ds transactions, matching attempted abuse patterns\nCnt_cr_51 also high (18-20 in the same period), consistent with failed card attempts', 'recommendation': 'BLOCK', 'confidence': 0.98}
Finished analyzing merchant: MOOVTOO.COM           PARIS        IleFR .....



Analyzing merchant: STEPINTO GROUP LTD    KINGTON      LNDGB | Blocked at: 2026-02-07 19:05:43
Fetching transaction data summary...

/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2016719537.py:194: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cb_df = pd.read_sql(cb_query, get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2004360204.py:74: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(response_code_query, con=get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/3607359053.py:100: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  card_verification_df = pd.read_sql(query, con=get_db_conn())

Final comprehensive prompt for analysis:
Agent result:
{'merchant_name': 'STEPINTO GROUP LTD    KINGTON      LNDGB', 'risk_level': 'high', 'summary': 'This merchant exhibits strong card-testing signals, including high recent velocity with a majority of card verifications lacking CVV/3DS, a pronounced concentration of risky response codes (87 and 14), a high failed/canceled rate, and 9 chargebacks from 9 unique users all associated with physical cards and no CVV within a single week. The activity started very recently and is heavily skewed toward unauthorized or failed attempts, corroborating abusive behavior.', 'suspicious_signals': 'Very recent first activity (first transaction t1w=2026-02-06)\nHigh failed/canceled transactions relative to authorizations (t1d: failed/canceled=33, authorized/settled=14)\nHigh counts of response codes 87 (49 in t1d), 14 (30 in t1d), 51 (33 in t1d)\nAlmost all verifications without CVV or 3DS (cnt_cr_0_no_3ds_no_cvv t1d=14, cnt_cr_0_has_cvv_or_has_3ds t1d=0)\nChargebacks: 9 chargebacks in a week across 9 users, all with no CVV and physical cards\nResponse code analysis: 33% of transactions on one date had code 87, with no historical baseline\nAuthorizations and verifications tightly clustered with no historical volume', 'recommendation': 'BLOCK', 'confidence': 0.98}
Finished analyzing merchant: STEPINTO GROUP LTD    KINGTON      LNDGB .....



Analyzing merchant: TRIVIVA LLC           ROUND ROCK   TX US | Blocked at: 2026-02-07 19:05:42
Fetching transaction data summary...

/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2016719537.py:194: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cb_df = pd.read_sql(cb_query, get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2004360204.py:74: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(response_code_query, con=get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/3607359053.py:100: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  card_verification_df = pd.read_sql(query, con=get_db_conn())

Final comprehensive prompt for analysis:
Agent result:
{'merchant_name': 'TRIVIVA LLC           ROUND ROCK   TX US', 'risk_level': 'high', 'summary': 'This merchant exhibited extremely suspicious transactional behavior within a single day of activity, including a high number of failed card verifications (codes 14, 87, and 51), all occurring without CVV or 3DS, and generated 4 unique-user chargebacks in its brief active window. The consolidation of all transactional activity within one day, high failed/canceled rates compared to settled (22 failed vs 7 settled), and every chargeback showing no CVV and PHYSICAL card type, strongly indicate card testing and fraud.', 'suspicious_signals': 'All activity occurred within a single day (t1d = t1w = ytd = 2026-02-07)\nHigh failed/canceled versus authorized/settled ratio (22 failed vs 7 settled)\nAll card verifications (7) lacked 3DS and CVV\nHigh counts of card-testing codes: 14 (19), 87 (26), 51 (22), all within first day\nOnly 29 unique users for this entire burst, indicating low user/card spread\n4 unique chargebacks from 4 unique users, all PHYSICAL cards, no CVV, all within initial activity window\nNo legitimate transaction history prior to the flagged period', 'recommendation': 'BLOCK', 'confidence': 0.99}
Finished analyzing merchant: TRIVIVA LLC           ROUND ROCK   TX US .....



Analyzing merchant: P&C SHOP /SHIPPELLO   LAUDERDALE LAFL US | Blocked at: 2026-02-07 07:06:00
Fetching transaction data summary...

/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2016719537.py:194: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cb_df = pd.read_sql(cb_query, get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2004360204.py:74: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(response_code_query, con=get_db_conn())
/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/3607359053.py:100: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  card_verification_df = pd.read_sql(query, con=get_db_conn())

Final comprehensive prompt for analysis:
Agent result:
{'merchant_name': 'P&C SHOP /SHIPPELLO   LAUDERDALE LAFL US', 'risk_level': 'high', 'summary': 'This merchant demonstrates a clear card testing/card validation pattern with very recent and limited transaction history, a high count of response code 14 errors (invalid card numbers), significant failed and non-authenticated attempts, and markedly abnormal distribution of high-risk response codes. The proportion of failed or card-verification transactions to total activity is extremely high, and card activity is concentrated in a short window after a dormant period, all without chargeback evidence (which is common with new merchants).', 'suspicious_signals': 'Very recent surge in activity after little prior history (first tx t1d=2026-02-07, most activity same day)\ncnt_cr_14=23 (invalid card number), huge compared to only 3-5 authorized/settled txs\ncnt_cr_87=2-5, strong card testing indicator\nFailed/canceled transactions (t1d=4) comparable to authorized/settled (t1d=3)\nAll transactions lacking 3DS/CVV authentication\nHigh concentration of activity on PHYSICAL cards and single BIN (cnt_card_type_PHYSICAL_no_3ds_no_cvv: t1d=7, cnt_product_type_CREDIT_5401_BIN_no_3ds_no_cvv: t1d=7)\nLow unique user count (7 users in t1d, 8 in t1w)\n50% of transactions as code 87 on 2026-01-23 (from response code analysis)', 'recommendation': 'BLOCK', 'confidence': 0.95}
Finished analyzing merchant: P&C SHOP /SHIPPELLO   LAUDERDALE LAFL US .....



Analyzing merchant: SHIPPELLO             GARLAND      TX US | Blocked at: 2026-02-07 07:05:59
Fetching transaction data summary...

/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_14820/2016719537.py:194: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cb_df = pd.read_sql(cb_query, get_db_conn())

DatabaseError: Execution failed on sql:
        WITH tc_base AS (
            SELECT
                tc.*,
                COALESCE(
                    NULLIF(split_part(tc.transaction_id, 'PARABILIUM:', 2), ''),
                    tc.transaction_id
                ) AS omi_id_operacion_raw
            FROM ops_fraud.total_chargeback tc
            WHERE
                tc.merchant = 'SHIPPELLO             GARLAND      TX US'
                AND tc.trx_timestamp_mx < DATEADD(day, 1, DATE '2026-02-07')
        ),

        oimt_base AS (
            SELECT
                oimt.omi_id_operacion,
                oimt.c063,
                oimt.c032 AS adquirente
            FROM is_pii_parabilium.operation_iso_messages_temp oimt
            INNER JOIN tc_base tc
                ON oimt.omi_id_operacion = tc.omi_id_operacion_raw
        ),

        pin_verif AS (
            SELECT
                o.omi_id_operacion,
                '! ' || REGEXP_SUBSTR(o.c063, 'B300080[^!]*') AS B300080_value,
                SUBSTRING(B300080_value FROM 49 FOR 6) AS "8-CVMRSLTS",
                SUBSTRING("8-CVMRSLTS" FROM 1 FOR 2) AS byte_1_hex,
                CASE
                    WHEN byte_1_hex ~ '^[0-9A-Fa-f]2$'
                    THEN FROM_VARBYTE(from_hex(byte_1_hex), 'binary')
                    ELSE NULL
                END AS byte_1_bits,
                CASE
                    WHEN byte_1_bits IS NULL THEN NULL
                    WHEN SUBSTRING(byte_1_bits FROM 3 FOR 6) = '000000'
                        THEN 'Procesamiento de CVM fallido'
                    WHEN SUBSTRING(byte_1_bits FROM 3 FOR 6) = '000001'
                        THEN 'Verificacion de PIN en texto plano realizada por el chip de la tarjeta'
                    WHEN SUBSTRING(byte_1_bits FROM 3 FOR 6) = '000010'
                        THEN 'PIN cifrado verificado en linea'
                    WHEN SUBSTRING(byte_1_bits FROM 3 FOR 6) = '000011'
                        THEN 'Verificacion de PIN en texto plano realizada por el chip de la tarjeta y firma (papel)'
                    WHEN SUBSTRING(byte_1_bits FROM 3 FOR 6) = '000100'
                        THEN 'Verificacion de PIN cifrado realizada por el chip de la tarjeta'
                    WHEN SUBSTRING(byte_1_bits FROM 3 FOR 6) = '000101'
                        THEN 'Verificacion de PIN cifrado realizada por el chip de la tarjeta y firma (papel)'
                    WHEN SUBSTRING(byte_1_bits FROM 3 FOR 6) = '011110'
                        THEN 'Firma (papel)'
                    WHEN SUBSTRING(byte_1_bits FROM 3 FOR 6) = '011111'
                        THEN 'No se requiere CVM'
                    ELSE SUBSTRING(byte_1_bits FROM 3 FOR 6)
                END AS metodo_verificacion
            FROM oimt_base o
            WHERE o.c063 LIKE '%! B3%'
        ),

        three_ds AS (
            SELECT
                o.omi_id_operacion,
                o.c063,
                REGEXP_SUBSTR(o.c063, 'CE[0-9]5[^!]*') AS ce_token,
                CASE
                    WHEN REGEXP_SUBSTR(o.c063, 'CE[0-9]5[^!]*') IS NOT NULL
                        AND POSITION('01' IN REGEXP_SUBSTR(o.c063, 'CE[0-9]5[^!]*')) > 0
                    THEN SUBSTRING(
                        REGEXP_SUBSTR(o.c063, 'CE[0-9]5[^!]*')
                        FROM POSITION('01' IN REGEXP_SUBSTR(o.c063, 'CE[0-9]5[^!]*')) + 2
                        FOR 2
                    )
                    ELSE NULL
                END AS leading_indicator,
                CASE
                    WHEN REGEXP_SUBSTR(o.c063, 'CE[0-9]5[^!]*') IS NULL
                        THEN 'NO_3DS'
                    WHEN SUBSTRING(
                            REGEXP_SUBSTR(o.c063, 'CE[0-9]5[^!]*')
                            FROM POSITION('01' IN REGEXP_SUBSTR(o.c063, 'CE[0-9]5[^!]*')) + 2
                            FOR 2
                        ) IN ('kA','kB','kC','kE','kF','kJ','kR','kS','kG','kO','kP')
                        THEN '3DS_AUTHENTICATED'
                    WHEN SUBSTRING(
                            REGEXP_SUBSTR(o.c063, 'CE[0-9]5[^!]*')
                            FROM POSITION('01' IN REGEXP_SUBSTR(o.c063, 'CE[0-9]5[^!]*')) + 2
                            FOR 2
                        ) IN ('kN','kW','kU','kX')
                        THEN '3DS_NOT_AUTHENTICATED'
                    ELSE 'UNKNOWN'
                END AS three_ds_status,
                CASE
                    WHEN REGEXP_SUBSTR(o.c063, 'CE[0-9]5[^!]*') IS NULL
                        THEN 'NO_3DS'
                    WHEN SUBSTRING(
                            REGEXP_SUBSTR(o.c063, 'CE[0-9]5[^!]*')
                            FROM POSITION('01' IN REGEXP_SUBSTR(o.c063, 'CE[0-9]5[^!]*')) + 2
                            FOR 2
                        ) IN ('kA','kC','kE','kO')
                        THEN 'FRICTIONLESS'
                    WHEN SUBSTRING(
                            REGEXP_SUBSTR(o.c063, 'CE[0-9]5[^!]*')
                            FROM POSITION('01' IN REGEXP_SUBSTR(o.c063, 'CE[0-9]5[^!]*')) + 2
                            FOR 2
                        ) IN ('kB','kS','kG','kP')
                        THEN 'CHALLENGE'
                    WHEN SUBSTRING(
                            REGEXP_SUBSTR(o.c063, 'CE[0-9]5[^!]*')
                            FROM POSITION('01' IN REGEXP_SUBSTR(o.c063, 'CE[0-9]5[^!]*')) + 2
                            FOR 2
                        ) IN ('kN','kW','kU','kX')
                        THEN 'EXEMPT_OR_INFO'
                    ELSE 'UNKNOWN'
                END AS three_ds_flow
            FROM oimt_base o
        )

        SELECT
            tc.*,
            pv.metodo_verificacion AS metodo_identificacion,
            td.leading_indicator,
            td.three_ds_status,
            td.three_ds_flow,
            td.c063,
            o.sucursal AS afiliacion,
            o.terminal AS numero_terminal,
            ob.adquirente
        FROM tc_base tc
        LEFT JOIN pin_verif pv
            ON pv.omi_id_operacion = tc.omi_id_operacion_raw
        LEFT JOIN three_ds td
            ON td.omi_id_operacion = tc.omi_id_operacion_raw
        LEFT JOIN is_pii_parabilium.parabilium_transactions pt
            ON pt.id = tc.omi_id_operacion_raw
        LEFT JOIN is_pii_parabilium.operaciones o
            ON o.id_operacion = tc.omi_id_operacion_raw
        LEFT JOIN oimt_base ob
            ON ob.omi_id_operacion = tc.omi_id_operacion_raw

could not receive data from server: Operation timed out
SSL SYSCALL error: Operation timed out

unable to rollback

In [181]:
extra_result_df = pd.concat(
    [
        df.assign(merchant_name=merchant_name)
        for merchant_name, df in extra_merchant_result.items()
    ],
    ignore_index=True
)

In [180]:
extra_merchant_result["WWW.TECH-VAULT.COM    SINGAPORE       SG"]

,risk_level,summary,suspicious_signals,recommendation,confidence
0,high,Merchant WWW.TECH-VAULT.COM demonstrates clear...,High count of response code 87 (fraud/security...,BLOCK,0.95

In [88]:
blocked_df = pd.DataFrame(merchant_result.keys(), columns=["merchant"])

In [90]:
blocked_df["is_blocked"] = 0

In [109]:
blocked_df.iloc[-10, blocked_df.columns.get_loc("is_blocked")] = 1

In [110]:
blocked_df

                                   merchant  is_blocked
0  Smoke Club FL LLC     Orlando      FL US           1
1  Paul Stuart Inc       2126820320   NY US           1
2  M800 LIMITED          KOWLOON BAY  KowHK           1
3  NY POST DIGITAL MEMBERNEW YORK     NY US           1
4  COOK MEMORIAL PUBLIC  LIBERTYVILLE IL US           1
5  LUAN MEIRELLES DIAS PARIBEIRAO PRETSP BR           0
6  IONOS INC             CHESTERBROOK PA US           1
7  Hims and Hers Inc.    San FranciscoCA US           1
8  ELKWEDY PERFUMES AND GDubai        000AE           1
9  ELKWEDY FASHION DESIGNDubai        000AE           1

In [63]:
# testing pipeline

merchant = bl_merchants_to_test["merchant"].iloc[5]
blocked_date = str(bl_merchants_to_test["updated_at"].iloc[0])
# example test run for one merchant
print(f"Analyzing merchant: {merchant} | Blocked at: {blocked_date}")
print("Fetching transaction data summary...")

Analyzing merchant: NY POST DIGITAL MEMBERNEW YORK     NY US | Blocked at: 2026-04-23 16:09:02
Fetching transaction data summary...

In [112]:
# merchant summary
trx_summary_df = merchant_trx_summary(merchant=merchant, blocked_date=blocked_date)

In [113]:
cb_df = chargeback_merchant_summary(merchant_name=merchant, blocking_date=blocked_date)

/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_51320/2836818482.py:197: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cb_df = pd.read_sql(cb_query, get_db_conn())

In [114]:
cod_df = build_cod_risk_summary(merchant_to_block=merchant, block_date=blocked_date)

/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_51320/2004360204.py:74: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(response_code_query, con=get_db_conn())

In [115]:
cod_df

''

In [116]:
user_prompt = build_final_report(
    merchant=merchant,
    blocked_date=blocked_date,
    commerce_summary=trx_summary_df,
    chargebacks_summary=cb_df,
    cod_analysis_df=cod_df
)

In [119]:
result = await fraud_CV_agent(user_prompt)

RunResult:
- Last agent: Agent(name="Fraud Analyst", ...)
- Final output (FraudFinding):
    {
      "risk_level": "high",
      "summary": "The merchant ELKWEDY FASHION DESIGNDubai 000AE shows strong indications of abuse and possible card testing: extremely short and intense transaction window (first to last TX is just a few hours), very high proportion of failed/canceled transactions (50 vs just 14 settled), heavy concentration of activity among a small number of unique users, high numbers of chargebacks (12 from 1 user, all 'no CVV' and 'UNKNOWN' 3DS), and a notable number of code 14 'invalid card number' responses in a very brief period. These signals match known fraud/card testing behaviors.",
      "suspicious_signals": [
        "12 chargebacks from a single user in one week/month (all same card type and BIN, no CVV, UNKNOWN 3DS)",
        "First and last transaction within a few hours; new merchant with all activity compressed into one brief period",
        "High number of failed/canceled transactions (50 in one week vs 14 successful)",
        "High count of response code 14 (invalid card): 9 in a week out of just 14 authorized/settled",
        "Only 2 unique users in t1d, 25 in t1w, very low for the total number of attempts",
        "Activity pattern fits 'card verification' and testing abuse"
      ],
      "recommendation": "BLOCK",
      "confidence": 0.98
    }
- 1 new item(s)
- 1 raw response(s)
- 0 input guardrail result(s)
- 0 output guardrail result(s)
(See `RunResult` for more details)

In [ ]:
result

In [117]:
print(user_prompt)

    MERCHANT FRAUD ANALYSIS REQUEST
    ================================

    MERCHANT CONTEXT:
    ELKWEDY FASHION DESIGNDubai        000AE was blocked on 2026-04-01 05:07:36 due to "Card Verifications".

    ---

    PAST TRANSACTIONALITY SUMMARY:
    - first_tx_date: t1d=2026-04-01 00:00, t1w=2026-03-31 22:46, ytd=2026-03-31 22:46
- last_tx_date: t1d=2026-04-01 04:35, t1w=2026-04-01 04:35, ytd=2026-04-01 04:35
- cnt_cr_0: t1d=0, t1w=14, ytd=14
- cnt_cr_0_no_3ds_no_cvv: t1d=0, t1w=14, ytd=14
- cnt_cr_14: t1d=2, t1w=9, ytd=9
- cnt_cr_51: t1d=0, t1w=41, ytd=41
- cnt_cr_51_no_3ds_no_cvv: t1d=0, t1w=41, ytd=41
- cnt_unique_users: t1d=2, t1w=25, ytd=25
- cnt_state_failed_canceled: t1d=2, t1w=50, ytd=50
- cnt_authorized_settled: t1d=0, t1w=14, ytd=14
- cnt_card_type_PHYSICAL_no_3ds_no_cvv: t1d=0, t1w=38, ytd=38
- cnt_card_type_VIRTUAL_no_3ds_no_cvv: t1d=0, t1w=17, ytd=17
- cnt_product_type_CREDIT_5401_BIN_no_3ds_no_cvv: t1d=0, t1w=51, ytd=51
- cnt_product_type_CREDIT_5456_BIN_no_3ds_no_cvv: t1d=0, t1w=4, ytd=4

    ---

    CHARGEBACKS SUMMARY:
    {
  "ELKWEDY FASHION DESIGNDubai        000AE": {
    "merchant_name": "ELKWEDY FASHION DESIGNDubai        000AE",
    "blocking_date": "2026-04-01 05:07:36",
    "first_appearance": "2026-03-31 23:03:08.776000",
    "last_appearance": "2026-03-31 23:07:32.740000",
    "timeframes": {
      "1_week": {
        "start_time": "2026-03-25 05:07:36",
        "end_time": "2026-04-01 05:07:36",
        "num_chargebacks_reported": 12,
        "num_unique_users": 1,
        "num_klrids_per_card_type": {
          "PHYSICAL": 1
        },
        "num_klrids_per_product_type": {
          "CREDIT_5401_BIN": 1
        },
        "num_transactions_per_cvv_indicator": {
          "no cvv": 12
        },
        "num_transactions_per_3ds_status": {
          "UNKNOWN": 12
        }
      },
      "1_month": {
        "start_time": "2026-03-02 05:07:36",
        "end_time": "2026-04-01 05:07:36",
        "num_chargebacks_reported": 12,
        "num_unique_users": 1,
        "num_klrids_per_card_type": {
          "PHYSICAL": 1
        },
        "num_klrids_per_product_type": {
          "CREDIT_5401_BIN": 1
        },
        "num_transactions_per_cvv_indicator": {
          "no cvv": 12
        },
        "num_transactions_per_3ds_status": {
          "UNKNOWN": 12
        }
      },
      "ytd": {
        "start_time": "2026-01-01 00:00:00",
        "end_time": "2026-04-01 05:07:36",
        "num_chargebacks_reported": 12,
        "num_unique_users": 1,
        "num_klrids_per_card_type": {
          "PHYSICAL": 1
        },
        "num_klrids_per_product_type": {
          "CREDIT_5401_BIN": 1
        },
        "num_transactions_per_cvv_indicator": {
          "no cvv": 12
        },
        "num_transactions_per_3ds_status": {
          "UNKNOWN": 12
        }
      }
    }
  }
}

    ---

    RESPONSE CODES ANALYSIS:
    No response code data available for analysis.

    ---

    ANALYSIS REQUIREMENTS:
    1. Evaluate the merchant based on all three data dimensions (transactions, chargebacks, response codes)
    2. Identify patterns that indicate fraud or card testing activities
    3. Consider the relationship between failed transaction counts and specific response codes
    4. Assess the risk of this merchant based on:
    - Transaction velocity and volume
    - Chargeback patterns and frequency
    - Response code distribution (especially codes 14, 87, 51)
    - Temporal patterns in activity
    5. Provide a clear recommendation: BLOCK or DO NOT BLOCK

    Make a comprehensive decision based on all provided data.

In [82]:
for i in merchant_result.keys():
    print(f"Merchant: {i} | Analysis Result: {merchant_result}")

Merchant: Smoke Club FL LLC     Orlando      FL US | Analysis Result: {'Smoke Club FL LLC     Orlando      FL US': None, 'Paul Stuart Inc       2126820320   NY US': None, 'M800 LIMITED          KOWLOON BAY  KowHK': None, 'NY POST DIGITAL MEMBERNEW YORK     NY US': None, 'COOK MEMORIAL PUBLIC  LIBERTYVILLE IL US': None, 'LUAN MEIRELLES DIAS PARIBEIRAO PRETSP BR': None, 'IONOS INC             CHESTERBROOK PA US': None, 'Hims and Hers Inc.    San FranciscoCA US': None, 'ELKWEDY PERFUMES AND GDubai        000AE': None, 'ELKWEDY FASHION DESIGNDubai        000AE': None}
Merchant: Paul Stuart Inc       2126820320   NY US | Analysis Result: {'Smoke Club FL LLC     Orlando      FL US': None, 'Paul Stuart Inc       2126820320   NY US': None, 'M800 LIMITED          KOWLOON BAY  KowHK': None, 'NY POST DIGITAL MEMBERNEW YORK     NY US': None, 'COOK MEMORIAL PUBLIC  LIBERTYVILLE IL US': None, 'LUAN MEIRELLES DIAS PARIBEIRAO PRETSP BR': None, 'IONOS INC             CHESTERBROOK PA US': None, 'Hims and Hers Inc.    San FranciscoCA US': None, 'ELKWEDY PERFUMES AND GDubai        000AE': None, 'ELKWEDY FASHION DESIGNDubai        000AE': None}
Merchant: M800 LIMITED          KOWLOON BAY  KowHK | Analysis Result: {'Smoke Club FL LLC     Orlando      FL US': None, 'Paul Stuart Inc       2126820320   NY US': None, 'M800 LIMITED          KOWLOON BAY  KowHK': None, 'NY POST DIGITAL MEMBERNEW YORK     NY US': None, 'COOK MEMORIAL PUBLIC  LIBERTYVILLE IL US': None, 'LUAN MEIRELLES DIAS PARIBEIRAO PRETSP BR': None, 'IONOS INC             CHESTERBROOK PA US': None, 'Hims and Hers Inc.    San FranciscoCA US': None, 'ELKWEDY PERFUMES AND GDubai        000AE': None, 'ELKWEDY FASHION DESIGNDubai        000AE': None}
Merchant: NY POST DIGITAL MEMBERNEW YORK     NY US | Analysis Result: {'Smoke Club FL LLC     Orlando      FL US': None, 'Paul Stuart Inc       2126820320   NY US': None, 'M800 LIMITED          KOWLOON BAY  KowHK': None, 'NY POST DIGITAL MEMBERNEW YORK     NY US': None, 'COOK MEMORIAL PUBLIC  LIBERTYVILLE IL US': None, 'LUAN MEIRELLES DIAS PARIBEIRAO PRETSP BR': None, 'IONOS INC             CHESTERBROOK PA US': None, 'Hims and Hers Inc.    San FranciscoCA US': None, 'ELKWEDY PERFUMES AND GDubai        000AE': None, 'ELKWEDY FASHION DESIGNDubai        000AE': None}
Merchant: COOK MEMORIAL PUBLIC  LIBERTYVILLE IL US | Analysis Result: {'Smoke Club FL LLC     Orlando      FL US': None, 'Paul Stuart Inc       2126820320   NY US': None, 'M800 LIMITED          KOWLOON BAY  KowHK': None, 'NY POST DIGITAL MEMBERNEW YORK     NY US': None, 'COOK MEMORIAL PUBLIC  LIBERTYVILLE IL US': None, 'LUAN MEIRELLES DIAS PARIBEIRAO PRETSP BR': None, 'IONOS INC             CHESTERBROOK PA US': None, 'Hims and Hers Inc.    San FranciscoCA US': None, 'ELKWEDY PERFUMES AND GDubai        000AE': None, 'ELKWEDY FASHION DESIGNDubai        000AE': None}
Merchant: LUAN MEIRELLES DIAS PARIBEIRAO PRETSP BR | Analysis Result: {'Smoke Club FL LLC     Orlando      FL US': None, 'Paul Stuart Inc       2126820320   NY US': None, 'M800 LIMITED          KOWLOON BAY  KowHK': None, 'NY POST DIGITAL MEMBERNEW YORK     NY US': None, 'COOK MEMORIAL PUBLIC  LIBERTYVILLE IL US': None, 'LUAN MEIRELLES DIAS PARIBEIRAO PRETSP BR': None, 'IONOS INC             CHESTERBROOK PA US': None, 'Hims and Hers Inc.    San FranciscoCA US': None, 'ELKWEDY PERFUMES AND GDubai        000AE': None, 'ELKWEDY FASHION DESIGNDubai        000AE': None}
Merchant: IONOS INC             CHESTERBROOK PA US | Analysis Result: {'Smoke Club FL LLC     Orlando      FL US': None, 'Paul Stuart Inc       2126820320   NY US': None, 'M800 LIMITED          KOWLOON BAY  KowHK': None, 'NY POST DIGITAL MEMBERNEW YORK     NY US': None, 'COOK MEMORIAL PUBLIC  LIBERTYVILLE IL US': None, 'LUAN MEIRELLES DIAS PARIBEIRAO PRETSP BR': None, 'IONOS INC             CHESTERBROOK PA US': None, 'Hims and Hers Inc.    San FranciscoCA US': None, 'ELKWEDY PERFUMES AND GDubai        000AE': None, 'ELKWEDY FASHION DESIGNDubai        000AE': None}
Merchant: Hims and Hers Inc.    San FranciscoCA US | Analysis Result: {'Smoke Club FL LLC     Orlando      FL US': None, 'Paul Stuart Inc       2126820320   NY US': None, 'M800 LIMITED          KOWLOON BAY  KowHK': None, 'NY POST DIGITAL MEMBERNEW YORK     NY US': None, 'COOK MEMORIAL PUBLIC  LIBERTYVILLE IL US': None, 'LUAN MEIRELLES DIAS PARIBEIRAO PRETSP BR': None, 'IONOS INC             CHESTERBROOK PA US': None, 'Hims and Hers Inc.    San FranciscoCA US': None, 'ELKWEDY PERFUMES AND GDubai        000AE': None, 'ELKWEDY FASHION DESIGNDubai        000AE': None}
Merchant: ELKWEDY PERFUMES AND GDubai        000AE | Analysis Result: {'Smoke Club FL LLC     Orlando      FL US': None, 'Paul Stuart Inc       2126820320   NY US': None, 'M800 LIMITED          KOWLOON BAY  KowHK': None, 'NY POST DIGITAL MEMBERNEW YORK     NY US': None, 'COOK MEMORIAL PUBLIC  LIBERTYVILLE IL US': None, 'LUAN MEIRELLES DIAS PARIBEIRAO PRETSP BR': None, 'IONOS INC             CHESTERBROOK PA US': None, 'Hims and Hers Inc.    San FranciscoCA US': None, 'ELKWEDY PERFUMES AND GDubai        000AE': None, 'ELKWEDY FASHION DESIGNDubai        000AE': None}
Merchant: ELKWEDY FASHION DESIGNDubai        000AE | Analysis Result: {'Smoke Club FL LLC     Orlando      FL US': None, 'Paul Stuart Inc       2126820320   NY US': None, 'M800 LIMITED          KOWLOON BAY  KowHK': None, 'NY POST DIGITAL MEMBERNEW YORK     NY US': None, 'COOK MEMORIAL PUBLIC  LIBERTYVILLE IL US': None, 'LUAN MEIRELLES DIAS PARIBEIRAO PRETSP BR': None, 'IONOS INC             CHESTERBROOK PA US': None, 'Hims and Hers Inc.    San FranciscoCA US': None, 'ELKWEDY PERFUMES AND GDubai        000AE': None, 'ELKWEDY FASHION DESIGNDubai        000AE': None}

In [ ]:
# TODO: pruebas % accuracy

In [122]:
result = await fraud_CV_agent(user_prompt)

In [138]:
df["suspicious_signals"].iloc[0]

'Merchant first appeared less than 24 hours before blocking—very short history\nOnly 25 unique users but 50 failed/canceled transactions and 41 response code 51 (insufficient funds) in a week\n12 chargebacks across only 1 unique user and concentrated in 1 BIN/card type—all without CVV/3DS\nCard testing patterns: high failed/canceled transaction rate, high rc_14 (9/week), high rc_51 (41/week), and 14 authorized/settled across 25 users\nActivity abruptly starts and intensifies, with no prior history'

In [158]:
merchant_result

{'Smoke Club FL LLC     Orlando      FL US':   risk_level                                            summary  \
 0       high  The merchant shows clear evidence of card test...

                                   suspicious_signals recommendation  \
 0  44.83% of transactions were invalid card (code...          BLOCK

    confidence
 0        0.99  ,
 'Paul Stuart Inc       2126820320   NY US':   risk_level                                            summary  \
 0       high  Paul Stuart Inc exhibited all transaction acti...

                                   suspicious_signals recommendation  \
 0  62 response code 14 (invalid card number) even...          BLOCK

    confidence
 0        0.98  ,
 'M800 LIMITED          KOWLOON BAY  KowHK':   risk_level                                            summary  \
 0       high  The merchant 'M800 LIMITED KOWLOON BAY KowHK' ...

                                   suspicious_signals recommendation  \
 0  Recent merchant activity started very recently...          BLOCK

    confidence
 0        0.99  ,
 'NY POST DIGITAL MEMBERNEW YORK     NY US':   risk_level                                            summary  \
 0       high  NY POST DIGITAL MEMBERNEW YORK NY US demonstra...

                                   suspicious_signals recommendation  \
 0  Merchant first observed and only active within...          BLOCK

    confidence
 0        0.99  ,
 'COOK MEMORIAL PUBLIC  LIBERTYVILLE IL US':   risk_level                                            summary  \
 0       high  The merchant displayed extremely short and int...

                                   suspicious_signals recommendation  \
 0  All activity occurred within a single 2-minute...          BLOCK

    confidence
 0        0.98  ,
 'LUAN MEIRELLES DIAS PARIBEIRAO PRETSP BR':   risk_level                                            summary  \
 0     medium  LUAN MEIRELLES DIAS PARIBEIRAO PRETSP BR is a ...

                                   suspicious_signals recommendation  \
 0  Merchant appeared for the first time with a si...          BLOCK

    confidence
 0         0.9  ,
 'IONOS INC             CHESTERBROOK PA US':   risk_level                                            summary  \
 0       high  IONOS INC shows multiple risk signals aligning...

                                   suspicious_signals recommendation  \
 0  Very short merchant history with significant r...          BLOCK

    confidence
 0        0.95  ,
 'Hims and Hers Inc.    San FranciscoCA US':   risk_level                                            summary  \
 0       high  Merchant demonstrates classic card testing and...

                                   suspicious_signals recommendation  \
 0  100% of 2026-04-03 transactions (25/25) were d...          BLOCK

    confidence
 0         1.0  ,
 'ELKWEDY PERFUMES AND GDubai        000AE':   risk_level                                            summary  \
 0       high  The merchant 'ELKWEDY PERFUMES AND GDubai 000A...

                                   suspicious_signals recommendation  \
 0  Very recent first and last transaction (same d...          BLOCK

    confidence
 0        0.98  ,
 'ELKWEDY FASHION DESIGNDubai        000AE':   risk_level                                            summary  \
 0       high  The merchant ELKWEDY FASHION DESIGNDubai 000AE...

                                   suspicious_signals recommendation  \
 0  All activity occurred in less than 2 days (mer...          BLOCK

    confidence
 0        0.98  ,
 'Nova Wave Trading FZLLRas AlKhaima000AE':   risk_level                                            summary  \
 0        low  There is no transaction, chargeback, or respon...

                                   suspicious_signals recommendation  \
 0  Merchant previously blocked for 'Card Verifica...      NOT BLOCK

    confidence
 0         0.7  ,
 'SIMPLISAFE            BOSTON       MA US':   risk_level                                            summary  \
 0       high  SIMPLISAFE shows extremely suspicious transact...

                                   suspicious_signals recommendation  \
 0  20 response code 14 (invalid card number) tran...          BLOCK

    confidence
 0        0.99  ,
 'MAKRAM HANNA PERFUMES Dubai        000AE':   risk_level                                            summary  \
 0       high  The merchant 'MAKRAM HANNA PERFUMES Dubai 000A...

                                   suspicious_signals recommendation  \
 0  Merchant appeared and was blocked within less ...          BLOCK

    confidence
 0        0.95  ,
 'Partyrama             Milton KeynesENGGB':   risk_level                                            summary  \
 0       high  The merchant shows a very short operational hi...

                                   suspicious_signals recommendation  \
 0  First transaction only 24 hours before block; ...          BLOCK

    confidence
 0        0.99  ,
 'CANEX.CA HPS          OTTAWA       000CA':   risk_level                                            summary  \
 0       high  The merchant shows multiple high-risk fraud in...

                                   suspicious_signals recommendation  \
 0  12 code 14 (invalid card) declines in t1d (exc...          BLOCK

    confidence
 0        0.99  ,
 'Nova Wave Trading FZLLRas Al Khaima000AE':   risk_level                                            summary  \
 0       high  Nova Wave Trading shows significant indicators...

                                   suspicious_signals recommendation  \
 0  Merchant first seen within the last day; all a...          BLOCK

    confidence
 0        0.95  ,
 'WARRANTY PURCHASE     LOUISVILLE   KY US':   risk_level                                            summary  \
 0       high  Merchant shows extreme and persistent indicato...

                                   suspicious_signals recommendation  \
 0  Very high percentage of response code 14 (inva...          BLOCK

    confidence
 0        0.99  ,
 'MAKRAM HANNA FASHION DDubai        000AE':   risk_level                                            summary  \
 0       high  The merchant appeared for less than one hour, ...

                                   suspicious_signals recommendation  \
 0  Merchant first and last transaction occurred w...          BLOCK

    confidence
 0        0.99  ,
 'ALZDJALY FOR PERFUMES Dubai        000AE':   risk_level                                            summary  \
 0       high  The merchant ALZDJALY FOR PERFUMES Dubai 000AE...

                                   suspicious_signals recommendation  \
 0  All activity within ~1 hour of first seen date...          BLOCK

    confidence
 0        0.98  ,
 'MAXFY                 MILDENHALL   ENGGB':   risk_level                                            summary  \
 0       high  MAXFY MILDENHALL ENGGB displays strong and con...

                                   suspicious_signals recommendation  \
 0  Extremely high proportion of code 87 ('fraud/s...          BLOCK

    confidence
 0        0.99  ,
 'KCPBUSCLAS           CIUDAD DE MEX001MX':   risk_level                                            summary  \
 0       high  The merchant KCPBUSCLAS CIUDAD DE MEX001MX sho...

                                   suspicious_signals recommendation  \
 0  Very recent first appearance and rapid blockin...          BLOCK

    confidence
 0        0.95  ,
 'KCPBSK               CIUDAD DE MEX001MX':   risk_level                                            summary  \
 0       high  The merchant demonstrated strong signals of ca...

                                   suspicious_signals recommendation  \
 0  Very recent first appearance (2025-12-20) with...          BLOCK

    confidence
 0        0.95  ,
 'ATLAS EXCHANGE LIMITEDLusaka       000KE':   risk_level                                            summary  \
 0     medium  The merchant ATLAS EXCHANGE LIMITEDLusaka has ...

                                   suspicious_signals recommendation  \
 0  2 chargebacks with only 5 settled transactions...          BLOCK

    confidence
 0        0.85  ,
 'CS ONLINESHOP         BOSTON       MA US':   risk_level                                            summary  \
 0       high  The merchant CS ONLINESHOP exhibited a very re...

                                   suspicious_signals recommendation  \
 0  All transaction activity packed within a ~15-m...          BLOCK

    confidence
 0        0.99  ,
 'AARON ABKE 4D UNIVERS+14082066220 TX US':   risk_level                                            summary  \
 0        low  There is no transactional, chargeback, or resp...

                                   suspicious_signals recommendation  \
 0  Merchant was blocked for 'Card Verifications.'...      NOT BLOCK

    confidence
 0         0.6  ,
 'EASY MONEY CHEAP RIDESNEWPORT      OR US':   risk_level                                            summary  \
 0       high  The merchant 'EASY MONEY CHEAP RIDESNEWPORT OR...

                                   suspicious_signals recommendation  \
 0  Extremely high and increasing ratio of respons...          BLOCK

    confidence
 0        0.99  ,
 'VOGO GLOBAL           RALEIGH      NC US':   risk_level                                            summary  \
 0       high  VOGO GLOBAL demonstrated an extremely high rat...

                                   suspicious_signals recommendation  \
 0  46% of all transactions declined due to fraud/...          BLOCK

    confidence
 0        0.99  ,
 'OMNIVISIX             BAD ISCHL    AT AT':   risk_level                                            summary  \
 0       high  OMNIVISIX BAD ISCHL AT AT shows a very high pr...

                                   suspicious_signals recommendation  \
 0  Exceptionally high and accelerating code 87 (f...          BLOCK

    confidence
 0        0.98  ,
 'WONDERFUL             BLOOMFIELD   NJ US':   risk_level                                            summary  \
 0       high  The merchant WONDERFUL BLOOMFIELD NJ US shows ...

                                   suspicious_signals recommendation  \
 0  Very recent appearance (first_tx_date: 2026-02...          BLOCK

    confidence
 0        0.99  ,
 'PLANTARWEB BY IMT SRL MILANO       MI IT':   risk_level                                            summary  \
 0       high  The merchant 'PLANTARWEB BY IMT SRL MILANO MI ...

                                   suspicious_signals recommendation  \
 0  15 card verification failures (code 87), compa...          BLOCK

    confidence
 0         1.0  ,
 'CBI BALFOUR           AUSTIN       TX US':   risk_level                                            summary  \
 0       high  Merchant displays a sustained and very high pr...

                                   suspicious_signals recommendation  \
 0  Extremely high ratios of code 14 (invalid card...          BLOCK

    confidence
 0        0.98  ,
 'BIOLONGEVITY          LAS VEGAS    NV US':   risk_level                                            summary  \
 0       high  The merchant, BIOLONGEVITY LAS VEGAS NV US, ex...

                                   suspicious_signals recommendation  \
 0  First transaction and only transaction window:...          BLOCK

    confidence
 0        0.98  ,
 'B2 SUPERVALUE CHECKS NEW BRAUNFELSTX US':   risk_level                                            summary  \
 0        low  There is insufficient data to establish any fr...

                                   suspicious_signals recommendation  \
 0  Merchant blocked due to 'Card Verifications' (...      NOT BLOCK

    confidence
 0         0.5  ,
 'STARCROWN, INC.       NAHASHI      okiJP':   risk_level                                            summary  \
 0       high  Merchant has extremely short history, with hig...

                                   suspicious_signals recommendation  \
 0  Extremely short transaction history (all activ...          BLOCK

    confidence
 0        0.98  ,
 'MOOVTOO.COM           PARIS        IleFR':   risk_level                                            summary  \
 0       high  MOOVTOO.COM shows multiple, clear signs of car...

                                   suspicious_signals recommendation  \
 0  32-34 response code 87s within days (fraud/sec...          BLOCK

    confidence
 0        0.98  ,
 'STEPINTO GROUP LTD    KINGTON      LNDGB':   risk_level                                            summary  \
 0       high  STEPINTO GROUP LTD showed a massive spike in t...

                                   suspicious_signals recommendation  \
 0  Extremely short merchant lifetime (no history ...          BLOCK

    confidence
 0        0.99  ,
 'TRIVIVA LLC           ROUND ROCK   TX US':   risk_level                                            summary  \
 0       high  TRIVIVA LLC shows clear signs of high-risk beh...

                                   suspicious_signals recommendation  \
 0  Merchant first appeared and was blocked the sa...          BLOCK

    confidence
 0        0.98  ,
 'P&C SHOP /SHIPPELLO   LAUDERDALE LAFL US':   risk_level                                            summary  \
 0       high  The merchant shows a pattern of very recent ac...

                                   suspicious_signals recommendation  \
 0  cnt_cr_14 (invalid card): 23 in t1d/t1w/ytd vs...          BLOCK

    confidence
 0        0.99  ,
 'SHIPPELLO             GARLAND      TX US':   risk_level                                            summary  \
 0       high  The merchant SHIPPELLO shows a pattern of frau...

                                   suspicious_signals recommendation  \
 0  All response code 14 (14 in one day, 100% of i...          BLOCK

    confidence
 0        0.99  }

In [159]:
merchant_result["AARON ABKE 4D UNIVERS+14082066220 TX US"]

,risk_level,summary,suspicious_signals,recommendation,confidence
0,low,"There is no transactional, chargeback, or resp...",Merchant was blocked for 'Card Verifications.'...,NOT BLOCK,0.6

In [164]:
result_df = pd.concat(
    [
        df.assign(merchant_name=merchant_name)
        for merchant_name, df in merchant_result.items()
    ],
    ignore_index=True
)
result_df = result_df[[
    'merchant_name', 'risk_level', 'summary', 'suspicious_signals', 'recommendation', 'confidence'
]]

In [166]:
result_df.recommendation.value_counts(normalize=True)

recommendation
BLOCK        0.923077
NOT BLOCK    0.076923
Name: proportion, dtype: float64

In [167]:
result_df.shape

(39, 6)

In [169]:
result_df.to_excel('misc_info/fraud_agent_results.xlsx', index=False)

In [171]:
blocking_agent_sheet = '1A7ECmSCOobNxamBdmMzqJqnchO_WjcA68yj-qCrtXcI'

In [172]:
worksheet_blocking_agent = gc.open_by_key(blocking_agent_sheet).worksheet('results')

In [174]:
worksheet_blocking_agent.update([result_df.columns.values.tolist()] + result_df.values.tolist())

{'spreadsheetId': '1A7ECmSCOobNxamBdmMzqJqnchO_WjcA68yj-qCrtXcI',
 'updatedRange': 'results!A1:F40',
 'updatedRows': 40,
 'updatedColumns': 6,
 'updatedCells': 240}

In [170]:
result_df

,merchant_name,risk_level,summary,suspicious_signals,recommendation,confidence
0,Smoke Club FL LLC Orlando FL US,high,The merchant shows clear evidence of card test...,44.83% of transactions were invalid card (code...,BLOCK,0.99
1,Paul Stuart Inc 2126820320 NY US,high,Paul Stuart Inc exhibited all transaction acti...,62 response code 14 (invalid card number) even...,BLOCK,0.98
2,M800 LIMITED KOWLOON BAY KowHK,high,The merchant 'M800 LIMITED KOWLOON BAY KowHK' ...,Recent merchant activity started very recently...,BLOCK,0.99
3,NY POST DIGITAL MEMBERNEW YORK NY US,high,NY POST DIGITAL MEMBERNEW YORK NY US demonstra...,Merchant first observed and only active within...,BLOCK,0.99
4,COOK MEMORIAL PUBLIC LIBERTYVILLE IL US,high,The merchant displayed extremely short and int...,All activity occurred within a single 2-minute...,BLOCK,0.98
5,LUAN MEIRELLES DIAS PARIBEIRAO PRETSP BR,medium,LUAN MEIRELLES DIAS PARIBEIRAO PRETSP BR is a ...,Merchant appeared for the first time with a si...,BLOCK,0.90
6,IONOS INC CHESTERBROOK PA US,high,IONOS INC shows multiple risk signals aligning...,Very short merchant history with significant r...,BLOCK,0.95
7,Hims and Hers Inc. San FranciscoCA US,high,Merchant demonstrates classic card testing and...,100% of 2026-04-03 transactions (25/25) were d...,BLOCK,1.00
8,ELKWEDY PERFUMES AND GDubai 000AE,high,The merchant 'ELKWEDY PERFUMES AND GDubai 000A...,Very recent first and last transaction (same d...,BLOCK,0.98
9,ELKWEDY FASHION DESIGNDubai 000AE,high,The merchant ELKWEDY FASHION DESIGNDubai 000AE...,All activity occurred in less than 2 days (mer...,BLOCK,0.98
10,Nova Wave Trading FZLLRas AlKhaima000AE,low,"There is no transaction, chargeback, or respon...",Merchant previously blocked for 'Card Verifica...,NOT BLOCK,0.70
11,SIMPLISAFE BOSTON MA US,high,SIMPLISAFE shows extremely suspicious transact...,20 response code 14 (invalid card number) tran...,BLOCK,0.99
12,MAKRAM HANNA PERFUMES Dubai 000AE,high,The merchant 'MAKRAM HANNA PERFUMES Dubai 000A...,Merchant appeared and was blocked within less ...,BLOCK,0.95
13,Partyrama Milton KeynesENGGB,high,The merchant shows a very short operational hi...,First transaction only 24 hours before block; ...,BLOCK,0.99
14,CANEX.CA HPS OTTAWA 000CA,high,The merchant shows multiple high-risk fraud in...,12 code 14 (invalid card) declines in t1d (exc...,BLOCK,0.99
15,Nova Wave Trading FZLLRas Al Khaima000AE,high,Nova Wave Trading shows significant indicators...,Merchant first seen within the last day; all a...,BLOCK,0.95
16,WARRANTY PURCHASE LOUISVILLE KY US,high,Merchant shows extreme and persistent indicato...,Very high percentage of response code 14 (inva...,BLOCK,0.99
17,MAKRAM HANNA FASHION DDubai 000AE,high,"The merchant appeared for less than one hour, ...",Merchant first and last transaction occurred w...,BLOCK,0.99
18,ALZDJALY FOR PERFUMES Dubai 000AE,high,The merchant ALZDJALY FOR PERFUMES Dubai 000AE...,All activity within ~1 hour of first seen date...,BLOCK,0.98
19,MAXFY MILDENHALL ENGGB,high,MAXFY MILDENHALL ENGGB displays strong and con...,Extremely high proportion of code 87 ('fraud/s...,BLOCK,0.99
20,KCPBUSCLAS CIUDAD DE MEX001MX,high,The merchant KCPBUSCLAS CIUDAD DE MEX001MX sho...,Very recent first appearance and rapid blockin...,BLOCK,0.95
21,KCPBSK CIUDAD DE MEX001MX,high,The merchant demonstrated strong signals of ca...,Very recent first appearance (2025-12-20) with...,BLOCK,0.95
22,ATLAS EXCHANGE LIMITEDLusaka 000KE,medium,The merchant ATLAS EXCHANGE LIMITEDLusaka has ...,2 chargebacks with only 5 settled transactions...,BLOCK,0.85
23,CS ONLINESHOP BOSTON MA US,high,The merchant CS ONLINESHOP exhibited a very re...,All transaction activity packed within a ~15-m...,BLOCK,0.99
24,AARON ABKE 4D UNIVERS+14082066220 TX US,low,"There is no transactional, chargeback, or resp...",Merchant was blocked for 'Card Verifications.'...,NOT BLOCK,0.60
25,EASY MONEY CHEAP RIDESNEWPORT OR US,high,The merchant 'EASY MONEY CHEAP RIDESNEWPORT OR...,Extremely high and increasing ratio of respons...,BLOCK,0.99
26,VOGO GLOBAL RALEIGH NC US,high,VOGO GLOBAL demonstrated an extremely high rat...,46% of all transactions declined due to fraud/...,BLOCK,0.99
27,OMNIVISIX BAD ISCHL AT AT,high,OMNIVISIX BAD ISCHL AT AT shows a very high pr...,Exceptionally high and accelerating code 87 (f...,BLOCK,0.98
28,WONDERFUL BLOOMFIELD NJ US,high,The merchant WONDERFUL BLOOMFIELD NJ US shows ...,Very recent appearance (first_tx_date: 2026-02...,BLOCK,0.99
29,PLANTARWEB BY IMT SRL MILANO MI IT,high,The merchant 'PLANTARWEB BY IMT SRL MILANO MI ...,"15 card verification failures (code 87), compa...",BLOCK,1.00
30,CBI BALFOUR AUSTIN TX US,high,Merchant displays a sustained and very high pr...,Extremely high ratios of code 14 (invalid card...,BLOCK,0.98
31,BIOLONGEVITY LAS VEGAS NV US,high,"The merchant, BIOLONGEVITY LAS VEGAS NV US, ex...",First transaction and only transaction window:...,BLOCK,0.98
32,B2 SUPERVALUE CHECKS NEW BRAUNFELSTX US,low,There is insufficient data to establish any fr...,Merchant blocked due to 'Card Verifications' (...,NOT BLOCK,0.50
33,"STARCROWN, INC. NAHASHI okiJP",high,"Merchant has extremely short history, with hig...",Extremely short transaction history (all activ...,BLOCK,0.98
34,MOOVTOO.COM PARIS IleFR,high,"MOOVTOO.COM shows multiple, clear signs of car...",32-34 response code 87s within days (fraud/sec...,BLOCK,0.98
35,STEPINTO GROUP LTD KINGTON LNDGB,high,STEPINTO GROUP LTD showed a massive spike in t...,Extremely short merchant lifetime (no history ...,BLOCK,0.99
36,TRIVIVA LLC ROUND ROCK TX US,high,TRIVIVA LLC shows clear signs of high-risk beh...,Merchant first appeared and was blocked the sa...,BLOCK,0.98
37,P&C SHOP /SHIPPELLO LAUDERDALE LAFL US,high,The merchant shows a pattern of very recent ac...,cnt_cr_14 (invalid card): 23 in t1d/t1w/ytd vs...,BLOCK,0.99
38,SHIPPELLO GARLAND TX US,high,The merchant SHIPPELLO shows a pattern of frau...,"All response code 14 (14 in one day, 100% of i...",BLOCK,0.99

In [184]:
# add extra result df to the google sheets worksheet
full_df = pd.concat([result_df, extra_result_df], ignore_index=True)

In [185]:
worksheet_blocking_agent.update([full_df.columns.values.tolist()] + full_df.values.tolist())

{'spreadsheetId': '1A7ECmSCOobNxamBdmMzqJqnchO_WjcA68yj-qCrtXcI',
 'updatedRange': 'results!A1:F42',
 'updatedRows': 42,
 'updatedColumns': 6,
 'updatedCells': 252}

In [ ]:
#create card verification query so that the agent can fetch the data

In [51]:
merchant = 'ANTHROPIC             SAN FRANCISCOCA US'

In [52]:
test_df = summarize_card_verification_anomaly(merchant)

/var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/ipykernel_9221/3607359053.py:100: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  card_verification_df = pd.read_sql(query, con=get_db_conn())

In [ ]:
test_df

Index(['operador', 'pais', 'total_count_1h', 'validation_count_1h',
       'validation_rate_1h', 'avg_total_count_same_hour_7d',
       'avg_validation_count_same_hour_7d', 'avg_validation_rate_same_hour_7d',
       'max_validation_count_same_hour_7d', 'max_validation_rate_same_hour_7d',
       'baseline_hours', 'validation_count_lift',
       'validation_rate_multiplier'],
      dtype='object')