In [1]:
cd ..

/Users/camila.cusicanqui/Documents/GitHub/frod-agentic-ai

In [2]:
%load_ext autoreload
%autoreload 2

In [36]:
import os
import yaml

with open(".config/credentials-mage.yaml", "r") as f:
    creds = yaml.safe_load(f)

for item in creds:
    os.environ[item["name"]] = str(item["value"])

In [19]:
import importlib.util
import sys
from pathlib import Path

TRANSACTION_SCHEMA_PATH = Path(
    "/Users/camila.cusicanqui/Documents/GitHub/analytics-mage-infra/mage-fraud-space/fraud_utils/fraud_agents/schemas/transactions.py"
)
spec = importlib.util.spec_from_file_location("fraud_transaction_schemas", TRANSACTION_SCHEMA_PATH)
if spec is None or spec.loader is None:
    raise ImportError(f"Could not load transaction schemas from {TRANSACTION_SCHEMA_PATH}")

transaction_schemas = importlib.util.module_from_spec(spec)
sys.modules[spec.name] = transaction_schemas
spec.loader.exec_module(transaction_schemas)

TransactionRow = transaction_schemas.TransactionRow
TransactionBatch = transaction_schemas.TransactionBatch

In [34]:
# homemade utils
from utils.data_ingest import get_db_conn
from utils.chargeback_data import load_cb_df
# librerías 
import pandas as pd
import numpy as np
import gspread
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import date, timedelta, datetime
import gspread
from dateutil.utils import today

# formatting options
pd.set_option('display.max_columns', None)
pd.options.display.float_format = '{:,.2f}'.format

In [6]:
cb_df = load_cb_df()

/Users/camila.cusicanqui/Documents/GitHub/frod-agentic-ai/utils/chargeback_data.py:201: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql(query, conn)

In [11]:
cb_df["amount_pos"] = cb_df["amount"]*-1

In [ ]:
important_cols = [
    'cb_timestamp',
    'user_id',
    'transaction_id',
    'trx_timestamp_mx',
    'amount_pos',
    # 'merchant',
    'operador',
    'mcc_code',
    'card_type',
    'product_type',
    'nombrearchivo',
    'embozo_file_date',
    'pos_entry_mode',
    'cvv_ind',
    'metodo_identificacion',
    'three_ds_flow',
    'afiliacion',
    'adquirente',
    'country',
    'cod_respuesta',   
]

In [43]:
cb_df

,freshdesk_ticket_id,cb_reason,cb_timestamp,user_id,klrid,transaction_id,trx_timestamp_mx,amount,merchant,mcc_code,card_type,product_type,nombrearchivo,pos_entry_mode,cvv_ind,t3ds_indicator,cb_source,sync_timestamp_utc,omi_id_operacion_raw,metodo_identificacion,leading_indicator,three_ds_status,three_ds_flow,c063,afiliacion,numero_terminal,adquirente,operador,cod_respuesta,trx_time,week_number,trx_date,trx_month,trx_day,trx_month_year,trx_week_year,cb_date,cb_month,cb_day,cb_month_year,cb_week_year,online,cb_reason_original,country,amount_pos,embozo_file_date
0,12544637,Otro,2025-06-03 22:44:13,44f3688e-45fd-44ea-81fe-b22d8c7cf1d8,052f20dd-dae2-41c6-b070-f19bda9466aa,PARABILIUM:100159166,2025-05-18 21:57:55.570,-800.00,OPENPAYADMA PROVIDENCIA 1JALMX,7277,VIRTUAL,CREDIT_5401_BIN,NaN,CNP Manual,has cvv,3ds,freshdesk,2025-12-09 23:10:45,100159166,NaN,kB,3DS_AUTHENTICATED,CHALLENGE,& 0000600344! C000026 XXXXXXXXXXXXXXXXXXXXXXXX...,4200578,03040378,12,OPENPAY*ADMA PROVIDENCIA 1JALMX,00,2025-05-18 21:57:55.570,20,2025-05-18,5.00,18.00,2025-05,2025-19,2025-06-03,6,3,2025-06,2025-22,True,Otro,MX,800.00,NaT
1,12401525,Otro,2025-05-21 15:12:43,18918cbe-d254-425a-8a11-9b7cf98d8b4d,942962f2-29c2-4ee1-ac59-1f2be7a21f32,PARABILIUM:100463184,2025-05-19 22:28:42.643,"-2,774.00",VOLARIS MOTO DEB 2 CIUDAD DE MEX001MX,4511,PHYSICAL,PLATINUM,par250125ProdJSP02_SubEm0004.emb,CNP Manual,has cvv,normal,freshdesk,2025-12-09 23:10:45,100463184,NaN,NaN,UNKNOWN,UNKNOWN,& 0000400082! C000026 XXXXXXXXXXXXXXXXXXXXXXXX...,8112910,208624789,5,VOLARIS MOTO DEB 2 CIUDAD DE MEX001MX,00,2025-05-19 22:28:42.643,21,2025-05-19,5.00,19.00,2025-05,2025-20,2025-05-21,5,21,2025-05,2025-20,True,Otro,MX,"2,774.00",2025-01-25
2,12595415,Otro,2025-06-09 01:47:29,e0b3bdb2-ec5f-4784-a5d4-9950225960c9,f768e9ac-1842-410f-b068-970e5743314b,PARABILIUM:100679780,2025-05-20 18:30:51.097,-109.00,TRACTEBEL DGQRO MU MEXICO DF DF MX,5983,PHYSICAL,CREDIT_5401_BIN,par240403ProdJSO01_SubEm0001.emb,CNP Manual,has cvv,3ds,freshdesk,2025-12-09 23:10:45,100679780,NaN,kA,3DS_AUTHENTICATED,FRICTIONLESS,& 0000600344! C000026 XXXXXXXXXXXXXXXXXXXXXXXX...,4040922,00007319,12,TRACTEBEL DGQRO MU MEXICO DF DF MX,00,2025-05-20 18:30:51.097,21,2025-05-20,5.00,20.00,2025-05,2025-20,2025-06-09,6,9,2025-06,2025-23,True,Otro,MX,109.00,2024-04-03
3,12460106,Cargo no reconocido,2025-05-26 20:50:10,f8fb6af7-bb15-40e2-a06a-3206ff35a40f,cfd80a63-7763-428a-8323-f2cdf3565d2e,101015177,2025-05-21 20:01:21.900,-349.00,KFC ECOMMERCE CIUDAD DE MEX001MX,5814,VIRTUAL,CREDIT_5401_BIN,NaN,CNP Manual,has cvv,3ds,freshdesk,2025-12-09 23:10:45,101015177,NaN,kB,3DS_AUTHENTICATED,CHALLENGE,& 0000600344! C000026 XXXXXXXXXXXXXXXXXXXXXXXX...,8419607,06699918,302,KFC ECOMMERCE CIUDAD DE MEX001MX,00,2025-05-21 20:01:21.900,21,2025-05-21,5.00,21.00,2025-05,2025-20,2025-05-26,5,26,2025-05,2025-21,True,Error durante el proceso,MX,349.00,NaT
4,12478081,Otro,2025-05-28 14:26:40,69cc717e-f27b-4a0f-b46f-3315d16fd228,07d988fc-3bab-441e-b6fe-1facab01267d,PARABILIUM:101804609,2025-05-24 13:16:47.739,-263.00,SERV CONSULTORIA MK HUIXQUILUCAN 015MX,7392,VIRTUAL,CREDIT_5456_BIN,NaN,CNP Manual,no cvv,normal,freshdesk,2025-12-09 23:10:45,101804609,NaN,NaN,UNKNOWN,UNKNOWN,& 0000500112! C000026 XXXXXXXXXXXXXXXXXXXXXXXX...,9628274,0000000000000001,485,SERV CONSULTORIA MK HUIXQUILUCAN 015MX,00,2025-05-24 13:16:47.739,21,2025-05-24,5.00,24.00,2025-05,2025-20,2025-05-28,5,28,2025-05,2025-21,True,Otro,MX,263.00,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
273751,14210678,Otro,2025-10-24 22:28:43,b69e2053-e9de-4cf7-af2f-350209fa7e8b,c09c3cd9-1670-4fbd-8010-29bfe1917543,c09c3cd9-1670-4fbd-8010-29bfe1917543:388852:SI...,2025-10-21 18:33:24.832,-149.00,,0731,PHYSICAL,PLATINUM,par250812ProdJSP01_SubEm0004.emb,NaN,unknown,normal,freshdesk,2025-12-09 23:10:45,c09c3cd9-1670-4fbd-8010-29bfe1917543:388852:SI...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-10-21 18:33:24.832,43,2025-10-21,10.00,21.00,2025-10,2025-42,2025-10-24,10,24,2025-10,2025-42,False,Otro,NaN,149.00,2025-08-12
273752,13830130,Cargo no reconocido,2025-09-24 23:10:48,3d2a5350-fa17-4a11-9d00-1e08e2431976,dd56284b-bf95-4912-ab11-083c659fb081,dd56284b-bf95-4912-ab11-083c659fb081:970959:88...,2025-09-24 16:02:31.436,-367.53,,0412,PHYSICAL,CREDIT_5401_BIN,par250916ProdJSO02_SubEm0001.emb,NaN,unknown,normal,freshdesk,2025-12-09 23:10:45,dd56284b-bf95-4912-ab11-083c659fb081:970959:88...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-09-24 16:02:31.436,39,2025-09-24,9.00,24.00,2025-09,2025-38,2025-09-24,9,24,2025-09,2025-38,False,Error durante el proceso,NaN,367.53,2025-09-16
273753,11670685,Otro,2025-03-21 20:16:49,14a6bb69-4303-4e85-900a-67a1c8425ce3,ed4a9f04-6c8b-4a7c-9aac-4cda56b42e15,ed4a9f04-6c8b-4a7c-9aac-4cda56b42e15: :00...,2025-03-05 17:59:41.078,-721.50,,0507,PHYSICAL,CREDIT_5401_BIN,par241124ProdJSO01_SubEm0001.emb,NaN,unknown,normal,freshdesk,2025-12-09 23:10:45,ed4a9f04-6c8b-4a7c-9aac-4cda56b42e15: :00...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-03-05 17:59:41.078,10,2025-03-05,3.00,5.00,2025-03,2025-09,2025-03-21,3,21,2025-03,2025-11,False,Otro,NaN,721.50,2024-11-24
273754,13640291,Cargo no reconocido,2025-09-09 12:35:59,cba1d2c0-6bdd-42ad-b753-e6ae94fcffae,f60976f9-0391-404d-a390-42ea83e3ecc5,f60976f9-0391-404d-a390-42ea83e3ecc5:830569:3O...,2025-09-08 18:01:16.906,-99.00,,0489,PHYSICAL,CREDIT_5456_BIN,NaN,NaN,unknown,normal,freshdesk,2025-12-09 23:10:45,f60976f9-0391-404d-a390-42ea83e3ecc5:830569:3O...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-09-08 18:01:16.906,37,2025-09-08,9.00,8.00,2025-09,2025-36,2025-09-09,9,9,2025-09,2025-36,False,Error durante el proceso,NaN,99.00,NaT
273755,14383355,Cargo no reconocido,2025-11-08 00:04:48,e7ec1bb1-5c3a-4001-af40-fcda32ef7def,fe36095a-f90e-47b2-a901-055abf5d2f81,fe36095a-f90e-47b2-a901-055abf5d2f81:183650:00...,2025-11-07 17:06:03.053,-200.00,,0490,VIRTUAL,CREDIT_5401_BIN,NaN,NaN,unknown,normal,freshdesk,2025-12-09 23:10:45,fe36095a-f90e-47b2-a901-055abf5d2f81:183650:00...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-11-07 17:06:03.053,45,2025-11-07,11.00,7.00,2025-11,2025-44,2025-11-08,11,8,2025-11,2025-44,False,Error durante el proceso,NaN,200.00,NaT

In [17]:
cb_df[important_cols]

,cb_timestamp,user_id,transaction_id,trx_timestamp_mx,amount_pos,operador,mcc_code,card_type,product_type,nombrearchivo,pos_entry_mode,cvv_ind,metodo_identificacion,three_ds_flow,afiliacion,adquirente,country,cod_respuesta
0,2025-06-03 22:44:13,44f3688e-45fd-44ea-81fe-b22d8c7cf1d8,PARABILIUM:100159166,2025-05-18 21:57:55.570,800.00,OPENPAY*ADMA PROVIDENCIA 1JALMX,7277,VIRTUAL,CREDIT_5401_BIN,NaN,CNP Manual,has cvv,NaN,CHALLENGE,4200578,12,MX,00
1,2025-05-21 15:12:43,18918cbe-d254-425a-8a11-9b7cf98d8b4d,PARABILIUM:100463184,2025-05-19 22:28:42.643,"2,774.00",VOLARIS MOTO DEB 2 CIUDAD DE MEX001MX,4511,PHYSICAL,PLATINUM,par250125ProdJSP02_SubEm0004.emb,CNP Manual,has cvv,NaN,UNKNOWN,8112910,5,MX,00
2,2025-06-09 01:47:29,e0b3bdb2-ec5f-4784-a5d4-9950225960c9,PARABILIUM:100679780,2025-05-20 18:30:51.097,109.00,TRACTEBEL DGQRO MU MEXICO DF DF MX,5983,PHYSICAL,CREDIT_5401_BIN,par240403ProdJSO01_SubEm0001.emb,CNP Manual,has cvv,NaN,FRICTIONLESS,4040922,12,MX,00
3,2025-05-26 20:50:10,f8fb6af7-bb15-40e2-a06a-3206ff35a40f,101015177,2025-05-21 20:01:21.900,349.00,KFC ECOMMERCE CIUDAD DE MEX001MX,5814,VIRTUAL,CREDIT_5401_BIN,NaN,CNP Manual,has cvv,NaN,CHALLENGE,8419607,302,MX,00
4,2025-05-28 14:26:40,69cc717e-f27b-4a0f-b46f-3315d16fd228,PARABILIUM:101804609,2025-05-24 13:16:47.739,263.00,SERV CONSULTORIA MK HUIXQUILUCAN 015MX,7392,VIRTUAL,CREDIT_5456_BIN,NaN,CNP Manual,no cvv,NaN,UNKNOWN,9628274,485,MX,00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
273751,2025-10-24 22:28:43,b69e2053-e9de-4cf7-af2f-350209fa7e8b,c09c3cd9-1670-4fbd-8010-29bfe1917543:388852:SI...,2025-10-21 18:33:24.832,149.00,NaN,0731,PHYSICAL,PLATINUM,par250812ProdJSP01_SubEm0004.emb,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN
273752,2025-09-24 23:10:48,3d2a5350-fa17-4a11-9d00-1e08e2431976,dd56284b-bf95-4912-ab11-083c659fb081:970959:88...,2025-09-24 16:02:31.436,367.53,NaN,0412,PHYSICAL,CREDIT_5401_BIN,par250916ProdJSO02_SubEm0001.emb,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN
273753,2025-03-21 20:16:49,14a6bb69-4303-4e85-900a-67a1c8425ce3,ed4a9f04-6c8b-4a7c-9aac-4cda56b42e15: :00...,2025-03-05 17:59:41.078,721.50,NaN,0507,PHYSICAL,CREDIT_5401_BIN,par241124ProdJSO01_SubEm0001.emb,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN
273754,2025-09-09 12:35:59,cba1d2c0-6bdd-42ad-b753-e6ae94fcffae,f60976f9-0391-404d-a390-42ea83e3ecc5:830569:3O...,2025-09-08 18:01:16.906,99.00,NaN,0489,PHYSICAL,CREDIT_5456_BIN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN
273755,2025-11-08 00:04:48,e7ec1bb1-5c3a-4001-af40-fcda32ef7def,fe36095a-f90e-47b2-a901-055abf5d2f81:183650:00...,2025-11-07 17:06:03.053,200.00,NaN,0490,VIRTUAL,CREDIT_5401_BIN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
cb_df.groupby(['three_ds_status','three_ds_flow']).transaction_id.nunique()

three_ds_status        three_ds_flow
3DS_AUTHENTICATED      CHALLENGE          10993
                       FRICTIONLESS        2987
3DS_NOT_AUTHENTICATED  EXEMPT_OR_INFO        52
UNKNOWN                UNKNOWN           241569
Name: transaction_id, dtype: int64

In [35]:
import asyncio
#from agents import Agent, Runner
#from agents import Agent, Runner, function_tool
import datetime as dt
import polars as pl
# import docx2txt
from pydantic import BaseModel, Field
from typing import List, Optional
import json

In [25]:
def _transaction_value_for_prompt(column, value):
    if pd.isna(value):
        return None
    if column == "amount_pos":
        return float(value)
    if hasattr(value, "isoformat"):
        return value.isoformat(sep=" ")
    return str(value)


def build_transaction_batch(df: pd.DataFrame, limit: int | None = None) -> TransactionBatch:
    rows_df = df.loc[:, important_cols]
    if limit is not None:
        rows_df = rows_df.head(limit)

    records = [
        {
            column: _transaction_value_for_prompt(column, value)
            for column, value in row.items()
        }
        for row in rows_df.to_dict("records")
    ]
    return TransactionBatch(transactions=records)

In [26]:

transactions_for_prompt = build_transaction_batch(cb_df, limit=50)
transaction_context = transactions_for_prompt.model_dump_json(indent=2)
user_prompt = f"""Describe the transactional patterns in this chargeback batch.

Transactions:
{transaction_context}
"""

user_prompt

'Describe the transactional patterns in this chargeback batch.\n\nTransactions:\n{\n  "transactions": [\n    {\n      "cb_timestamp": "2025-06-03 22:44:13",\n      "user_id": "44f3688e-45fd-44ea-81fe-b22d8c7cf1d8",\n      "transaction_id": "PARABILIUM:100159166",\n      "trx_timestamp_mx": "2025-05-18 21:57:55.570000",\n      "amount_pos": 800.0,\n      "operador": "OPENPAY*ADMA          PROVIDENCIA 1JALMX",\n      "mcc_code": "7277",\n      "card_type": "VIRTUAL",\n      "product_type": "CREDIT_5401_BIN",\n      "nombrearchivo": null,\n      "pos_entry_mode": "CNP Manual",\n      "cvv_ind": "has cvv",\n      "metodo_identificacion": null,\n      "three_ds_flow": "CHALLENGE",\n      "afiliacion": "4200578",\n      "adquirente": "12",\n      "country": "MX",\n      "cod_respuesta": "00  "\n    },\n    {\n      "cb_timestamp": "2025-05-21 15:12:43",\n      "user_id": "18918cbe-d254-425a-8a11-9b7cf98d8b4d",\n      "transaction_id": "PARABILIUM:100463184",\n      "trx_timestamp_mx": "2025-05-19 22:28:42.643000",\n      "amount_pos": 2774.0,\n      "operador": "VOLARIS MOTO DEB 2    CIUDAD DE MEX001MX",\n      "mcc_code": "4511",\n      "card_type": "PHYSICAL",\n      "product_type": "PLATINUM",\n      "nombrearchivo": "par250125ProdJSP02_SubEm0004.emb",\n      "pos_entry_mode": "CNP Manual",\n      "cvv_ind": "has cvv",\n      "metodo_identificacion": null,\n      "three_ds_flow": "UNKNOWN",\n      "afiliacion": "8112910",\n      "adquirente": "5",\n      "country": "MX",\n      "cod_respuesta": "00  "\n    },\n    {\n      "cb_timestamp": "2025-06-09 01:47:29",\n      "user_id": "e0b3bdb2-ec5f-4784-a5d4-9950225960c9",\n      "transaction_id": "PARABILIUM:100679780",\n      "trx_timestamp_mx": "2025-05-20 18:30:51.097000",\n      "amount_pos": 109.0,\n      "operador": "TRACTEBEL DGQRO MU    MEXICO DF    DF MX",\n      "mcc_code": "5983",\n      "card_type": "PHYSICAL",\n      "product_type": "CREDIT_5401_BIN",\n      "nombrearchivo": "par240403ProdJSO01_SubEm0001.emb",\n      "pos_entry_mode": "CNP Manual",\n      "cvv_ind": "has cvv",\n      "metodo_identificacion": null,\n      "three_ds_flow": "FRICTIONLESS",\n      "afiliacion": "4040922",\n      "adquirente": "12",\n      "country": "MX",\n      "cod_respuesta": "00  "\n    },\n    {\n      "cb_timestamp": "2025-05-26 20:50:10",\n      "user_id": "f8fb6af7-bb15-40e2-a06a-3206ff35a40f",\n      "transaction_id": "101015177",\n      "trx_timestamp_mx": "2025-05-21 20:01:21.900000",\n      "amount_pos": 349.0,\n      "operador": "KFC ECOMMERCE         CIUDAD DE MEX001MX",\n      "mcc_code": "5814",\n      "card_type": "VIRTUAL",\n      "product_type": "CREDIT_5401_BIN",\n      "nombrearchivo": null,\n      "pos_entry_mode": "CNP Manual",\n      "cvv_ind": "has cvv",\n      "metodo_identificacion": null,\n      "three_ds_flow": "CHALLENGE",\n      "afiliacion": "8419607",\n      "adquirente": "302",\n      "country": "MX",\n      "cod_respuesta": "00  "\n    },\n    {\n      "cb_timestamp": "2025-05-28 14:26:40",\n      "user_id": "69cc717e-f27b-4a0f-b46f-3315d16fd228",\n      "transaction_id": "PARABILIUM:101804609",\n      "trx_timestamp_mx": "2025-05-24 13:16:47.739000",\n      "amount_pos": 263.0,\n      "operador": "SERV CONSULTORIA MK   HUIXQUILUCAN 015MX",\n      "mcc_code": "7392",\n      "card_type": "VIRTUAL",\n      "product_type": "CREDIT_5456_BIN",\n      "nombrearchivo": null,\n      "pos_entry_mode": "CNP Manual",\n      "cvv_ind": "no cvv",\n      "metodo_identificacion": null,\n      "three_ds_flow": "UNKNOWN",\n      "afiliacion": "9628274",\n      "adquirente": "485",\n      "country": "MX",\n      "cod_respuesta": "00  "\n    },\n    {\n      "cb_timestamp": "2025-05-29 13:35:50",\n      "user_id": "01744a1c-8fa6-4346-8f51-e5012538e2d1",\n      "transaction_id": "PARABILIUM:102210993",\n      "trx_timestamp_mx": "2025-05-25 19:08:56.498000",\n      "amount_pos": 999.0,\n      "operador": "ROKU MEXICO           CIUDAD DE MEX001MX",\n      "mcc_code": "5815",\n      "card_type": "PHYSICAL",\n      "product_type": "CREDIT_5401_BIN",\n      "nombrearchivo": "par241219ProdJSO01_SubEm0001.emb",\n      "pos_entry_mode": "CNP Manual",\n      "cvv_ind": "no cvv",\n      "metodo_identificacion": null,\n      "three_ds_flow": "UNKNOWN",\n      "afiliacion": "9088757",\n      "adquirente": "126080",\n      "country": "MX",\n      "cod_respuesta": "00  "\n    },\n    {\n      "cb_timestamp": "2025-05-29 20:19:04",\n      "user_id": "6c7cd4c7-0acc-44b3-b9ee-81d50684fe6c",\n      "transaction_id": "PARABILIUM:102296603",\n      "trx_timestamp_mx": "2025-05-26 03:01:06.947000",\n      "amount_pos": 199.0,\n      "operador": "PAYPAL *ITUNESAPPST APMEXICO CITY  DF MX",\n      "mcc_code": "5399",\n      "card_type": "PHYSICAL",\n      "product_type": "CREDIT_5401_BIN",\n      "nombrearchivo": "par241228ProdJSO01_SubEm0001.emb",\n      "pos_entry_mode": "CNP Manual",\n      "cvv_ind": "no cvv",\n      "metodo_identificacion": null,\n      "three_ds_flow": "UNKNOWN",\n      "afiliacion": "4143789",\n      "adquirente": "12",\n      "country": "MX",\n      "cod_respuesta": "00  "\n    },\n    {\n      "cb_timestamp": "2025-05-28 15:40:54",\n      "user_id": "89b6b876-f11b-4c4e-b961-66d35e270dcc",\n      "transaction_id": "PARABILIUM:102465162",\n      "trx_timestamp_mx": "2025-05-26 16:26:53.054000",\n      "amount_pos": 199.0,\n      "operador": "ZTL*FNPEOPLE          CIUDAD DE MEX001MX",\n      "mcc_code": "5812",\n      "card_type": "PHYSICAL",\n      "product_type": "CREDIT_5401_BIN",\n      "nombrearchivo": "par250510ProdJSO01_SubEm0001.emb",\n      "pos_entry_mode": "Contactless",\n      "cvv_ind": "no cvv",\n      "metodo_identificacion": "No se requiere CVM",\n      "three_ds_flow": "UNKNOWN",\n      "afiliacion": "8826953",\n      "adquirente": "346",\n      "country": "MX",\n      "cod_respuesta": "00  "\n    },\n    {\n      "cb_timestamp": "2025-05-29 13:37:12",\n      "user_id": "071924c6-775b-47ba-95d5-2068c549fb87",\n      "transaction_id": "102705079",\n      "trx_timestamp_mx": "2025-05-27 12:55:04.626000",\n      "amount_pos": 120.0,\n      "operador": "CONEKTA*MIBAIT        DF           DF MX",\n      "mcc_code": "4812",\n      "card_type": "PHYSICAL",\n      "product_type": "CREDIT_5401_BIN",\n      "nombrearchivo": "par250425ProdJSO01_SubEm0001.emb",\n      "pos_entry_mode": "CNP Manual",\n      "cvv_ind": "no cvv",\n      "metodo_identificacion": null,\n      "three_ds_flow": "UNKNOWN",\n      "afiliacion": "9256198",\n      "adquirente": "58",\n      "country": "MX",\n      "cod_respuesta": "00  "\n    },\n    {\n      "cb_timestamp": "2025-05-30 12:12:26",\n      "user_id": "4cd58969-0772-432f-8b53-c5908dafdbf7",\n      "transaction_id": "103068757",\n      "trx_timestamp_mx": "2025-05-28 15:48:20.710000",\n      "amount_pos": 99.0,\n      "operador": "AMAZON PRIME          CIUDAD DE MEX001MX",\n      "mcc_code": "4899",\n      "card_type": "PHYSICAL",\n      "product_type": "CREDIT_5401_BIN",\n      "nombrearchivo": "par250305ProdJSO01_SubEm0001.emb",\n      "pos_entry_mode": "CNP Card On File",\n      "cvv_ind": "no cvv",\n      "metodo_identificacion": null,\n      "three_ds_flow": "UNKNOWN",\n      "afiliacion": "8353766",\n      "adquirente": "544550",\n      "country": "MX",\n      "cod_respuesta": "00  "\n    },\n    {\n      "cb_timestamp": "2025-05-31 04:16:39",\n      "user_id": "6c4ee3fe-1f9a-4c20-a2dc-fc6f756290be",\n      "transaction_id": "103100935",\n      "trx_timestamp_mx": "2025-05-28 17:33:24.447000",\n      "amount_pos": 413.33,\n      "operador": "MERCADO PAGO          CIUDAD DE MEXDF MX",\n      "mcc_code": "4816",\n      "card_type": "VIRTUAL",\n      "product_type": "CREDIT_5401_BIN",\n      "nombrearchivo": null,\n      "pos_entry_mode": "CNP Manual",\n      "cvv_ind": "has cvv",\n      "metodo_identificacion": null,\n      "three_ds_flow": "UNKNOWN",\n      "afiliacion": "4585494",\n      "adquirente": "12",\n      "country": "MX",\n      "cod_respuesta": "00  "\n    },\n    {\n      "cb_timestamp": "2025-06-05 22:55:23",\n      "user_id": "cef55d9b-79c2-4680-b3be-27dec19c79b3",\n      "transaction_id": "103211659",\n      "trx_timestamp_mx": "2025-05-29 00:49:43.404000",\n      "amount_pos": 1.0,\n      "operador": "DLO*DEMERGE MEXICO    MEXICO       CMXMX",\n      "mcc_code": "4121",\n      "card_type": "PHYSICAL",\n      "product_type": "CREDIT_5456_BIN",\n      "nombrearchivo": null,\n      "pos_entry_mode": "CNP Manual",\n      "cvv_ind": "no cvv",\n      "metodo_identificacion": null,\n      "three_ds_flow": "UNKNOWN",\n      "afiliacion": "9439275",\n      "adquirente": "544550",\n      "country": "MX",\n      "cod_respuesta": "00  "\n    },\n    {\n      "cb_timestamp": "2025-08-25 07:09:38",\n      "user_id": "679b1464-699d-462f-a084-0aa66569dcf1",\n      "transaction_id": "0d623fb3-0e37-4fc6-9186-c1676d48c0c6:737640:95294751000000009529475:24015:69749966",\n      "trx_timestamp_mx": "2025-08-21 15:28:23.165000",\n      "amount_pos": 240.15,\n      "operador": null,\n      "mcc_code": "0731",\n      "card_type": "VIRTUAL",\n      "product_type": "CREDIT_5401_BIN",\n      "nombrearchivo": null,\n      "pos_entry_mode": null,\n      "cvv_ind": "unknown",\n      "metodo_identificacion": null,\n      "three_ds_flow": null,\n      "afiliacion": null,\n      "adquirente": null,\n      "country": null,\n      "cod_respuesta": null\n    },\n    {\n      "cb_timestamp": "2025-07-15 16:56:25",\n      "user_id": "409dfd9c-f204-48a6-b859-a964f7f2db91",\n      "transaction_id": "PARABILIUM:101572005",\n      "trx_timestamp_mx": "2025-05-23 17:14:08.335000",\n      "amount_pos": 43.97,\n      "operador": "skinisgreat.com       Limassol        CY",\n      "mcc_code": "5977",\n      "card_type": "PHYSICAL",\n      "product_type": "CREDIT_5401_BIN",\n      "nombrearchivo": "par250319ProdJSO01_SubEm0001.emb",\n      "pos_entry_mode": "CNP Manual",\n      "cvv_ind": "has cvv",\n      "metodo_identificacion": null,\n      "three_ds_flow": "CHALLENGE",\n      "afiliacion": "3870493",\n      "adquirente": "10537",\n      "country": "CY",\n      "cod_respuesta": "00  "\n    },\n    {\n      "cb_timestamp": "2025-05-27 05:18:20",\n      "user_id": "3e0e410a-219e-414a-87b2-9b2cbe85caab",\n      "transaction_id": "PARABILIUM:101992631",\n      "trx_timestamp_mx": "2025-05-25 00:12:35.867000",\n      "amount_pos": 4073.18,\n      "operador": "SHEIN.COM             SINGAPORE    000SG",\n      "mcc_code": "5651",\n      "card_type": "PHYSICAL",\n      "product_type": "PLATINUM",\n      "nombrearchivo": "par250109ProdJSP02_SubEm0004.emb",\n      "pos_entry_mode": "CNP Manual",\n      "cvv_ind": "has cvv",\n      "metodo_identificacion": null,\n      "three_ds_flow": "UNKNOWN",\n      "afiliacion": "2301980",\n      "adquirente": "18622",\n      "country": "SG",\n      "cod_respuesta": "00  "\n    },\n    {\n      "cb_timestamp": "2025-06-06 18:48:12",\n      "user_id": "43a9f964-09bc-41a2-803d-ae639c00aa29",\n      "transaction_id": "PARABILIUM:102435096",\n      "trx_timestamp_mx": "2025-05-26 14:47:23.772000",\n      "amount_pos": 349.0,\n      "operador": "EBW*TIKTOK SHOP3      Ciudad de MexDF MX",\n      "mcc_code": "5399",\n      "card_type": "PHYSICAL",\n      "product_type": "CREDIT_5401_BIN",\n      "nombrearchivo": "par241215ProdJSO01_SubEm0001.emb",\n      "pos_entry_mode": "CNP Manual",\n      "cvv_ind": "has cvv",\n      "metodo_identificacion": null,\n      "three_ds_flow": "UNKNOWN",\n      "afiliacion": "9496336",\n      "adquirente": "544550",\n      "country": "MX",\n      "cod_respuesta": "00  "\n    },\n    {\n      "cb_timestamp": "2025-06-04 23:34:58",\n      "user_id": "72f8d5b3-e2b6-4554-a0fd-304bfdf5a95e",\n      "transaction_id": "PARABILIUM:103138353",\n      "trx_timestamp_mx": "2025-05-28 19:33:05.550000",\n      "amount_pos": 567.97,\n      "operador": "loyalpetspaws.com     +35725008556 000CY",\n      "mcc_code": "5995",\n      "card_type": "PHYSICAL",\n      "product_type": "CREDIT_5401_BIN",\n      "nombrearchivo": "par240530ProdJSO01_SubEm0001.emb",\n      "pos_entry_mode": "CNP Card On File",\n      "cvv_ind": "no cvv",\n      "metodo_identificacion": null,\n      "three_ds_flow": "UNKNOWN",\n      "afiliacion": "1000000",\n      "adquirente": "16120",\n      "country": "CY",\n      "cod_respuesta": "00  "\n    },\n    {\n      "cb_timestamp": "2025-06-09 16:56:49",\n      "user_id": "5c939abc-55eb-4a59-a143-3bbd91544efb",\n      "transaction_id": "PARABILIUM:103422521",\n      "trx_timestamp_mx": "2025-05-29 18:56:34.947000",\n      "amount_pos": 7.29,\n      "operador": "DLO*DiDi MX Payin RideMEXICO       CMXMX",\n      "mcc_code": "4121",\n      "card_type": "PHYSICAL",\n      "product_type": "CREDIT_5401_BIN",\n      "nombrearchivo": "par241022ProdJSO01_SubEm0001.emb",\n      "pos_entry_mode": "CNP Manual",\n      "cvv_ind": "no cvv",\n      "metodo_identificacion": null,\n      "three_ds_flow": "UNKNOWN",\n      "afiliacion": "9439275",\n      "adquirente": "544550",\n      "country": "MX",\n      "cod_respuesta": "00  "\n    },\n    {\n      "cb_timestamp": "2025-06-03 16:27:01",\n      "user_id": "68ff8f92-019e-474d-8805-0288c70be7f9",\n      "transaction_id": "104330098",\n      "trx_timestamp_mx": "2025-06-01 17:15:19.224000",\n      "amount_pos": 170.0,\n      "operador": "STR*CINEMEX COM       CIUDAD DE MEX001MX",\n      "mcc_code": "7832",\n      "card_type": "PHYSICAL",\n      "product_type": "CREDIT_5456_BIN",\n      "nombrearchivo": null,\n      "pos_entry_mode": "CNP Manual",\n      "cvv_ind": "has cvv",\n      "metodo_identificacion": null,\n      "three_ds_flow": "UNKNOWN",\n      "afiliacion": "8941290",\n      "adquirente": "346",\n      "country": "MX",\n      "cod_respuesta": "00  "\n    },\n    {\n      "cb_timestamp": "2025-06-11 16:15:56",\n      "user_id": "935f57a8-5a40-4806-a81d-4464b8743b33",\n      "transaction_id": "PARABILIUM:105778323",\n      "trx_timestamp_mx": "2025-06-06 11:24:11.192000",\n      "amount_pos": 1900.0,\n      "operador": "shein.com             Singapore       SG",\n      "mcc_code": "5999",\n      "card_type": "PHYSICAL",\n      "product_type": "PLATINUM",\n      "nombrearchivo": "par250127ProdJSP02_SubEm0004.emb",\n      "pos_entry_mode": "CNP Card On File",\n      "cvv_ind": "no cvv",\n      "metodo_identificacion": null,\n      "three_ds_flow": "UNKNOWN",\n      "afiliacion": "0000000",\n      "adquirente": "23233",\n      "country": "SG",\n      "cod_respuesta": "00  "\n    },\n    {\n      "cb_timestamp": "2025-06-10 18:30:07",\n      "user_id": "752cb9cf-1349-4954-b0cb-1b71194f76c6",\n      "transaction_id": "PARABILIUM:105893530",\n      "trx_timestamp_mx": "2025-06-06 17:34:27.126000",\n      "amount_pos": 191.51,\n      "operador": "fabtechz.com          +35726023499 000CY",\n      "mcc_code": "5968",\n      "card_type": "PHYSICAL",\n      "product_type": "CREDIT_5401_BIN",\n      "nombrearchivo": "par240613ProdJSO01_SubEm0001.emb",\n      "pos_entry_mode": "CNP Card On File",\n      "cvv_ind": "has cvv",\n      "metodo_identificacion": null,\n      "three_ds_flow": "UNKNOWN",\n      "afiliacion": "1000000",\n      "adquirente": "16120",\n      "country": "CY",\n      "cod_respuesta": "00  "\n    },\n    {\n      "cb_timestamp": "2025-07-25 23:47:39",\n      "user_id": "6c8a9109-b95d-4836-a280-e754d12368e0",\n      "transaction_id": "PARABILIUM:106390456",\n      "trx_timestamp_mx": "2025-06-08 10:46:24.008000",\n      "amount_pos": 55.0,\n      "operador": "OXXO ESTACION SAN JOSEFRESNILLO ZACZA MX",\n      "mcc_code": "5499",\n      "card_type": "PHYSICAL",\n      "product_type": "CREDIT_5401_BIN",\n      "nombrearchivo": "par250528ProdJSO06_SubEm0001.emb",\n      "pos_entry_mode": "Contactless",\n      "cvv_ind": "no cvv",\n      "metodo_identificacion": "No se requiere CVM",\n      "three_ds_flow": "UNKNOWN",\n      "afiliacion": "4238295",\n      "adquirente": "12",\n      "country": "MX",\n      "cod_respuesta": "00  "\n    },\n    {\n      "cb_timestamp": "2025-08-04 19:01:22",\n      "user_id": "f09267ec-5411-4035-bc4b-b7f05ed6b7fa",\n      "transaction_id": "PARABILIUM:106973898",\n      "trx_timestamp_mx": "2025-06-10 08:58:27.172000",\n      "amount_pos": 139.0,\n      "operador": "AMAZON MX MARKETPLACE CIUDAD DE MEX001MX",\n      "mcc_code": "4816",\n      "card_type": "PHYSICAL",\n      "product_type": "CREDIT_5401_BIN",\n      "nombrearchivo": "par250418ProdJSO01_SubEm0001.emb",\n      "pos_entry_mode": "CNP Manual",\n      "cvv_ind": "no cvv",\n      "metodo_identificacion": null,\n      "three_ds_flow": "UNKNOWN",\n      "afiliacion": "7979128",\n      "adquirente": "544550",\n      "country": "MX",\n      "cod_respuesta": "00  "\n    },\n    {\n      "cb_timestamp": "2025-06-12 23:21:21",\n      "user_id": "fae76ec2-7d6b-41e7-b34d-4453529c48ab",\n      "transaction_id": "107103038",\n      "trx_timestamp_mx": "2025-06-10 16:56:05.571000",\n      "amount_pos": 641.16,\n      "operador": "formyfashion.com      +35725008749 000CY",\n      "mcc_code": "5661",\n      "card_type": "PHYSICAL",\n      "product_type": "CREDIT_5456_BIN",\n      "nombrearchivo": null,\n      "pos_entry_mode": "CNP Card On File",\n      "cvv_ind": "no cvv",\n      "metodo_identificacion": null,\n      "three_ds_flow": "UNKNOWN",\n      "afiliacion": "1000000",\n      "adquirente": "16120",\n      "country": "CY",\n      "cod_respuesta": "00  "\n    },\n    {\n      "cb_timestamp": "2025-06-07 11:43:00",\n      "user_id": "ecd5a401-d064-4d5d-85d4-1e9ce337f33f",\n      "transaction_id": "PARABILIUM:104140732",\n      "trx_timestamp_mx": "2025-06-01 00:24:37.710000",\n      "amount_pos": 100.0,\n      "operador": "NUVEIMX*CALIENTE      TIJUANA      BCNMX",\n      "mcc_code": "7941",\n      "card_type": "VIRTUAL",\n      "product_type": "CREDIT_5401_BIN",\n      "nombrearchivo": null,\n      "pos_entry_mode": "CNP Card On File",\n      "cvv_ind": "no cvv",\n      "metodo_identificacion": null,\n      "three_ds_flow": "UNKNOWN",\n      "afiliacion": "4764150",\n      "adquirente": "12",\n      "country": "MX",\n      "cod_respuesta": "00  "\n    },\n    {\n      "cb_timestamp": "2025-06-11 02:41:55",\n      "user_id": "cbd235e5-0bde-4bf6-b202-826760795447",\n      "transaction_id": "104445152",\n      "trx_timestamp_mx": "2025-06-02 00:16:19.080000",\n      "amount_pos": 20.0,\n      "operador": "NUVEIMX*CALIENTE      TIJUANA      BCNMX",\n      "mcc_code": "7941",\n      "card_type": "VIRTUAL",\n      "product_type": "CREDIT_5401_BIN",\n      "nombrearchivo": null,\n      "pos_entry_mode": "CNP Card On File",\n      "cvv_ind": "no cvv",\n      "metodo_identificacion": null,\n      "three_ds_flow": "UNKNOWN",\n      "afiliacion": "4764150",\n      "adquirente": "12",\n      "country": "MX",\n      "cod_respuesta": "00  "\n    },\n    {\n      "cb_timestamp": "2025-06-07 12:20:41",\n      "user_id": "5d505fad-d609-4344-87a3-245afee431ca",\n      "transaction_id": "PARABILIUM:104621379",\n      "trx_timestamp_mx": "2025-06-02 15:37:59.938000",\n      "amount_pos": 395.0,\n      "operador": "Google MobiSystems    Mountain ViewCA US",\n      "mcc_code": "7372",\n      "card_type": "PHYSICAL",\n      "product_type": "CREDIT_5401_BIN",\n      "nombrearchivo": "par240201ProdJSO01_SubEm0001.emb",\n      "pos_entry_mode": "CNP Card On File",\n      "cvv_ind": "no cvv",\n      "metodo_identificacion": null,\n      "three_ds_flow": "UNKNOWN",\n      "afiliacion": "5270210",\n      "adquirente": "14021",\n      "country": "US",\n      "cod_respuesta": "00  "\n    },\n    {\n      "cb_timestamp": "2025-06-08 21:23:14",\n      "user_id": "ff18b7f8-3646-47ed-b8fa-1d8b2e64534b",\n      "transaction_id": "PARABILIUM:104799233",\n      "trx_timestamp_mx": "2025-06-03 06:16:06.145000",\n      "amount_pos": 1306.76,\n      "operador": "SEG BUPA MEXICO 3     CIUDAD DE MEX001MX",\n      "mcc_code": "6300",\n      "card_type": "PHYSICAL",\n      "product_type": "CREDIT_5401_BIN",\n    

In [27]:
transaction_context

'{\n  "transactions": [\n    {\n      "cb_timestamp": "2025-06-03 22:44:13",\n      "user_id": "44f3688e-45fd-44ea-81fe-b22d8c7cf1d8",\n      "transaction_id": "PARABILIUM:100159166",\n      "trx_timestamp_mx": "2025-05-18 21:57:55.570000",\n      "amount_pos": 800.0,\n      "operador": "OPENPAY*ADMA          PROVIDENCIA 1JALMX",\n      "mcc_code": "7277",\n      "card_type": "VIRTUAL",\n      "product_type": "CREDIT_5401_BIN",\n      "nombrearchivo": null,\n      "pos_entry_mode": "CNP Manual",\n      "cvv_ind": "has cvv",\n      "metodo_identificacion": null,\n      "three_ds_flow": "CHALLENGE",\n      "afiliacion": "4200578",\n      "adquirente": "12",\n      "country": "MX",\n      "cod_respuesta": "00  "\n    },\n    {\n      "cb_timestamp": "2025-05-21 15:12:43",\n      "user_id": "18918cbe-d254-425a-8a11-9b7cf98d8b4d",\n      "transaction_id": "PARABILIUM:100463184",\n      "trx_timestamp_mx": "2025-05-19 22:28:42.643000",\n      "amount_pos": 2774.0,\n      "operador": "VOLARIS MOTO DEB 2    CIUDAD DE MEX001MX",\n      "mcc_code": "4511",\n      "card_type": "PHYSICAL",\n      "product_type": "PLATINUM",\n      "nombrearchivo": "par250125ProdJSP02_SubEm0004.emb",\n      "pos_entry_mode": "CNP Manual",\n      "cvv_ind": "has cvv",\n      "metodo_identificacion": null,\n      "three_ds_flow": "UNKNOWN",\n      "afiliacion": "8112910",\n      "adquirente": "5",\n      "country": "MX",\n      "cod_respuesta": "00  "\n    },\n    {\n      "cb_timestamp": "2025-06-09 01:47:29",\n      "user_id": "e0b3bdb2-ec5f-4784-a5d4-9950225960c9",\n      "transaction_id": "PARABILIUM:100679780",\n      "trx_timestamp_mx": "2025-05-20 18:30:51.097000",\n      "amount_pos": 109.0,\n      "operador": "TRACTEBEL DGQRO MU    MEXICO DF    DF MX",\n      "mcc_code": "5983",\n      "card_type": "PHYSICAL",\n      "product_type": "CREDIT_5401_BIN",\n      "nombrearchivo": "par240403ProdJSO01_SubEm0001.emb",\n      "pos_entry_mode": "CNP Manual",\n      "cvv_ind": "has cvv",\n      "metodo_identificacion": null,\n      "three_ds_flow": "FRICTIONLESS",\n      "afiliacion": "4040922",\n      "adquirente": "12",\n      "country": "MX",\n      "cod_respuesta": "00  "\n    },\n    {\n      "cb_timestamp": "2025-05-26 20:50:10",\n      "user_id": "f8fb6af7-bb15-40e2-a06a-3206ff35a40f",\n      "transaction_id": "101015177",\n      "trx_timestamp_mx": "2025-05-21 20:01:21.900000",\n      "amount_pos": 349.0,\n      "operador": "KFC ECOMMERCE         CIUDAD DE MEX001MX",\n      "mcc_code": "5814",\n      "card_type": "VIRTUAL",\n      "product_type": "CREDIT_5401_BIN",\n      "nombrearchivo": null,\n      "pos_entry_mode": "CNP Manual",\n      "cvv_ind": "has cvv",\n      "metodo_identificacion": null,\n      "three_ds_flow": "CHALLENGE",\n      "afiliacion": "8419607",\n      "adquirente": "302",\n      "country": "MX",\n      "cod_respuesta": "00  "\n    },\n    {\n      "cb_timestamp": "2025-05-28 14:26:40",\n      "user_id": "69cc717e-f27b-4a0f-b46f-3315d16fd228",\n      "transaction_id": "PARABILIUM:101804609",\n      "trx_timestamp_mx": "2025-05-24 13:16:47.739000",\n      "amount_pos": 263.0,\n      "operador": "SERV CONSULTORIA MK   HUIXQUILUCAN 015MX",\n      "mcc_code": "7392",\n      "card_type": "VIRTUAL",\n      "product_type": "CREDIT_5456_BIN",\n      "nombrearchivo": null,\n      "pos_entry_mode": "CNP Manual",\n      "cvv_ind": "no cvv",\n      "metodo_identificacion": null,\n      "three_ds_flow": "UNKNOWN",\n      "afiliacion": "9628274",\n      "adquirente": "485",\n      "country": "MX",\n      "cod_respuesta": "00  "\n    },\n    {\n      "cb_timestamp": "2025-05-29 13:35:50",\n      "user_id": "01744a1c-8fa6-4346-8f51-e5012538e2d1",\n      "transaction_id": "PARABILIUM:102210993",\n      "trx_timestamp_mx": "2025-05-25 19:08:56.498000",\n      "amount_pos": 999.0,\n      "operador": "ROKU MEXICO           CIUDAD DE MEX001MX",\n      "mcc_code": "5815",\n      "card_type": "PHYSICAL",\n      "product_type": "CREDIT_5401_BIN",\n      "nombrearchivo": "par241219ProdJSO01_SubEm0001.emb",\n      "pos_entry_mode": "CNP Manual",\n      "cvv_ind": "no cvv",\n      "metodo_identificacion": null,\n      "three_ds_flow": "UNKNOWN",\n      "afiliacion": "9088757",\n      "adquirente": "126080",\n      "country": "MX",\n      "cod_respuesta": "00  "\n    },\n    {\n      "cb_timestamp": "2025-05-29 20:19:04",\n      "user_id": "6c7cd4c7-0acc-44b3-b9ee-81d50684fe6c",\n      "transaction_id": "PARABILIUM:102296603",\n      "trx_timestamp_mx": "2025-05-26 03:01:06.947000",\n      "amount_pos": 199.0,\n      "operador": "PAYPAL *ITUNESAPPST APMEXICO CITY  DF MX",\n      "mcc_code": "5399",\n      "card_type": "PHYSICAL",\n      "product_type": "CREDIT_5401_BIN",\n      "nombrearchivo": "par241228ProdJSO01_SubEm0001.emb",\n      "pos_entry_mode": "CNP Manual",\n      "cvv_ind": "no cvv",\n      "metodo_identificacion": null,\n      "three_ds_flow": "UNKNOWN",\n      "afiliacion": "4143789",\n      "adquirente": "12",\n      "country": "MX",\n      "cod_respuesta": "00  "\n    },\n    {\n      "cb_timestamp": "2025-05-28 15:40:54",\n      "user_id": "89b6b876-f11b-4c4e-b961-66d35e270dcc",\n      "transaction_id": "PARABILIUM:102465162",\n      "trx_timestamp_mx": "2025-05-26 16:26:53.054000",\n      "amount_pos": 199.0,\n      "operador": "ZTL*FNPEOPLE          CIUDAD DE MEX001MX",\n      "mcc_code": "5812",\n      "card_type": "PHYSICAL",\n      "product_type": "CREDIT_5401_BIN",\n      "nombrearchivo": "par250510ProdJSO01_SubEm0001.emb",\n      "pos_entry_mode": "Contactless",\n      "cvv_ind": "no cvv",\n      "metodo_identificacion": "No se requiere CVM",\n      "three_ds_flow": "UNKNOWN",\n      "afiliacion": "8826953",\n      "adquirente": "346",\n      "country": "MX",\n      "cod_respuesta": "00  "\n    },\n    {\n      "cb_timestamp": "2025-05-29 13:37:12",\n      "user_id": "071924c6-775b-47ba-95d5-2068c549fb87",\n      "transaction_id": "102705079",\n      "trx_timestamp_mx": "2025-05-27 12:55:04.626000",\n      "amount_pos": 120.0,\n      "operador": "CONEKTA*MIBAIT        DF           DF MX",\n      "mcc_code": "4812",\n      "card_type": "PHYSICAL",\n      "product_type": "CREDIT_5401_BIN",\n      "nombrearchivo": "par250425ProdJSO01_SubEm0001.emb",\n      "pos_entry_mode": "CNP Manual",\n      "cvv_ind": "no cvv",\n      "metodo_identificacion": null,\n      "three_ds_flow": "UNKNOWN",\n      "afiliacion": "9256198",\n      "adquirente": "58",\n      "country": "MX",\n      "cod_respuesta": "00  "\n    },\n    {\n      "cb_timestamp": "2025-05-30 12:12:26",\n      "user_id": "4cd58969-0772-432f-8b53-c5908dafdbf7",\n      "transaction_id": "103068757",\n      "trx_timestamp_mx": "2025-05-28 15:48:20.710000",\n      "amount_pos": 99.0,\n      "operador": "AMAZON PRIME          CIUDAD DE MEX001MX",\n      "mcc_code": "4899",\n      "card_type": "PHYSICAL",\n      "product_type": "CREDIT_5401_BIN",\n      "nombrearchivo": "par250305ProdJSO01_SubEm0001.emb",\n      "pos_entry_mode": "CNP Card On File",\n      "cvv_ind": "no cvv",\n      "metodo_identificacion": null,\n      "three_ds_flow": "UNKNOWN",\n      "afiliacion": "8353766",\n      "adquirente": "544550",\n      "country": "MX",\n      "cod_respuesta": "00  "\n    },\n    {\n      "cb_timestamp": "2025-05-31 04:16:39",\n      "user_id": "6c4ee3fe-1f9a-4c20-a2dc-fc6f756290be",\n      "transaction_id": "103100935",\n      "trx_timestamp_mx": "2025-05-28 17:33:24.447000",\n      "amount_pos": 413.33,\n      "operador": "MERCADO PAGO          CIUDAD DE MEXDF MX",\n      "mcc_code": "4816",\n      "card_type": "VIRTUAL",\n      "product_type": "CREDIT_5401_BIN",\n      "nombrearchivo": null,\n      "pos_entry_mode": "CNP Manual",\n      "cvv_ind": "has cvv",\n      "metodo_identificacion": null,\n      "three_ds_flow": "UNKNOWN",\n      "afiliacion": "4585494",\n      "adquirente": "12",\n      "country": "MX",\n      "cod_respuesta": "00  "\n    },\n    {\n      "cb_timestamp": "2025-06-05 22:55:23",\n      "user_id": "cef55d9b-79c2-4680-b3be-27dec19c79b3",\n      "transaction_id": "103211659",\n      "trx_timestamp_mx": "2025-05-29 00:49:43.404000",\n      "amount_pos": 1.0,\n      "operador": "DLO*DEMERGE MEXICO    MEXICO       CMXMX",\n      "mcc_code": "4121",\n      "card_type": "PHYSICAL",\n      "product_type": "CREDIT_5456_BIN",\n      "nombrearchivo": null,\n      "pos_entry_mode": "CNP Manual",\n      "cvv_ind": "no cvv",\n      "metodo_identificacion": null,\n      "three_ds_flow": "UNKNOWN",\n      "afiliacion": "9439275",\n      "adquirente": "544550",\n      "country": "MX",\n      "cod_respuesta": "00  "\n    },\n    {\n      "cb_timestamp": "2025-08-25 07:09:38",\n      "user_id": "679b1464-699d-462f-a084-0aa66569dcf1",\n      "transaction_id": "0d623fb3-0e37-4fc6-9186-c1676d48c0c6:737640:95294751000000009529475:24015:69749966",\n      "trx_timestamp_mx": "2025-08-21 15:28:23.165000",\n      "amount_pos": 240.15,\n      "operador": null,\n      "mcc_code": "0731",\n      "card_type": "VIRTUAL",\n      "product_type": "CREDIT_5401_BIN",\n      "nombrearchivo": null,\n      "pos_entry_mode": null,\n      "cvv_ind": "unknown",\n      "metodo_identificacion": null,\n      "three_ds_flow": null,\n      "afiliacion": null,\n      "adquirente": null,\n      "country": null,\n      "cod_respuesta": null\n    },\n    {\n      "cb_timestamp": "2025-07-15 16:56:25",\n      "user_id": "409dfd9c-f204-48a6-b859-a964f7f2db91",\n      "transaction_id": "PARABILIUM:101572005",\n      "trx_timestamp_mx": "2025-05-23 17:14:08.335000",\n      "amount_pos": 43.97,\n      "operador": "skinisgreat.com       Limassol        CY",\n      "mcc_code": "5977",\n      "card_type": "PHYSICAL",\n      "product_type": "CREDIT_5401_BIN",\n      "nombrearchivo": "par250319ProdJSO01_SubEm0001.emb",\n      "pos_entry_mode": "CNP Manual",\n      "cvv_ind": "has cvv",\n      "metodo_identificacion": null,\n      "three_ds_flow": "CHALLENGE",\n      "afiliacion": "3870493",\n      "adquirente": "10537",\n      "country": "CY",\n      "cod_respuesta": "00  "\n    },\n    {\n      "cb_timestamp": "2025-05-27 05:18:20",\n      "user_id": "3e0e410a-219e-414a-87b2-9b2cbe85caab",\n      "transaction_id": "PARABILIUM:101992631",\n      "trx_timestamp_mx": "2025-05-25 00:12:35.867000",\n      "amount_pos": 4073.18,\n      "operador": "SHEIN.COM             SINGAPORE    000SG",\n      "mcc_code": "5651",\n      "card_type": "PHYSICAL",\n      "product_type": "PLATINUM",\n      "nombrearchivo": "par250109ProdJSP02_SubEm0004.emb",\n      "pos_entry_mode": "CNP Manual",\n      "cvv_ind": "has cvv",\n      "metodo_identificacion": null,\n      "three_ds_flow": "UNKNOWN",\n      "afiliacion": "2301980",\n      "adquirente": "18622",\n      "country": "SG",\n      "cod_respuesta": "00  "\n    },\n    {\n      "cb_timestamp": "2025-06-06 18:48:12",\n      "user_id": "43a9f964-09bc-41a2-803d-ae639c00aa29",\n      "transaction_id": "PARABILIUM:102435096",\n      "trx_timestamp_mx": "2025-05-26 14:47:23.772000",\n      "amount_pos": 349.0,\n      "operador": "EBW*TIKTOK SHOP3      Ciudad de MexDF MX",\n      "mcc_code": "5399",\n      "card_type": "PHYSICAL",\n      "product_type": "CREDIT_5401_BIN",\n      "nombrearchivo": "par241215ProdJSO01_SubEm0001.emb",\n      "pos_entry_mode": "CNP Manual",\n      "cvv_ind": "has cvv",\n      "metodo_identificacion": null,\n      "three_ds_flow": "UNKNOWN",\n      "afiliacion": "9496336",\n      "adquirente": "544550",\n      "country": "MX",\n      "cod_respuesta": "00  "\n    },\n    {\n      "cb_timestamp": "2025-06-04 23:34:58",\n      "user_id": "72f8d5b3-e2b6-4554-a0fd-304bfdf5a95e",\n      "transaction_id": "PARABILIUM:103138353",\n      "trx_timestamp_mx": "2025-05-28 19:33:05.550000",\n      "amount_pos": 567.97,\n      "operador": "loyalpetspaws.com     +35725008556 000CY",\n      "mcc_code": "5995",\n      "card_type": "PHYSICAL",\n      "product_type": "CREDIT_5401_BIN",\n      "nombrearchivo": "par240530ProdJSO01_SubEm0001.emb",\n      "pos_entry_mode": "CNP Card On File",\n      "cvv_ind": "no cvv",\n      "metodo_identificacion": null,\n      "three_ds_flow": "UNKNOWN",\n      "afiliacion": "1000000",\n      "adquirente": "16120",\n      "country": "CY",\n      "cod_respuesta": "00  "\n    },\n    {\n      "cb_timestamp": "2025-06-09 16:56:49",\n      "user_id": "5c939abc-55eb-4a59-a143-3bbd91544efb",\n      "transaction_id": "PARABILIUM:103422521",\n      "trx_timestamp_mx": "2025-05-29 18:56:34.947000",\n      "amount_pos": 7.29,\n      "operador": "DLO*DiDi MX Payin RideMEXICO       CMXMX",\n      "mcc_code": "4121",\n      "card_type": "PHYSICAL",\n      "product_type": "CREDIT_5401_BIN",\n      "nombrearchivo": "par241022ProdJSO01_SubEm0001.emb",\n      "pos_entry_mode": "CNP Manual",\n      "cvv_ind": "no cvv",\n      "metodo_identificacion": null,\n      "three_ds_flow": "UNKNOWN",\n      "afiliacion": "9439275",\n      "adquirente": "544550",\n      "country": "MX",\n      "cod_respuesta": "00  "\n    },\n    {\n      "cb_timestamp": "2025-06-03 16:27:01",\n      "user_id": "68ff8f92-019e-474d-8805-0288c70be7f9",\n      "transaction_id": "104330098",\n      "trx_timestamp_mx": "2025-06-01 17:15:19.224000",\n      "amount_pos": 170.0,\n      "operador": "STR*CINEMEX COM       CIUDAD DE MEX001MX",\n      "mcc_code": "7832",\n      "card_type": "PHYSICAL",\n      "product_type": "CREDIT_5456_BIN",\n      "nombrearchivo": null,\n      "pos_entry_mode": "CNP Manual",\n      "cvv_ind": "has cvv",\n      "metodo_identificacion": null,\n      "three_ds_flow": "UNKNOWN",\n      "afiliacion": "8941290",\n      "adquirente": "346",\n      "country": "MX",\n      "cod_respuesta": "00  "\n    },\n    {\n      "cb_timestamp": "2025-06-11 16:15:56",\n      "user_id": "935f57a8-5a40-4806-a81d-4464b8743b33",\n      "transaction_id": "PARABILIUM:105778323",\n      "trx_timestamp_mx": "2025-06-06 11:24:11.192000",\n      "amount_pos": 1900.0,\n      "operador": "shein.com             Singapore       SG",\n      "mcc_code": "5999",\n      "card_type": "PHYSICAL",\n      "product_type": "PLATINUM",\n      "nombrearchivo": "par250127ProdJSP02_SubEm0004.emb",\n      "pos_entry_mode": "CNP Card On File",\n      "cvv_ind": "no cvv",\n      "metodo_identificacion": null,\n      "three_ds_flow": "UNKNOWN",\n      "afiliacion": "0000000",\n      "adquirente": "23233",\n      "country": "SG",\n      "cod_respuesta": "00  "\n    },\n    {\n      "cb_timestamp": "2025-06-10 18:30:07",\n      "user_id": "752cb9cf-1349-4954-b0cb-1b71194f76c6",\n      "transaction_id": "PARABILIUM:105893530",\n      "trx_timestamp_mx": "2025-06-06 17:34:27.126000",\n      "amount_pos": 191.51,\n      "operador": "fabtechz.com          +35726023499 000CY",\n      "mcc_code": "5968",\n      "card_type": "PHYSICAL",\n      "product_type": "CREDIT_5401_BIN",\n      "nombrearchivo": "par240613ProdJSO01_SubEm0001.emb",\n      "pos_entry_mode": "CNP Card On File",\n      "cvv_ind": "has cvv",\n      "metodo_identificacion": null,\n      "three_ds_flow": "UNKNOWN",\n      "afiliacion": "1000000",\n      "adquirente": "16120",\n      "country": "CY",\n      "cod_respuesta": "00  "\n    },\n    {\n      "cb_timestamp": "2025-07-25 23:47:39",\n      "user_id": "6c8a9109-b95d-4836-a280-e754d12368e0",\n      "transaction_id": "PARABILIUM:106390456",\n      "trx_timestamp_mx": "2025-06-08 10:46:24.008000",\n      "amount_pos": 55.0,\n      "operador": "OXXO ESTACION SAN JOSEFRESNILLO ZACZA MX",\n      "mcc_code": "5499",\n      "card_type": "PHYSICAL",\n      "product_type": "CREDIT_5401_BIN",\n      "nombrearchivo": "par250528ProdJSO06_SubEm0001.emb",\n      "pos_entry_mode": "Contactless",\n      "cvv_ind": "no cvv",\n      "metodo_identificacion": "No se requiere CVM",\n      "three_ds_flow": "UNKNOWN",\n      "afiliacion": "4238295",\n      "adquirente": "12",\n      "country": "MX",\n      "cod_respuesta": "00  "\n    },\n    {\n      "cb_timestamp": "2025-08-04 19:01:22",\n      "user_id": "f09267ec-5411-4035-bc4b-b7f05ed6b7fa",\n      "transaction_id": "PARABILIUM:106973898",\n      "trx_timestamp_mx": "2025-06-10 08:58:27.172000",\n      "amount_pos": 139.0,\n      "operador": "AMAZON MX MARKETPLACE CIUDAD DE MEX001MX",\n      "mcc_code": "4816",\n      "card_type": "PHYSICAL",\n      "product_type": "CREDIT_5401_BIN",\n      "nombrearchivo": "par250418ProdJSO01_SubEm0001.emb",\n      "pos_entry_mode": "CNP Manual",\n      "cvv_ind": "no cvv",\n      "metodo_identificacion": null,\n      "three_ds_flow": "UNKNOWN",\n      "afiliacion": "7979128",\n      "adquirente": "544550",\n      "country": "MX",\n      "cod_respuesta": "00  "\n    },\n    {\n      "cb_timestamp": "2025-06-12 23:21:21",\n      "user_id": "fae76ec2-7d6b-41e7-b34d-4453529c48ab",\n      "transaction_id": "107103038",\n      "trx_timestamp_mx": "2025-06-10 16:56:05.571000",\n      "amount_pos": 641.16,\n      "operador": "formyfashion.com      +35725008749 000CY",\n      "mcc_code": "5661",\n      "card_type": "PHYSICAL",\n      "product_type": "CREDIT_5456_BIN",\n      "nombrearchivo": null,\n      "pos_entry_mode": "CNP Card On File",\n      "cvv_ind": "no cvv",\n      "metodo_identificacion": null,\n      "three_ds_flow": "UNKNOWN",\n      "afiliacion": "1000000",\n      "adquirente": "16120",\n      "country": "CY",\n      "cod_respuesta": "00  "\n    },\n    {\n      "cb_timestamp": "2025-06-07 11:43:00",\n      "user_id": "ecd5a401-d064-4d5d-85d4-1e9ce337f33f",\n      "transaction_id": "PARABILIUM:104140732",\n      "trx_timestamp_mx": "2025-06-01 00:24:37.710000",\n      "amount_pos": 100.0,\n      "operador": "NUVEIMX*CALIENTE      TIJUANA      BCNMX",\n      "mcc_code": "7941",\n      "card_type": "VIRTUAL",\n      "product_type": "CREDIT_5401_BIN",\n      "nombrearchivo": null,\n      "pos_entry_mode": "CNP Card On File",\n      "cvv_ind": "no cvv",\n      "metodo_identificacion": null,\n      "three_ds_flow": "UNKNOWN",\n      "afiliacion": "4764150",\n      "adquirente": "12",\n      "country": "MX",\n      "cod_respuesta": "00  "\n    },\n    {\n      "cb_timestamp": "2025-06-11 02:41:55",\n      "user_id": "cbd235e5-0bde-4bf6-b202-826760795447",\n      "transaction_id": "104445152",\n      "trx_timestamp_mx": "2025-06-02 00:16:19.080000",\n      "amount_pos": 20.0,\n      "operador": "NUVEIMX*CALIENTE      TIJUANA      BCNMX",\n      "mcc_code": "7941",\n      "card_type": "VIRTUAL",\n      "product_type": "CREDIT_5401_BIN",\n      "nombrearchivo": null,\n      "pos_entry_mode": "CNP Card On File",\n      "cvv_ind": "no cvv",\n      "metodo_identificacion": null,\n      "three_ds_flow": "UNKNOWN",\n      "afiliacion": "4764150",\n      "adquirente": "12",\n      "country": "MX",\n      "cod_respuesta": "00  "\n    },\n    {\n      "cb_timestamp": "2025-06-07 12:20:41",\n      "user_id": "5d505fad-d609-4344-87a3-245afee431ca",\n      "transaction_id": "PARABILIUM:104621379",\n      "trx_timestamp_mx": "2025-06-02 15:37:59.938000",\n      "amount_pos": 395.0,\n      "operador": "Google MobiSystems    Mountain ViewCA US",\n      "mcc_code": "7372",\n      "card_type": "PHYSICAL",\n      "product_type": "CREDIT_5401_BIN",\n      "nombrearchivo": "par240201ProdJSO01_SubEm0001.emb",\n      "pos_entry_mode": "CNP Card On File",\n      "cvv_ind": "no cvv",\n      "metodo_identificacion": null,\n      "three_ds_flow": "UNKNOWN",\n      "afiliacion": "5270210",\n      "adquirente": "14021",\n      "country": "US",\n      "cod_respuesta": "00  "\n    },\n    {\n      "cb_timestamp": "2025-06-08 21:23:14",\n      "user_id": "ff18b7f8-3646-47ed-b8fa-1d8b2e64534b",\n      "transaction_id": "PARABILIUM:104799233",\n      "trx_timestamp_mx": "2025-06-03 06:16:06.145000",\n      "amount_pos": 1306.76,\n      "operador": "SEG BUPA MEXICO 3     CIUDAD DE MEX001MX",\n      "mcc_code": "6300",\n      "card_type": "PHYSICAL",\n      "product_type": "CREDIT_5401_BIN",\n      "nombrearchivo": "par240927ProdJSO14_SubEm0001.emb",\n      "pos_entry_mode": 

## Local Python transaction analyst agent

These cells expose `cb_df[important_cols]` to the agent through controlled local Python tools instead of dumping the full dataframe into the prompt.

In [28]:
from types import SimpleNamespace

from transactional_describer.transaction_agent import (
    TransactionalDescription,
    build_transaction_analyst_agent,
    get_transaction_schema,
    prepare_transaction_context,
    run_transaction_python,
)

In [29]:
transaction_agent_context = prepare_transaction_context(
    cb_df[cb_df['trx_timestamp_mx'] >= '2026-05-25'],
    important_cols,
    sample_name="chargeback_transactions",
)

print(f"Saved agent dataset to: {transaction_agent_context.data_path}")
print(f"Columns exposed: {transaction_agent_context.columns}")

Saved agent dataset to: /var/folders/ch/hb63cwpx22l_1jl5cqj7wp_80000gq/T/chargeback_transactions_9c83fd49fe154846a56dbf38414a4fb0.jsonl
Columns exposed: ['cb_timestamp', 'user_id', 'transaction_id', 'trx_timestamp_mx', 'amount_pos', 'operador', 'mcc_code', 'card_type', 'product_type', 'nombrearchivo', 'pos_entry_mode', 'cvv_ind', 'metodo_identificacion', 'three_ds_flow', 'afiliacion', 'adquirente', 'country', 'cod_respuesta']

In [30]:
schema_preview = get_transaction_schema(SimpleNamespace(context=transaction_agent_context))
print(schema_preview[:4000])

{"row_count": 1486, "column_count": 18, "columns_exposed": ["cb_timestamp", "user_id", "transaction_id", "trx_timestamp_mx", "amount_pos", "operador", "mcc_code", "card_type", "product_type", "nombrearchivo", "pos_entry_mode", "cvv_ind", "metodo_identificacion", "three_ds_flow", "afiliacion", "adquirente", "country", "cod_respuesta"], "columns": [{"name": "cb_timestamp", "dtype": "str", "null_count": 0, "null_rate": 0.0, "sample_values": ["2026-05-29T01:23:46.539", "2026-05-30T18:42:44.344", "2026-05-30T13:35:42.202", "2026-05-29T06:15:37.986", "2026-05-29T02:36:39.048"]}, {"name": "user_id", "dtype": "str", "null_count": 0, "null_rate": 0.0, "sample_values": ["38248b6b-82d0-4d7b-a5b5-24cb53934dc7", "568eacf2-e234-4e76-a0fe-e754384f27e1", "ca066a4c-6c3e-472b-8cdd-d070e35947ed", "1b7ab48f-cf5e-4e61-8dda-9c3d41739b45", "135575d6-9e0b-4885-97b7-8f7da8ed5841"]}, {"name": "transaction_id", "dtype": "str", "null_count": 0, "null_rate": 0.0, "sample_values": ["PARABILIUM:235790753", "PARABILIUM:236822080", "PARABILIUM:235341420", "PARABILIUM:235793515", "PARABILIUM:235902481"]}, {"name": "trx_timestamp_mx", "dtype": "str", "null_count": 0, "null_rate": 0.0, "sample_values": ["2026-05-26T13:20:43.676", "2026-05-28T17:49:10.869", "2026-05-25T13:19:23.374", "2026-05-26T13:27:06.970", "2026-05-26T17:39:00.274"]}, {"name": "amount_pos", "dtype": "float64", "null_count": 0, "null_rate": 0.0, "sample_values": ["10000.0", "8169.05", "159.0", "75.0", "1079.0"]}, {"name": "operador", "dtype": "str", "null_count": 169, "null_rate": 0.1137, "sample_values": ["NUVEIMX*CALIENTE      TIJUANA      BCNMX", "ELEKTRA COM MX 1      MEXICO DF    001MX", "Google YouTube        Mountain ViewCA US", "MERPAGO*ELRECUERDO    TONALA       000MX", "PAYUMEX*ADIDAS        BAHIA_BLANCA MEXMX"]}, {"name": "mcc_code", "dtype": "float64", "null_count": 12, "null_rate": 0.0081, "sample_values": ["7941.0", "5311.0", "5818.0", "5411.0", "5699.0"]}, {"name": "card_type", "dtype": "str", "null_count": 0, "null_rate": 0.0, "sample_values": ["VIRTUAL", "PHYSICAL"]}, {"name": "product_type", "dtype": "str", "null_count": 0, "null_rate": 0.0, "sample_values": ["CREDIT_5401_BIN", "PLATINUM", "CREDIT_5456_BIN", "BUSINESS_NEW_BIN"]}, {"name": "nombrearchivo", "dtype": "str", "null_count": 776, "null_rate": 0.5222, "sample_values": ["par260316ProdJSO02_SubEm0001.emb", "par251117ProdJSO02_SubEm0001.emb", "par251029ProdJSO02_SubEm0001.emb", "par250708ProdJSO02_SubEm0001.emb", "par251220ProdJSO02_SubEm0001.emb"]}, {"name": "pos_entry_mode", "dtype": "str", "null_count": 169, "null_rate": 0.1137, "sample_values": ["CNP Card On File", "CNP Manual", "Contactless", "Integrated Circuit Read"]}, {"name": "cvv_ind", "dtype": "str", "null_count": 0, "null_rate": 0.0, "sample_values": ["no cvv", "has cvv", "unknown"]}, {"name": "metodo_identificacion", "dtype": "str", "null_count": 1289, "null_rate": 0.8674, "sample_values": ["Verificacion de PIN cifrado realizada por el chip de la tarjeta", "No se requiere CVM", "Firma (papel)", "PIN cifrado verificado en linea"]}, {"name": "three_ds_flow", "dtype": "str", "null_count": 169, "null_rate": 0.1137, "sample_values": ["UNKNOWN", "CHALLENGE", "FRICTIONLESS", "EXEMPT_OR_INFO"]}, {"name": "afiliacion", "dtype": "str", "null_count": 169, "null_rate": 0.1137, "sample_values": ["4764150", "7942693", "5270210", "8847759", "4248025"]}, {"name": "adquirente", "dtype": "float64", "null_count": 169, "null_rate": 0.1137, "sample_values": ["12.0", "1.0", "14021.0", "3499.0", "420.0"]}, {"name": "country", "dtype": "str", "null_count": 169, "null_rate": 0.1137, "sample_values": ["MX", "US", "CY", "BR", "LT"]}, {"name": "cod_respuesta", "dtype": "float64", "null_count": 169, "null_rate": 0.1137, "sample_values": ["0.0"]}], "date_ranges": {"cb_timestamp": {"min": "2026-05-26T00:41:42.431000", "max": "2026-06-01T07:07:51.593000"}, "trx_timestamp_mx": {"min": "2026-05-25T00:11:14.738000", "max": "2026-05-31T20:18:51.650000"}}, "amount_pos": {"count": 1486, "sum":

In [31]:
tool_preview = run_transaction_python(
    SimpleNamespace(context=transaction_agent_context),
    """
top_merchants = (
    df.groupby("operador", dropna=False)
      .agg(
          transactions=("transaction_id", "nunique"),
          users=("user_id", "nunique"),
          amount=("amount_pos", "sum"),
      )
      .sort_values(["transactions", "amount"], ascending=False)
      .head(10)
)
top_merchants
    """,
)
print(tool_preview[:5000])

{"status": "ok", "stdout": "", "result": {"type": "DataFrame", "shape": [10, 3], "columns": ["transactions", "users", "amount"], "records": [{"transactions": 169, "users": 144, "amount": 179507.54}, {"transactions": 69, "users": 62, "amount": 6550.21}, {"transactions": 50, "users": 44, "amount": 15388.6}, {"transactions": 47, "users": 30, "amount": 4530.0}, {"transactions": 37, "users": 31, "amount": 101889.03}, {"transactions": 26, "users": 25, "amount": 3122.0}, {"transactions": 24, "users": 24, "amount": 2515.0}, {"transactions": 20, "users": 20, "amount": 7769.81}, {"transactions": 18, "users": 15, "amount": 3632.58}, {"transactions": 16, "users": 11, "amount": 1450.0}]}}

In [37]:
from agents import Runner

transaction_agent = build_transaction_analyst_agent()

analyst_request = """
Describe the common transaction patterns in this chargeback batch.
Focus on common merchants, repeated user behavior, product/card type differences,
authentication patterns (CVV/3DS/POS entry), countries/acquirers, response codes, amounts, and timing.
Use Python before answering and cite the computed evidence.
""".strip()

transaction_agent_result = await Runner.run(
    transaction_agent,
    analyst_request,
    context=transaction_agent_context,
    max_turns=8,
)

transaction_description = transaction_agent_result.final_output
transaction_description.model_dump()

OPENAI_API_KEY is not set, skipping trace export
OPENAI_API_KEY is not set, skipping trace export
OPENAI_API_KEY is not set, skipping trace export

{'summary': 'This batch is dominated by low-value CNP activity, mostly in Mexico, with a small set of recurring merchants and many single-transaction users. Authentication data is sparse or defaulted in many records, so pattern confidence is strongest on merchant, country, amount, and entry-mode trends.',
 'key_patterns': [{'title': 'A few merchants repeat heavily, but most users are one-off',
   'evidence': 'Top merchants include DLO*UBER RIDE (69 tx), APPLE.COM/BILL (50), TELCEL RECARGAS FONY (47), MERCADO PAGO (37), and AMAZONCOM INC AMZN (26). User concentration is low: 1,146 users for 1,486 rows, with 170 users having >1 tx and max 15 tx/user.',
   'examples': []},
  {'title': 'CNP/manual transactions dominate',
   'evidence': 'pos_entry_mode shows CNP Manual 816/1,486 (54.9%), CNP Card On File 220 (14.8%), Contactless 171 (11.5%), and Integrated Circuit Read 110 (7.4%); 169 rows are null for POS entry mode.',
   'examples': []},
  {'title': 'CVV and 3DS are often missing/unknown',
   'evidence': "cvv_ind is 'no cvv' in 913 rows (61.4%), 'has cvv' in 393 (26.5%), and 'unknown' in 180 (12.1%). three_ds_flow is 'UNKNOWN' in 1,214 rows (81.7%), with CHALLENGE 78 (5.2%), FRICTIONLESS 24 (1.6%), and only 1 EXEMPT_OR_INFO.",
   'examples': []},
  {'title': 'Mexico and the US are the main countries; many records are Mexico-linked',
   'evidence': 'country counts: MX 1,034 (69.6%), US 175 (11.8%), then GB 21, CY 20, HK 12, and smaller counts; 169 rows have null country.',
   'examples': []},
  {'title': 'Virtual cards skew higher in amount than physical cards',
   'evidence': 'Card split is even (743 virtual, 743 physical), but virtual cards have higher average and max amount: mean 1,406.53 vs 718.95 for physical; median 239 vs 149; max 59,000 vs 27,015.',
   'examples': []},
  {'title': 'Higher-value spend is concentrated in a few product types',
   'evidence': 'product_type counts: CREDIT_5401_BIN 1,299 rows (87.4%), CREDIT_5456_BIN 96, PLATINUM 89, BUSINESS_NEW_BIN 2. Average amount is highest for PLATINUM (2,858.49; median 983.15) and CREDIT_5456_BIN (1,432.60; median 213.30), vs CREDIT_5401_BIN (905.10; median 183.00).',
   'examples': []},
  {'title': 'Most transactions are small, but there is a long tail',
   'evidence': 'Amount median is 199.0, mean 1,062.74, p95 4,757.25, max 59,000. Bucket counts show 23 tx under 10, 139 in 10-50, 227 in 50-100, 340 in 100-200, 295 in 200-500, and 74 at 5k+.',
   'examples': []},
  {'title': 'Transactions cluster mid-afternoon to evening, with a decline at the end of the window',
   'evidence': 'By hour, activity peaks at 19:00 (163 tx), then 16:00 (114), 17:00 (110), and 20:00 (102). By day, volume falls from 378 on 2026-05-25 and 364 on 2026-05-26 to 7 on 2026-05-31. trx_timestamp_mx spans 2026-05-25 to 2026-05-31.',
   'examples': []},
  {'title': 'Merchant-specific auth patterns are very uniform',
   'evidence': 'Examples: DLO*UBER RIDE has 69/69 MX, CNP Manual, no cvv, UNKNOWN 3DS, and response code 0. APPLE.COM/BILL has 50/50 US, CNP Card On File, no cvv, UNKNOWN 3DS, response 0. TELCEL RECARGAS FONY is 47/47 MX, CNP Manual, mostly has cvv (44/47), UNKNOWN 3DS, response 0.',
   'examples': []},
  {'title': 'Response codes are almost entirely a single code',
   'evidence': 'cod_respuesta is 0.0 in 1,317 rows; 169 rows are null. No other response codes appear in the extracted counts.',
   'examples': []}],
 'caveats': ['169 rows (~11.4%) have null values in merchant/POS/3DS/acquirer/country/response fields, so some patterns are based on the non-null subset.',
  'metodo_identificacion is missing in 1,289 rows (86.7%), so chip/PIN/CVM behavior cannot be generalized well from this batch.',
  'This description is descriptive only; the data shown here do not by themselves establish cause or intent.'],
 'confidence': 0.88}